--[[----------------------------------------------------------------------------
    deDE — ueberschreibt enUS. Vollstaendig, weil Deutsch die Erstsprache ist.
------------------------------------------------------------------------------]]

local _, GA = ...

GA.Core.Locale:Register("deDE", {
    NAV_DASHBOARD    = "Dashboard",
    NAV_ARMORY       = "Armory",
    NAV_CHARACTERS   = "Charaktere",
    NAV_LOOTCOUNCIL  = "LootCouncil",
    NAV_LOOTHISTORY  = "Historie",
    NAV_WISHLIST     = "Wunschliste",
    NAV_GEAR         = "Gear-Tracking",
    NAV_ARMORY_LONG  = "Gilden-Armory",
    DASH_CHANGES     = "Letzte Aenderungen",
    DASH_ONLINE      = "Gilde online",
    DASH_NO_CHANGES  = "Noch keine Aenderungen erfasst.",
    DASH_SNAPSHOT_ROW = "Ausruestungsstand erfasst, Itemlevel %s",
    DASH_NOBODY_ONLINE = "Niemand online",
    ARMORY_CHARACTERS = "Charaktere",
    ARMORY_SEARCH    = "Name suchen",
    SET_NATIVE       = "Fenstervorlagen",
    NAV_ANALYTICS    = "Statistik",
    NAV_SETTINGS     = "Einstellungen",

    BTN_CLOSE        = "Schliessen",
    BTN_REFRESH      = "Aktualisieren",
    BTN_EXPORT       = "Exportieren",
    BTN_IMPORT       = "Importieren",
    BTN_COPY_HINT    = "Strg+A, dann Strg+C",
    UNKNOWN          = "unbekannt",
    NEVER            = "nie",
    JUST_NOW         = "gerade eben",
    AGO_MINUTES      = "vor %d min",
    AGO_HOURS        = "vor %d Std.",
    AGO_DAYS         = "vor %d Tagen",
    PHASE_LABEL      = "Phase %d",

    DASH_MY_CHARACTER = "Mein Charakter",
    DASH_GUILD        = "Gilde",
    DASH_LOOT_STATE   = "Loot",
    DASH_ITEMLEVEL    = "Itemlevel",
    DASH_EQUIPPED     = "%d von %d Plaetzen belegt",
    DASH_MEMBERS      = "%d Mitglieder, %d online",
    DASH_NOT_IN_GUILD = "Nicht in einer Gilde",
    DASH_LOOT_METHOD  = "Lootmethode",
    DASH_LOOT_MASTER  = "Du bist Pluendermeister",
    DASH_LOOT_NOTMASTER = "Pluendermeister ist nicht aktiv",
    DASH_COMPUTED     = "aus den angelegten Gegenstaenden berechnet",

    ARMORY_SLOT       = "Platz",
    ARMORY_ITEM       = "Gegenstand",
    ARMORY_ILVL       = "Ilvl",
    ARMORY_EMPTY      = "leer",
    ARMORY_SNAPSHOT   = "Stand: %s",
    ARMORY_NO_DATA    = "Fuer diesen Charakter liegen noch keine Ausruestungsdaten vor.",
    ARMORY_OWN_HINT   = "Deine eigene Ausruestung wird bei jeder Aenderung automatisch erfasst.",
    ARMORY_STALE      = "Letzte Aktualisierung %s — das sind KEINE Live-Daten.",

    ROLE_ADMIN        = "Administrator",
    ROLE_LOOTMASTER   = "Lootmeister",
    ROLE_COUNCIL      = "Council",
    ROLE_MEMBER       = "Mitglied",

    SET_WINDOW        = "Fenster",
    SET_SCALE         = "Skalierung: %.2f",
    SET_DEBUG         = "Debug umschalten",
    SET_CLIENT        = "Dieser Client",
    SET_DATA          = "Daten",
    SET_PUBLISH       = "Meine Charaktere mit der Gilde teilen",
    SET_PUBLISH_HINT  = "Hinaus gehen Ausruestung, Itemlevel, Klasse und Stufe — und die bestaetigten Vergaben. NICHT hinaus gehen Notizen, Spitznamen und dein Aenderungsjournal. Erzwingen kann das Addon nichts: Wer nicht teilt, erscheint in der Versionsuebersicht als ohne Antwort.",

    -- Ergaenzt 19.09.2026: Dashboard/Armory-Texte, Inspect, Quellen
    LEVEL_FMT               = "Stufe %s",
    LOOT_NO_GROUP           = "Nicht in einer Gruppe",
    LOOT_NO_GROUP_HINT      = "Die Lootmethode gilt erst in Gruppe oder Schlachtzug.",
    LOOT_FREEFORALL         = "Jeder gegen jeden",
    LOOT_ROUNDROBIN         = "Reihum",
    LOOT_MASTER             = "Pluendermeister",
    LOOT_GROUP              = "Gruppenwurf",
    LOOT_NBG                = "Bedarf vor Gier",
    LOOT_PERSONAL           = "Persoenliche Beute",
    CHANGE_EQUIPPED         = "%s: %s angelegt",
    CHANGE_UNEQUIPPED       = "%s: %s abgelegt",
    ITEM_FALLBACK           = "Gegenstand %s",
    ARMORY_LOADOUT_CAPTURED = "Talent-Loadout erfasst",
    ARMORY_SNAPSHOT_COUNT   = "%d Ausruestungsstaende seit %s",
    ARMORY_OWN              = "Dein Charakter",
    ARMORY_GUILD_MEMBER     = "Gildenmitglied",
    COL_NAME                = "Name",
    COL_CLASS               = "Klasse",
    COL_ILVL                = "Ilvl",
    ARMORY_INSPECT_TARGET   = "Ziel inspizieren",
    ARMORY_INSPECT_HINT     = "Spieler anvisieren (bis ~28 m), dann inspizieren.",
    ARMORY_INSPECT_SENT     = "Inspect angefordert: %s",
    ARMORY_INSPECT_DONE     = "Inspect erfasst: %s",
    ARMORY_INSPECT_FAILED   = "Keine Antwort auf den Inspect von %s.",
    INSPECT_REASON_notarget = "Kein Ziel",
    INSPECT_REASON_notplayer= "Ziel ist kein Spieler",
    INSPECT_REASON_self     = "Das bist du selbst",
    INSPECT_REASON_combat   = "Nicht im Kampf",
    INSPECT_REASON_range    = "Ziel ausser Reichweite",
    INSPECT_REASON_api      = "Inspect nicht verfuegbar",
    INSPECT_REASON_busy     = "Ein Inspect laeuft noch",
    SOURCE_self             = "eigener Charakter",
    SOURCE_inspect          = "Inspect",
    SOURCE_sync             = "Gilden-Sync",
    SET_ON                  = "an",
    SET_OFF                 = "aus",
    SET_STATS               = "%d Charaktere · %d Vergaben · %d Journaleintraege · Schema %s",

    -- Charaktere/Spieler und Gear-Verlauf (Phase 3)
    CHAR_PLAYERS            = "Spieler",
    CHAR_PLAYER_DETAIL      = "%d Charaktere  ·  %s",
    CHAR_MEMBERS            = "Charaktere",
    CHAR_MEMBERS_OF         = "Charaktere von %s",
    CHAR_UNASSIGNED         = "Nicht zugeordnet",
    CHAR_MAIN_TAG           = "|cffe5cc80(Main)|r",
    CHAR_SET_MAIN           = "Main setzen",
    CHAR_UNLINK             = "Loesen",
    CHAR_ASSIGN             = "Zuordnen",
    CHAR_NEW_PLAYER         = "Neuer Spieler",
    CHAR_ORIGIN_account     = "bewiesen",
    CHAR_ORIGIN_manual      = "gesetzt",
    CHAR_ORIGIN_claim       = "behauptet",
    CHAR_PROVEN_HINT        = "Derselbe WoW-Account — das ist keine Eintragung, sondern eine Tatsache.",
    CHAR_ALREADY_MAIN       = "Ist bereits der Main.",
    CHAR_PICK_PLAYER        = "Erst links einen Spieler waehlen.",
    CHAR_ROLE_HINT          = "Die Rolle haengt am Main; Twinks erben sie.",
    CHAR_ROLE_CURRENT       = "Aktuelle Rolle.",
    CHAR_NEED_ADMIN         = "Nur ein Administrator kann Rollen aendern.",
    CHAR_CONTEXT            = "%d Spieler  ·  %d nicht zugeordnet",
    GEAR_HISTORY            = "Itemlevel-Verlauf",
    GEAR_NO_HISTORY         = "Noch kein Verlauf — er entsteht, sobald sich die Ausruestung aendert.",
    GEAR_SNAPSHOTS          = "%d Staende",
    GEAR_DISCRETE           = "Je Balken ein erfasster Stand, kein Verlauf dazwischen.",

    -- Loot-Historie und Erfassung (Phase 5)
    COL_WHEN                    = "Wann",
    COL_ITEM                    = "Gegenstand",
    COL_WHO                     = "Empfaenger",
    COL_STATUS                  = "Status",
    COL_PROOF                   = "Bestaetigt durch",
    LOOT_SEARCH                 = "Gegenstand oder Spieler",
    LOOT_ONLY_OPEN              = "Nur offene",
    LOOT_DETAIL                 = "Details",
    LOOT_PICK_ROW               = "Eine Zeile waehlen.",
    LOOT_SUMMARY                = "%d erfasst  ·  %d offen  ·  %d von Hand bestaetigt",
    LOOT_CONTEXT                = "%d Eintraege",
    LOOT_STATUS_DETECTED        = "erkannt",
    LOOT_STATUS_SESSION_OPEN    = "Bewerbung laeuft",
    LOOT_STATUS_AWARDED         = "vergeben",
    LOOT_STATUS_TRANSFER_PENDING= "Uebergabe offen",
    LOOT_STATUS_RECEIVED        = "erhalten",
    LOOT_STATUS_EQUIPPED        = "angelegt",
    LOOT_STATUS_CANCELLED       = "abgebrochen",
    LOOT_STATUS_CORRECTED       = "korrigiert",
    LOOT_PROOF_MASTER_LOOT      = "Pluendermeister",
    LOOT_PROOF_TRADE            = "Handel",
    LOOT_PROOF_LOOT_CHAT        = "Chat-Meldung",
    LOOT_PROOF_MANUAL           = "von Hand",
    LOOT_PROOF_NONE             = "—",
    LOOT_PROOF_STRONG           = "Vom Spiel gemeldet",
    LOOT_PROOF_WEAK             = "Schwacher Beleg",
    LOOT_FROM_ENCOUNTER         = "Kampf: %s",
    LOOT_FROM_CREATURE          = "Von %s",
    LOOT_FROM_NPCID             = "NPC %s",
    LOOT_FROM_UNKNOWN           = "Herkunft unbekannt",
    SET_LOOT                    = "Loot-Erfassung",
    SET_LOOT_THRESHOLD          = "Ab Qualitaet: %s",
    SET_LOOT_SOLO               = "Auch ausserhalb der Gruppe erfassen",
    SET_LOOT_SOLO_HINT          = "Zum Testen allein. Im Betrieb aus, sonst landet jeder Questgegenstand in der Historie.",
    SET_MEASURED                = "Beobachtete Lootmethoden: %s",
    SET_MEASURED_NONE           = "noch keine",
    QUALITY_2                   = "Gruen",
    QUALITY_3                   = "Blau",
    QUALITY_4                   = "Episch",
    LOOT_CORRECTION_OF          = "Korrektur von %s",
    LOOT_CORRECTED_BY           = "Korrigiert durch %s",

    -- Minimap-Knopf
    MINIMAP_LEFT                = "Linksklick: Fenster oeffnen",
    MINIMAP_RIGHT               = "Rechtsklick: Einstellungen",
    MINIMAP_DRAG                = "Ziehen: Knopf verschieben",
    MINIMAP_STATS               = "%d Charaktere  ·  %d Vergaben",
    SET_MINIMAP                 = "Minimap-Knopf anzeigen",

    -- LootCouncil (Phase 4)
    BID_TITLE                   = "Beute-Bewerbung",
    BID_HINT                    = "Waehle je Gegenstand eine Antwort.",
    BID_FROM                    = "Lootmeister: %s",
    BID_ANSWERED                = "Geantwortet: %s",
    BID_FAILED                  = "Bewerbung konnte nicht gesendet werden (%s).",
    COUNCIL_OPEN                = "Session oeffnen",
    COUNCIL_CLOSE               = "Schliessen",
    COUNCIL_ITEMS               = "Gegenstaende",
    COUNCIL_DETECTED_TITLE      = "Erkannte Beute",
    COUNCIL_CANDIDATES          = "Bewerber",
    COUNCIL_CANDIDATES_FOR      = "Bewerber: %s",
    COUNCIL_VOTE                = "Stimme",
    COUNCIL_AWARD               = "Vergeben",
    COUNCIL_BIDS                = "%d Bew.",
    COUNCIL_RUNNING             = "Session laeuft: %d Gegenstaende  ·  Lootmeister %s",
    COUNCIL_DETECTED            = "%d Gegenstaende erkannt — Session noch nicht geoeffnet",
    COUNCIL_IDLE                = "Keine offene Session, nichts erkannt.",
    COUNCIL_FOOTER              = "%d Bewerbungen  ·  %d Stimmen abgegeben",
    COUNCIL_PICK_ITEM           = "Links einen Gegenstand waehlen.",
    COUNCIL_HINT                = "Beute wird beim Oeffnen des Lootfensters erkannt. Dann hier die Session oeffnen.",
    COUNCIL_CONTEXT_OPEN        = "Session laeuft",
    COUNCIL_NEED_LOOTMASTER     = "Nur der Lootmeister kann das.",
    COUNCIL_NEED_COUNCIL        = "Nur das Council kann abstimmen.",
    COUNCIL_ALREADY_OPEN        = "Es laeuft schon eine Session.",
    COUNCIL_NO_SESSION          = "Keine offene Session.",
    COUNCIL_NOTHING_DETECTED    = "Keine erkannte Beute.",
    COUNCIL_NO_CANDIDATE        = "%s steht nicht in der Pluendermeister-Liste — Uebergabe bleibt offen.",
    COUNCIL_ERR_notallowed      = "Dafuer fehlt die Berechtigung.",
    COUNCIL_ERR_alreadyopen     = "Es laeuft schon eine Session.",
    COUNCIL_ERR_noitems         = "Keine Gegenstaende ausgewaehlt.",
    COUNCIL_ERR_noeligible      = "Nichts Erkanntes zum Oeffnen.",
    COUNCIL_ERR_nobid           = "Dieser Spieler hat sich nicht beworben.",
    COUNCIL_ERR_closed          = "Die Session ist geschlossen.",

    -- Wunschliste und Statistik (Phase 6)
    WISH_MINE                 = "Meine Wunschliste",
    WISH_MINE_COUNT           = "Meine Wunschliste — %d offen, %d erfuellt",
    WISH_OTHERS               = "Wer will das noch?",
    WISH_OTHERS_FOR           = "Wer will noch: %s",
    WISH_INPUT                = "Wowhead-Link, Itemlink, ID oder Name",
    WISH_DROP_HINT            = "Wowhead-Link einfuegen, Itemlink, Item-ID oder Namen tippen.",
    WISH_NO_ITEM              = "Kein Gegenstand erkannt — Link einfuegen oder Namen tippen.",
    WISH_SEARCH_TITLE         = "Suchtreffer (%d)",
    WISH_SEARCH_EMPTY         = "Nichts gefunden. Das Verzeichnis kennt %d Gegenstaende.",
    WISH_SEARCH_HINT          = "Es enthaelt nur, was dieser Client schon gesehen hat — ein Addon kann Wowhead nicht abfragen. Einen Wowhead-Link einfuegen geht immer.",
    WISH_SEARCH_STATUS        = "Suche im Verzeichnis dieses Clients (%d Gegenstaende). Treffer anklicken.",
    SET_ITEMINDEX             = "Itemverzeichnis: %d Gegenstaende",
    SET_SYNC                  = "Abgleich: %d andere Clients gesehen, %d Widersprueche",
    EXPORT_TITLE              = "Export fuer die Webapp",
    EXPORT_DONE               = "Export aufgebaut: %d Charaktere, %d Vergaben, %d KB.",
    EXPORT_HINT               = "In die Datei kommt er beim Ausloggen oder /reload — ein Addon kann nicht selbst ins Netz.",
    SET_EXPORT                = "Export: %d KB, Stand %s",
    SET_EXPORT_NONE           = "Export: noch keiner aufgebaut",
    ANNOUNCE_AWARD            = "%s an %s",
    ANNOUNCE_REASON           = " (%s)",
    ANNOUNCE_SOURCE           = " — %s",
    ANNOUNCE_LIMIT            = "Ankuendigungen gestoppt: %d in dieser Sitzung ist die Grenze.",
    SET_ANNOUNCE              = "Bestaetigte Vergaben im Gildenchat ankuendigen",
    SET_ANNOUNCE_HINT         = "Nur bestaetigte Uebergaben, nur vom Lootmeister, hoechstens eine je 3 Sekunden. Hat die Gilde eine Discord-Bruecke am Gildenchat, landet es auch dort.",
    SET_COLLECTOR             = "Sammlerbetrieb: stuendlich neu laden",
    SET_COLLECTOR_HINT        = "Der Client schreibt die Datei fuer die Webapp NUR beim Ausloggen und bei /reload. Diese Einstellung laedt alle %d Minuten neu — nie im Kampf, nie bei laufender Lootsession. Nur fuer einen Client gedacht, der dafuer parkt.",
    EXPORT_RELOAD_SOON        = "Guild Armory laedt in %d Sekunden neu (Sammlerbetrieb).",

    IMPORT_TITLE              = "Sicherung einlesen",
    IMPORT_HINT               = "Exportblock hier einfuegen. Der Import fuegt hinzu und ueberschreibt nichts: Selbst gemessene Ausruestung bleibt, widersprechende Vergaben kommen ins Journal.",
    IMPORT_FROM               = "Aus %s, exportiert von %s (%s)",
    IMPORT_CHARS              = "Charaktere: %d neu, %d aktualisiert, %d unveraendert",
    IMPORT_AWARDS             = "Vergaben: %d neu, %d schon bekannt",
    IMPORT_CONFLICTS          = "%d Widersprueche — sie kommen ins Journal, nichts wird ueberschrieben",
    IMPORT_REST               = "Wunschlisten: %d  ·  Spielerprofile: %d  ·  Gegenstaende: %d",
    IMPORT_CONFIRM            = "Zum Uebernehmen noch einmal: /ga import",
    IMPORT_DONE               = "Import fertig: %d Charaktere, %d Vergaben, %d Widersprueche.",
    IMPORT_ERR_empty          = "Nichts eingefuegt.",
    IMPORT_ERR_badjson        = "Das ist kein gueltiger Exportblock.",
    IMPORT_ERR_badformat      = "Fremdes Format — das stammt nicht von Guild Armory.",
    IMPORT_ERR_newer          = "Die Sicherung stammt aus einer neueren Fassung. Addon aktualisieren.",
    IMPORT_ERR_noexport       = "In dieser Datenbank liegt kein Exportblock. Erst /ga export.",

    HIST_JOINED               = "beigetreten",
    HIST_LEFT                 = "nicht mehr im Roster",
    HIST_PROMOTED             = "befoerdert",
    HIST_DEMOTED              = "herabgestuft",
    HIST_KNOWN_SINCE          = "bekannt seit %s",
    HIST_JOINED_SINCE         = "beigetreten %s",
    HIST_FROM_RANK            = "von %s",

    TIP_WISHED                = "Auf der Wunschliste:",
    TIP_AND_MORE              = "und %d weitere",
    TIP_LAST_AWARD            = "Zuletzt vergeben an %s (%s)",
    TIP_ILVL                  = "Itemlevel %s  ·  %s, %s",
    TIP_LAST_LOOT             = "Zuletzt erhalten: %s (%s)",
    SET_TOOLTIPS              = "Tooltips ergaenzen",
    SET_TOOLTIPS_HINT         = "Wunschlisten-Treffer am Gegenstand, Itemlevel und letzte Vergabe am Spieler. Fremde Staende stehen immer mit Quelle und Alter dabei.",
    NOTE_NICKNAME             = "Spitzname",
    NOTE_NOTE                 = "Notiz",
    NOTE_HINT                 = "Bleibt auf diesem Client. Notizen ueber Mitspieler wandern nicht ungefragt durch die Gilde.",
    WISH_REMOVE               = "Entfernen",
    WISH_FULFILLED            = "erhalten %s",
    WISH_ALREADY_GOT          = "hat ihn schon",
    WISH_NOBODY_ELSE          = "Sonst niemand.",
    WISH_PICK                 = "Links einen Eintrag waehlen.",
    WISH_CONTEXT              = "%d offene Wuensche",
    WISH_ERR_noitem           = "Kein Gegenstand erkannt.",
    WISH_ERR_nocharacter      = "Kein Charakter.",
    WISH_ERR_unknownpriority  = "Unbekannte Prioritaet.",
    ANA_BY_PLAYER             = "Je Spieler",
    ANA_BY_CHARACTER          = "Je Charakter",
    ANA_BY_SOURCE             = "Je Herkunft",
    ANA_BY_RESPONSE           = "Je Antwort",
    ANA_BY_QUALITY            = "Je Qualitaet",
    ANA_RANGE_ALL             = "Gesamt",
    ANA_RANGE_7               = "7 Tage",
    ANA_RANGE_30              = "30 Tage",
    ANA_RANGE_90              = "90 Tage",
    ANA_TABLE                 = "Auswertung",
    ANA_TIMELINE              = "Verlauf",
    ANA_ACTIVE                = "Bereits ausgewaehlt.",
    ANA_DELIVERED             = "bestaetigt erhalten",
    ANA_UNKNOWN               = "Herkunft unbekannt",
    ANA_NO_DATA               = "Noch keine bestaetigten Vergaben.",
    ANA_PENDING               = "%d offen",
    ANA_MANUAL                = "%d von Hand",
    ANA_CLAIMED               = "Zuordnung behauptet",
    ANA_UNLINKED              = "ohne Profil",
    ANA_SUM_PENDING           = "%d Zuschlaege ohne bestaetigte Uebergabe",
    ANA_SUM_STRONG            = "%d vom Spiel gemeldet",
    ANA_SUM_CHAT              = "%d nur per Chat-Meldung",
    ANA_SUM_MANUAL            = "%d nur von Hand bestaetigt",
    ANA_SUM_UNKNOWN           = "%d ohne belegte Herkunft",
    ANA_SUM_SINCE             = "aelteste %s",
    ANA_TIMELINE_HINT         = "Ein Balken je Tag mit bestaetigter Uebergabe. Tage ohne Vergabe fehlen — die Reihe zeigt Ereignisse, keine Messreihe.",
    ANA_CONTEXT               = "%d erhalten  ·  %d offen",

    COUNCIL_ON_WISHLIST       = "Wunschliste: %s",
    COUNCIL_WISH_DONE         = "(schon erhalten)",

    SET_TRUSTED               = "Das ist meine eigene Sicherung",
    SET_TRUSTED_HINT          = "Nur dann bleiben bewiesene Main/Twink-Zuordnungen bewiesen. Aus einer fremden Datei waren sie der Beweis des Exporteurs, nicht deiner — sie werden dann zu \"behauptet\".",

    TODO_TITLE        = "Noch nicht gebaut",
    TODO_LOOTCOUNCIL  = "Lootsessions, Bewerbungen, Council-Abstimmung und Lootmeister-Ansicht.",
    TODO_LOOTHISTORY  = "Jede bestaetigte Vergabe mit Status, Empfaenger und Council-Entscheidung.",
    TODO_WISHLIST     = "Wunschlisten je Charakter und je Spieler, abgeglichen mit Vergaben.",
    TODO_GEAR         = "Ausruestungsstaende ueber die Zeit, Itemlevel-Kurve, Charaktervergleich.",
    TODO_ANALYTICS    = "Loot je Spieler, Charakter, Raid, Boss, Qualitaet und Zeitraum.",

    -- Council-Rotation
    ROTATION_TITLE            = "Council-Rotation",
    ROTATION_ANNOUNCE         = "Council-Rotation: %s sitzen heute mit im Council (%d h).",
    ROTATION_WHISPER          = "Du sitzt fuer die naechsten %d Stunden mit im Loot-Council. Du kannst bei Vergaben abstimmen — /ga council oeffnet die Ansicht.",
    ROTATION_ROTATE           = "Rotieren",
    ROTATION_CLEAR            = "Sitze beenden",
    ROTATION_SEATS            = "Sitze je Rotation",
    ROTATION_HOURS            = "Dauer in Stunden",
    ROTATION_ENABLED          = "Council-Rotation verwenden",
    ROTATION_ANNOUNCE_OPT     = "Rotation ankuendigen und anfluestern",
    ROTATION_ACTIVE           = "Laufende Sitze",
    ROTATION_NONE             = "Kein Sitz auf Zeit vergeben.",
    ROTATION_CYCLE            = "Zyklus: %d von %d",
    ROTATION_CYCLED           = "Neuer Zyklus begonnen",
    ROTATION_EXPIRES          = "laeuft ab %s",
    ROTATION_TEMPORARY        = "auf Zeit",
    ROTATION_ERR_NOTALLOWED   = "Nur der Lootmeister kann rotieren.",
    ROTATION_ERR_NOGROUP      = "Dafuer braucht es eine Gruppe.",
    ROTATION_ERR_NOPOOL       = "Niemand im Schlachtzug kommt in Frage.",
    ROTATION_ERR_NOSEATS      = "Mindestens ein Sitz.",
    ROTATION_DONE             = "Rotiert: %s",

    -- Versionsuebersicht
    VERSION_TITLE             = "Versionen",
    VERSION_CHECK             = "Abfragen",
    VERSION_RUNNING           = "Frage laeuft ...",
    VERSION_CURRENT           = "aktuell",
    VERSION_OUTDATED          = "veraltet",
    VERSION_NEWER             = "neuer",
    VERSION_UNKNOWN           = "Fassung unlesbar",
    VERSION_SILENT            = "keine Antwort",
    VERSION_SILENT_HINT       = "Keine Antwort heisst nicht, dass jemand das Addon nicht hat: offline, ausser Reichweite oder Nachricht verloren sind genauso moeglich.",
    VERSION_SUMMARY           = "%d aktuell · %d veraltet · %d ohne Antwort",
    VERSION_SCOPE_GROUP       = "Gruppe",
    VERSION_SCOPE_GUILD       = "Gilde",

    -- Offene Uebergaben
    HANDOVER_TITLE            = "Offene Uebergaben",
    HANDOVER_REMIND           = "%d Gegenstaende in deinen Taschen gehoeren anderen: %s",
    HANDOVER_MORE             = " und %d weitere",
    HANDOVER_NONE             = "Nichts offen.",
    HANDOVER_CARRYING         = "In den Taschen",
    HANDOVER_MISSING          = "Nicht in den Taschen",
    HANDOVER_MISSING_HINT     = "Kann in der Bank liegen, angelegt sein oder vom Empfaenger selbst aufgenommen worden sein. Das Addon aendert deshalb nichts von allein.",
    HANDOVER_WAITING          = "wartet seit %s",

    SET_STORAGE      = "Speicher: %s",

    STORAGE_EMPTY    = "Der Client hat keine gespeicherten Daten geliefert — die Datenbank beginnt leer. Auf der Forever-Beta ist das ein bekannter Fehler: Geschrieben wird korrekt, gelesen nicht. Alles, was du heute eintraegst, ist nach dem naechsten Anmelden weg.",

    -- Wuerfeln
    ROLL_TITLE                = "Wuerfeln",
    ROLL_ANNOUNCE             = "Wuerfeln auf %s — /roll %d-%d, %d Sekunden.",
    ROLL_OPEN                 = "Wurf oeffnen",
    ROLL_CLOSE                = "Beenden",
    ROLL_RUNNING              = "Wurfrunde laeuft: %s (%d-%d)",
    ROLL_IDLE                 = "Keine Wurfrunde offen.",
    ROLL_COUNT                = "%d Wuerfe, %d fehlen noch",
    ROLL_WINNER               = "Hoechster Wurf: %s mit %d",
    ROLL_TIE                  = "Gleichstand bei %d — %s",
    ROLL_TIE_HINT             = "Das Addon waehlt hier niemanden aus. Wie es weitergeht, entscheidet der Raid.",
    ROLL_INVALID_RANGE        = "falsche Spanne",
    ROLL_INVALID_SECOND       = "Zweitwurf",
    ROLL_NOBODY               = "Niemand hat gewuerfelt.",
    ROLL_ERR_RUNNING          = "Es laeuft schon eine Wurfrunde.",
    ROLL_ERR_NOGROUP          = "Dafuer braucht es eine Gruppe.",
    ROLL_ERR_RANGE            = "Die Spanne ergibt keinen Sinn.",

    -- Reservierungen und Plus-Eins
    SOFTRES_TITLE             = "Reservierungen",
    SOFTRES_OPEN              = "Runde oeffnen",
    SOFTRES_CLOSE             = "Runde beenden",
    SOFTRES_NONE              = "Keine Reservierungsrunde offen.",
    SOFTRES_STATS             = "%d Reservierungen von %d Spielern, %d umkaempft",
    SOFTRES_DROPPED           = "Reserviert: %s — %s",
    SOFTRES_ORIGIN_LIST       = "eingetragen",
    SOFTRES_ORIGIN_CLAIM      = "selbst angemeldet",
    SOFTRES_CONTESTED         = "Mehrfach reserviert",
    SOFTRES_OVERLIMIT         = "Ueber der Grenze",
    SOFTRES_IMPORTED          = "%d Reservierungen eingelesen, %d uebersprungen",
    SOFTRES_HINT              = "Eine Reservierung gilt fuer diesen Abend, nicht dauerhaft — und das Addon teilt nichts automatisch zu.",
    SOFTRES_ERR_NOROUND       = "Keine Reservierungsrunde offen.",
    SOFTRES_ERR_NOTALLOWED    = "Nur der Lootmeister kann eine Runde oeffnen.",
    PLUSONE_TITLE             = "Plus Eins",
    PLUSONE_ROW               = "%s: %d (%d gerechnet, %d Ausgleich)",
    PLUSONE_MANUAL_HINT       = "%d davon nur von Hand bestaetigt",
    PLUSONE_HINT              = "Gerechnet aus den bestaetigten Vergaben — nicht gefuehrt. Die Zahl kann der Historie nicht widersprechen.",

    COUNCIL_RESERVED = "reserviert (%s)",

    SOFTRES_ACK_ok            = "Reservierung eingetragen.",
    SOFTRES_ACK_noround       = "Es laeuft keine Reservierungsrunde.",
    SOFTRES_ACK_duplicate     = "Hast du schon reserviert.",
    SOFTRES_ACK_overlimit     = "Du liegst ueber der Grenze — eingetragen, aber der Lootmeister sieht es.",
    SOFTRES_ACK_removed       = "Reservierung zurueckgenommen.",
    SOFTRES_ACK_notfound      = "Da war nichts zurueckzunehmen.",
    SOFTRES_CLAIM             = "Fuer heute reservieren",
    SOFTRES_MINE              = "Meine Reservierungen",
    SOFTRES_VS_WISHLIST       = "Wunschliste heisst 'kann ich gebrauchen' und gilt dauerhaft. Eine Reservierung heisst 'das ist heute meins' und gilt nur diesen Abend.",
    SOFTRES_ERR_NOGROUP2      = "Dafuer braucht es eine Gruppe.",

    SET_PUBLISH_ON   = "Ausruestungsdaten werden in der Gilde geteilt.",

    ATLAS_START      = "AtlasLoot wird eingelesen: %d Gegenstaende ...",
    ATLAS_DONE       = "AtlasLoot eingelesen: %d Gegenstaende, %d Namen aufgeloest.",
    ATLAS_STATS      = "AtlasLoot: %d Fundstellen bekannt, %d Namen aufgeloest.",
    ATLAS_MISSING    = "AtlasLootClassic ist nicht installiert — die Suche nutzt nur, was dieser Client selbst gesehen hat.",
    ATLAS_SOURCE     = "Fundort: %s",
    ATLAS_OFFER      = "AtlasLoot gefunden. /ga atlas liest die Fundorte ein und erweitert die Suche.",

    ATLAS_LOAD           = "AtlasLoot laden",
    ATLAS_LOADED         = "AtlasLoot: %d Fundorte",
    ATLAS_RUNNING        = "AtlasLoot wird eingelesen — das dauert ein paar Sekunden.",
    ATLAS_RUNNING_SHORT  = "laedt ...",
    ATLAS_ERR_RUNNING    = "Laeuft schon.",
    ATLAS_ERR_NOTINSTALLED = "AtlasLootClassic ist nicht installiert.",
    ATLAS_ERR_NOITEMDB   = "AtlasLoot ist da, hat aber keine lesbare Datenbank.",
    ATLAS_ERR_NOSTORAGE  = "AtlasLoot ist da, hat aber keine lesbare Datenbank.",
    ATLAS_ERR_EMPTY      = "AtlasLoot hat noch nichts geladen — Datenmodule fehlen oder sind aus.",
})

-- Sprache JETZT anwenden, nicht erst bei PLAYER_LOGIN: Alle folgenden Dateien
-- (Views, MainFrame) lesen `L.XYZ` bereits beim Laden fuer Titel und Spalten.
-- GetLocale() ist zu diesem Zeitpunkt verfuegbar. Der zweite Aufruf bei
-- PLAYER_LOGIN in Core\Events.lua ist dann nur noch eine Sicherung.
GA.Core.Locale:Apply()
