--[[----------------------------------------------------------------------------
    deDE — ueberschreibt enUS. Vollstaendig, weil Deutsch die Erstsprache ist.
------------------------------------------------------------------------------]]

local _, GA = ...

GA.Core.Locale:Register("deDE", {
    NAV_DASHBOARD    = "Dashboard",
    NAV_ARMORY       = "Armory",
    NAV_CHARACTERS   = "Charaktere",
    NAV_LOOTCOUNCIL  = "LootCouncil",
    NAV_LOOTHISTORY  = "Historie",
    NAV_WISHLIST     = "Wunschliste",
    NAV_GEAR         = "Gear-Tracking",
    NAV_ARMORY_LONG  = "Gilden-Armory",
    DASH_CHANGES     = "Letzte Aenderungen",
    DASH_ONLINE      = "Gilde online",
    DASH_NO_CHANGES  = "Noch keine Aenderungen erfasst.",
    DASH_SNAPSHOT_ROW = "Ausruestungsstand erfasst, Itemlevel %s",
    DASH_NOBODY_ONLINE = "Niemand online",
    ARMORY_CHARACTERS = "Charaktere",
    ARMORY_SEARCH    = "Name suchen",
    SET_NATIVE       = "Fenstervorlagen",
    NAV_ANALYTICS    = "Statistik",
    NAV_SETTINGS     = "Einstellungen",

    BTN_CLOSE        = "Schliessen",
    BTN_REFRESH      = "Aktualisieren",
    BTN_EXPORT       = "Exportieren",
    BTN_IMPORT       = "Importieren",
    BTN_COPY_HINT    = "Strg+A, dann Strg+C",
    UNKNOWN          = "unbekannt",
    NEVER            = "nie",
    JUST_NOW         = "gerade eben",
    AGO_MINUTES      = "vor %d min",
    AGO_HOURS        = "vor %d Std.",
    AGO_DAYS         = "vor %d Tagen",
    PHASE_LABEL      = "Phase %d",

    DASH_MY_CHARACTER = "Mein Charakter",
    DASH_GUILD        = "Gilde",
    DASH_LOOT_STATE   = "Loot",
    DASH_ITEMLEVEL    = "Itemlevel",
    DASH_EQUIPPED     = "%d von %d Plaetzen belegt",
    DASH_MEMBERS      = "%d Mitglieder, %d online",
    DASH_NOT_IN_GUILD = "Nicht in einer Gilde",
    DASH_LOOT_METHOD  = "Lootmethode",
    DASH_LOOT_MASTER  = "Du bist Pluendermeister",
    DASH_LOOT_NOTMASTER = "Pluendermeister ist nicht aktiv",
    DASH_COMPUTED     = "aus den angelegten Gegenstaenden berechnet",

    ARMORY_SLOT       = "Platz",
    ARMORY_ITEM       = "Gegenstand",
    ARMORY_ILVL       = "Ilvl",
    ARMORY_EMPTY      = "leer",
    ARMORY_SNAPSHOT   = "Stand: %s",
    ARMORY_NO_DATA    = "Fuer diesen Charakter liegen noch keine Ausruestungsdaten vor.",
    ARMORY_OWN_HINT   = "Deine eigene Ausruestung wird bei jeder Aenderung automatisch erfasst.",
    ARMORY_STALE      = "Letzte Aktualisierung %s — das sind KEINE Live-Daten.",

    ROLE_ADMIN        = "Administrator",
    ROLE_LOOTMASTER   = "Lootmeister",
    ROLE_COUNCIL      = "Council",
    ROLE_MEMBER       = "Mitglied",

    SET_WINDOW        = "Fenster",
    SET_SCALE         = "Skalierung: %.2f",
    SET_DEBUG         = "Debug umschalten",
    SET_CLIENT        = "Dieser Client",
    SET_DATA          = "Daten",
    SET_PUBLISH       = "Meine Charaktere mit der Gilde teilen",
    SET_PUBLISH_HINT  = "Hinaus gehen Ausruestung, Itemlevel, Klasse und Stufe — und die bestaetigten Vergaben. NICHT hinaus gehen Notizen, Spitznamen und dein Aenderungsjournal. Erzwingen kann das Addon nichts: Wer nicht teilt, erscheint in der Versionsuebersicht als ohne Antwort.",

    -- Ergaenzt 19.09.2026: Dashboard/Armory-Texte, Inspect, Quellen
    LEVEL_FMT               = "Stufe %s",
    LOOT_NO_GROUP           = "Nicht in einer Gruppe",
    LOOT_NO_GROUP_HINT      = "Die Lootmethode gilt erst in Gruppe oder Schlachtzug.",
    LOOT_FREEFORALL         = "Jeder gegen jeden",
    LOOT_ROUNDROBIN         = "Reihum",
    LOOT_MASTER             = "Pluendermeister",
    LOOT_GROUP              = "Gruppenwurf",
    LOOT_NBG                = "Bedarf vor Gier",
    LOOT_PERSONAL           = "Persoenliche Beute",
    CHANGE_EQUIPPED         = "%s: %s angelegt",
    CHANGE_UNEQUIPPED       = "%s: %s abgelegt",
    ITEM_FALLBACK           = "Gegenstand %s",
    ARMORY_LOADOUT_CAPTURED = "Talent-Loadout erfasst",
    ARMORY_SNAPSHOT_COUNT   = "%d Ausruestungsstaende seit %s",
    ARMORY_OWN              = "Dein Charakter",
    ARMORY_GUILD_MEMBER     = "Gildenmitglied",
    COL_NAME                = "Name",
    COL_CLASS               = "Klasse",
    COL_ILVL                = "Ilvl",
    ARMORY_INSPECT_TARGET   = "Ziel inspizieren",
    ARMORY_INSPECT_HINT     = "Spieler anvisieren (bis ~28 m), dann inspizieren.",
    ARMORY_INSPECT_SENT     = "Inspect angefordert: %s",
    ARMORY_INSPECT_DONE     = "Inspect erfasst: %s",
    ARMORY_INSPECT_FAILED   = "Keine Antwort auf den Inspect von %s.",
    INSPECT_REASON_notarget = "Kein Ziel",
    INSPECT_REASON_notplayer= "Ziel ist kein Spieler",
    INSPECT_REASON_self     = "Das bist du selbst",
    INSPECT_REASON_combat   = "Nicht im Kampf",
    INSPECT_REASON_range    = "Ziel ausser Reichweite",
    INSPECT_REASON_api      = "Inspect nicht verfuegbar",
    INSPECT_REASON_busy     = "Ein Inspect laeuft noch",
    SOURCE_self             = "eigener Charakter",
    SOURCE_inspect          = "Inspect",
    SOURCE_sync             = "Gilden-Sync",
    SET_ON                  = "an",
    SET_OFF                 = "aus",
    SET_STATS               = "%d Charaktere · %d Vergaben · %d Journaleintraege · Schema %s",

    -- Charaktere/Spieler und Gear-Verlauf (Phase 3)
    CHAR_PLAYERS            = "Spieler",
    CHAR_PLAYER_DETAIL      = "%d Charaktere  ·  %s",
    CHAR_MEMBERS            = "Charaktere",
    CHAR_MEMBERS_OF         = "Charaktere von %s",
    CHAR_UNASSIGNED         = "Nicht zugeordnet",
    CHAR_MAIN_TAG           = "|cffe5cc80(Main)|r",
    CHAR_SET_MAIN           = "Main setzen",
    CHAR_UNLINK             = "Loesen",
    CHAR_ASSIGN             = "Zuordnen",
    CHAR_NEW_PLAYER         = "Neuer Spieler",
    CHAR_ORIGIN_account     = "bewiesen",
    CHAR_ORIGIN_manual      = "gesetzt",
    CHAR_ORIGIN_claim       = "behauptet",
    CHAR_PROVEN_HINT        = "Derselbe WoW-Account — das ist keine Eintragung, sondern eine Tatsache.",
    CHAR_ALREADY_MAIN       = "Ist bereits der Main.",
    CHAR_PICK_PLAYER        = "Erst links einen Spieler waehlen.",
    CHAR_ROLE_HINT          = "Die Rolle haengt am Main; Twinks erben sie.",
    CHAR_ROLE_CURRENT       = "Aktuelle Rolle.",
    CHAR_NEED_ADMIN         = "Nur ein Administrator kann Rollen aendern.",
    CHAR_CONTEXT            = "%d Spieler  ·  %d nicht zugeordnet",
    GEAR_HISTORY            = "Itemlevel-Verlauf",
    GEAR_NO_HISTORY         = "Noch kein Verlauf — er entsteht, sobald sich die Ausruestung aendert.",
    GEAR_SNAPSHOTS          = "%d Staende",
    GEAR_DISCRETE           = "Je Balken ein erfasster Stand, kein Verlauf dazwischen.",

    -- Loot-Historie und Erfassung (Phase 5)
    COL_WHEN                    = "Wann",
    COL_ITEM                    = "Gegenstand",
    COL_WHO                     = "Empfaenger",
    COL_STATUS                  = "Status",
    COL_PROOF                   = "Bestaetigt durch",
    LOOT_SEARCH                 = "Gegenstand oder Spieler",
    LOOT_ONLY_OPEN              = "Nur offene",
    LOOT_DETAIL                 = "Details",
    LOOT_PICK_ROW               = "Eine Zeile waehlen.",
    LOOT_SUMMARY                = "%d erfasst  ·  %d offen  ·  %d von Hand bestaetigt",
    LOOT_CONTEXT                = "%d Eintraege",
    LOOT_STATUS_DETECTED        = "erkannt",
    LOOT_STATUS_SESSION_OPEN    = "Bewerbung laeuft",
    LOOT_STATUS_AWARDED         = "vergeben",
    LOOT_STATUS_TRANSFER_PENDING= "Uebergabe offen",
    LOOT_STATUS_RECEIVED        = "erhalten",
    LOOT_STATUS_EQUIPPED        = "angelegt",
    LOOT_STATUS_CANCELLED       = "abgebrochen",
    LOOT_STATUS_CORRECTED       = "korrigiert",
    LOOT_PROOF_MASTER_LOOT      = "Pluendermeister",
    LOOT_PROOF_TRADE            = "Handel",
    LOOT_PROOF_LOOT_CHAT        = "Chat-Meldung",
    LOOT_PROOF_MANUAL           = "von Hand",
    LOOT_PROOF_NONE             = "—",
    LOOT_PROOF_STRONG           = "Vom Spiel gemeldet",
    LOOT_PROOF_WEAK             = "Schwacher Beleg",
    LOOT_FROM_ENCOUNTER         = "Kampf: %s",
    LOOT_FROM_CREATURE          = "Von %s",
    LOOT_FROM_NPCID             = "NPC %s",
    LOOT_FROM_UNKNOWN           = "Herkunft unbekannt",
    SET_LOOT                    = "Loot-Erfassung",
    SET_LOOT_THRESHOLD          = "Ab Qualitaet: %s",
    SET_LOOT_SOLO               = "Auch ausserhalb der Gruppe erfassen",
    SET_LOOT_SOLO_HINT          = "Zum Testen allein. Im Betrieb aus, sonst landet jeder Questgegenstand in der Historie.",
    SET_MEASURED                = "Beobachtete Lootmethoden: %s",
    SET_MEASURED_NONE           = "noch keine",
    QUALITY_2                   = "Gruen",
    QUALITY_3                   = "Blau",
    QUALITY_4                   = "Episch",
    LOOT_CORRECTION_OF          = "Korrektur von %s",
    LOOT_CORRECTED_BY           = "Korrigiert durch %s",

    -- Minimap-Knopf
    MINIMAP_LEFT                = "Linksklick: Fenster oeffnen",
    MINIMAP_RIGHT               = "Rechtsklick: Einstellungen",
    MINIMAP_DRAG                = "Ziehen: Knopf verschieben",
    MINIMAP_STATS               = "%d Charaktere  ·  %d Vergaben",
    SET_MINIMAP                 = "Minimap-Knopf anzeigen",

    -- LootCouncil (Phase 4)
    BID_TITLE                   = "Beute-Bewerbung",
    BID_HINT                    = "Waehle je Gegenstand eine Antwort.",
    BID_FROM                    = "Lootmeister: %s",
    BID_ANSWERED                = "Geantwortet: %s",
    BID_FAILED                  = "Bewerbung konnte nicht gesendet werden (%s).",
    COUNCIL_OPEN                = "Session oeffnen",
    COUNCIL_CLOSE               = "Schliessen",
    COUNCIL_ITEMS               = "Gegenstaende",
    COUNCIL_DETECTED_TITLE      = "Erkannte Beute",
    COUNCIL_CANDIDATES          = "Bewerber",
    COUNCIL_CANDIDATES_FOR      = "Bewerber: %s",
    COUNCIL_VOTE                = "Stimme",
    COUNCIL_AWARD               = "Vergeben",
    COUNCIL_BIDS                = "%d Bew.",
    COUNCIL_RUNNING             = "Session laeuft: %d Gegenstaende  ·  Lootmeister %s",
    COUNCIL_DETECTED            = "%d Gegenstaende erkannt — Session noch nicht geoeffnet",
    COUNCIL_IDLE                = "Keine offene Session, nichts erkannt.",
    COUNCIL_FOOTER              = "%d Bewerbungen  ·  %d Stimmen abgegeben",
    COUNCIL_PICK_ITEM           = "Links einen Gegenstand waehlen.",
    COUNCIL_HINT                = "Beute wird beim Oeffnen des Lootfensters erkannt. Dann hier die Session oeffnen.",
    COUNCIL_CONTEXT_OPEN        = "Session laeuft",
    COUNCIL_NEED_LOOTMASTER     = "Nur der Lootmeister kann das.",
    COUNCIL_NEED_COUNCIL        = "Nur das Council kann abstimmen.",
    COUNCIL_ALREADY_OPEN        = "Es laeuft schon eine Session.",
    COUNCIL_NO_SESSION          = "Keine offene Session.",
    COUNCIL_NOTHING_DETECTED    = "Keine erkannte Beute.",
    COUNCIL_NO_CANDIDATE        = "%s steht nicht in der Pluendermeister-Liste — Uebergabe bleibt offen.",
    COUNCIL_ERR_notallowed      = "Dafuer fehlt die Berechtigung.",
    COUNCIL_ERR_alreadyopen     = "Es laeuft schon eine Session.",
    COUNCIL_ERR_noitems         = "Keine Gegenstaende ausgewaehlt.",
    COUNCIL_ERR_noeligible      = "Nichts Erkanntes zum Oeffnen.",
    COUNCIL_ERR_nobid           = "Dieser Spieler hat sich nicht beworben.",
    COUNCIL_ERR_closed          = "Die Session ist geschlossen.",

    -- Wunschliste und Statistik (Phase 6)
    WISH_MINE                 = "Meine Wunschliste",
    WISH_MINE_COUNT           = "Meine Wunschliste — %d offen, %d erfuellt",
    WISH_OTHERS               = "Wer will das noch?",
    WISH_OTHERS_FOR           = "Wer will noch: %s",
    WISH_INPUT                = "Wowhead-Link, Itemlink, ID oder Name",
    WISH_DROP_HINT            = "Wowhead-Link einfuegen, Itemlink, Item-ID oder Namen tippen.",
    WISH_NO_ITEM              = "Kein Gegenstand erkannt — Link einfuegen oder Namen tippen.",
    WISH_SEARCH_TITLE         = "Suchtreffer (%d)",
    WISH_SEARCH_EMPTY         = "Nichts gefunden. Das Verzeichnis kennt %d Gegenstaende.",
    WISH_SEARCH_HINT          = "Es enthaelt nur, was dieser Client schon gesehen hat — ein Addon kann Wowhead nicht abfragen. Einen Wowhead-Link einfuegen geht immer.",
    WISH_SEARCH_STATUS        = "Suche im Verzeichnis dieses Clients (%d Gegenstaende). Treffer anklicken.",
    SET_ITEMINDEX             = "Itemverzeichnis: %d Gegenstaende",
    SET_SYNC                  = "Abgleich: %d andere Clients gesehen, %d Widersprueche",
    EXPORT_TITLE              = "Export fuer die Webapp",
    EXPORT_DONE               = "Export aufgebaut: %d Charaktere, %d Vergaben, %d KB.",
    EXPORT_HINT               = "In die Datei kommt er beim Ausloggen oder /reload — ein Addon kann nicht selbst ins Netz.",
    SET_EXPORT                = "Export: %d KB, Stand %s",
    SET_EXPORT_NONE           = "Export: noch keiner aufgebaut",
    ANNOUNCE_AWARD            = "%s an %s",
    ANNOUNCE_REASON           = " (%s)",
    ANNOUNCE_SOURCE           = " — %s",
    ANNOUNCE_LIMIT            = "Ankuendigungen gestoppt: %d in dieser Sitzung ist die Grenze.",
    SET_ANNOUNCE              = "Bestaetigte Vergaben im Gildenchat ankuendigen",
    SET_ANNOUNCE_HINT         = "Nur bestaetigte Uebergaben, nur vom Lootmeister, hoechstens eine je 3 Sekunden. Hat die Gilde eine Discord-Bruecke am Gildenchat, landet es auch dort.",
    SET_COMBATLOG      = "Combat Log im Raid einschalten",
    SET_COMBATLOG_HINT = "Schreibt WoWCombatLog.txt, solange du in einer Schlachtzugsinstanz bist — mehrere Megabyte je Abend, mit den Namen aller Anwesenden, auch ausserhalb der Gilde. Das Addon kann die Datei nicht lesen; sie ist fuer das Begleitprogramm und die Webseite. Standard aus.",
    COMBATLOG_UNAVAILABLE = "Dieser Client laesst ein Addon die Aufzeichnung nicht starten. Vor dem Raid selbst /combatlog tippen.",
    COMBATLOG_FAILED   = "Die Aufzeichnung liess sich nicht starten — der Aufruf lief durch, geaendert hat sich nichts.",
    SET_COLLECTOR             = "Sammlerbetrieb: stuendlich neu laden",
    SET_COLLECTOR_HINT        = "Der Client schreibt die Datei fuer die Webapp NUR beim Ausloggen und bei /reload. Diese Einstellung laedt alle %d Minuten neu — nie im Kampf, nie bei laufender Lootsession. Nur fuer einen Client gedacht, der dafuer parkt.",
    EXPORT_RELOAD_SOON        = "Guild Armory laedt in %d Sekunden neu (Sammlerbetrieb).",

    IMPORT_TITLE              = "Sicherung einlesen",
    IMPORT_HINT               = "Exportblock hier einfuegen. Der Import fuegt hinzu und ueberschreibt nichts: Selbst gemessene Ausruestung bleibt, widersprechende Vergaben kommen ins Journal.",
    IMPORT_FROM               = "Aus %s, exportiert von %s (%s)",
    IMPORT_CHARS              = "Charaktere: %d neu, %d aktualisiert, %d unveraendert",
    IMPORT_AWARDS             = "Vergaben: %d neu, %d schon bekannt",
    IMPORT_CONFLICTS          = "%d Widersprueche — sie kommen ins Journal, nichts wird ueberschrieben",
    IMPORT_REST               = "Wunschlisten: %d  ·  Spielerprofile: %d  ·  Gegenstaende: %d",
    IMPORT_CONFIRM            = "Zum Uebernehmen noch einmal: /ga import",
    IMPORT_DONE               = "Import fertig: %d Charaktere, %d Vergaben, %d Widersprueche.",
    IMPORT_ERR_empty          = "Nichts eingefuegt.",
    IMPORT_ERR_badjson        = "Das ist kein gueltiger Exportblock.",
    IMPORT_ERR_badformat      = "Fremdes Format — das stammt nicht von Guild Armory.",
    IMPORT_ERR_newer          = "Die Sicherung stammt aus einer neueren Fassung. Addon aktualisieren.",
    IMPORT_ERR_noexport       = "In dieser Datenbank liegt kein Exportblock. Erst /ga export.",

    HIST_JOINED               = "beigetreten",
    HIST_LEFT                 = "nicht mehr im Roster",
    HIST_PROMOTED             = "befoerdert",
    HIST_DEMOTED              = "herabgestuft",
    HIST_KNOWN_SINCE          = "bekannt seit %s",
    HIST_JOINED_SINCE         = "beigetreten %s",
    HIST_FROM_RANK            = "von %s",

    TIP_WISHED                = "Auf der Wunschliste:",
    TIP_AND_MORE              = "und %d weitere",
    TIP_LAST_AWARD            = "Zuletzt vergeben an %s (%s)",
    TIP_ILVL                  = "Itemlevel %s  ·  %s, %s",
    TIP_LAST_LOOT             = "Zuletzt erhalten: %s (%s)",
    SET_TOOLTIPS              = "Tooltips ergaenzen",
    SET_TOOLTIPS_HINT         = "Wunschlisten-Treffer am Gegenstand, Itemlevel und letzte Vergabe am Spieler. Fremde Staende stehen immer mit Quelle und Alter dabei.",
    NOTE_NICKNAME             = "Spitzname",
    NOTE_NOTE                 = "Notiz",
    NOTE_HINT                 = "Bleibt auf diesem Client. Notizen ueber Mitspieler wandern nicht ungefragt durch die Gilde.",
    WISH_REMOVE               = "Entfernen",
    WISH_FULFILLED            = "erhalten %s",
    WISH_ALREADY_GOT          = "hat ihn schon",
    WISH_NOBODY_ELSE          = "Sonst niemand.",
    WISH_PICK                 = "Links einen Eintrag waehlen.",
    WISH_CONTEXT              = "%d offene Wuensche",
    WISH_ERR_noitem           = "Kein Gegenstand erkannt.",
    WISH_ERR_nocharacter      = "Kein Charakter.",
    WISH_ERR_unknownpriority  = "Unbekannte Prioritaet.",
    ANA_BY_PLAYER             = "Je Spieler",
    ANA_BY_CHARACTER          = "Je Charakter",
    ANA_BY_SOURCE             = "Je Herkunft",
    ANA_BY_RESPONSE           = "Je Antwort",
    ANA_BY_QUALITY            = "Je Qualitaet",
    ANA_RANGE_ALL             = "Gesamt",
    ANA_RANGE_7               = "7 Tage",
    ANA_RANGE_30              = "30 Tage",
    ANA_RANGE_90              = "90 Tage",
    ANA_TABLE                 = "Auswertung",
    ANA_TIMELINE              = "Verlauf",
    ANA_ACTIVE                = "Bereits ausgewaehlt.",
    ANA_DELIVERED             = "bestaetigt erhalten",
    ANA_UNKNOWN               = "Herkunft unbekannt",
    ANA_NO_DATA               = "Noch keine bestaetigten Vergaben.",
    ANA_PENDING               = "%d offen",
    ANA_MANUAL                = "%d von Hand",
    ANA_CLAIMED               = "Zuordnung behauptet",
    ANA_UNLINKED              = "ohne Profil",
    ANA_SUM_PENDING           = "%d Zuschlaege ohne bestaetigte Uebergabe",
    ANA_SUM_STRONG            = "%d vom Spiel gemeldet",
    ANA_SUM_CHAT              = "%d nur per Chat-Meldung",
    ANA_SUM_MANUAL            = "%d nur von Hand bestaetigt",
    ANA_SUM_UNKNOWN           = "%d ohne belegte Herkunft",
    ANA_SUM_SINCE             = "aelteste %s",
    ANA_TIMELINE_HINT         = "Ein Balken je Tag mit bestaetigter Uebergabe. Tage ohne Vergabe fehlen — die Reihe zeigt Ereignisse, keine Messreihe.",
    ANA_CONTEXT               = "%d erhalten  ·  %d offen",

    COUNCIL_ON_WISHLIST       = "Wunschliste: %s",
    COUNCIL_WISH_DONE         = "(schon erhalten)",

    SET_TRUSTED               = "Das ist meine eigene Sicherung",
    SET_TRUSTED_HINT          = "Nur dann bleiben bewiesene Main/Twink-Zuordnungen bewiesen. Aus einer fremden Datei waren sie der Beweis des Exporteurs, nicht deiner — sie werden dann zu \"behauptet\".",

    TODO_TITLE        = "Noch nicht gebaut",
    TODO_LOOTCOUNCIL  = "Lootsessions, Bewerbungen, Council-Abstimmung und Lootmeister-Ansicht.",
    TODO_LOOTHISTORY  = "Jede bestaetigte Vergabe mit Status, Empfaenger und Council-Entscheidung.",
    TODO_WISHLIST     = "Wunschlisten je Charakter und je Spieler, abgeglichen mit Vergaben.",
    TODO_GEAR         = "Ausruestungsstaende ueber die Zeit, Itemlevel-Kurve, Charaktervergleich.",
    TODO_ANALYTICS    = "Loot je Spieler, Charakter, Raid, Boss, Qualitaet und Zeitraum.",

    -- Council-Rotation
    ROTATION_TITLE            = "Council-Rotation",
    ROTATION_ANNOUNCE         = "Council-Rotation: %s sitzen heute mit im Council (%d h).",
    ROTATION_WHISPER          = "Du sitzt fuer die naechsten %d Stunden mit im Loot-Council. Du kannst bei Vergaben abstimmen — /ga council oeffnet die Ansicht.",
    ROTATION_ROTATE           = "Rotieren",
    ROTATION_CLEAR            = "Sitze beenden",
    ROTATION_SEATS            = "Sitze je Rotation",
    ROTATION_HOURS            = "Dauer in Stunden",
    ROTATION_ENABLED          = "Council-Rotation verwenden",
    ROTATION_ANNOUNCE_OPT     = "Rotation ankuendigen und anfluestern",
    ROTATION_ACTIVE           = "Laufende Sitze",
    ROTATION_NONE             = "Kein Sitz auf Zeit vergeben.",
    ROTATION_CYCLE            = "Zyklus: %d von %d",
    ROTATION_CYCLED           = "Neuer Zyklus begonnen",
    ROTATION_EXPIRES          = "laeuft ab %s",
    ROTATION_TEMPORARY        = "auf Zeit",
    ROTATION_ERR_NOTALLOWED   = "Nur der Lootmeister kann rotieren.",
    ROTATION_ERR_NOGROUP      = "Dafuer braucht es eine Gruppe.",
    ROTATION_ERR_NOPOOL       = "Niemand im Schlachtzug kommt in Frage.",
    ROTATION_ERR_NOSEATS      = "Mindestens ein Sitz.",
    ROTATION_DONE             = "Rotiert: %s",

    -- Versionsuebersicht
    VERSION_TITLE             = "Versionen",
    VERSION_CHECK             = "Abfragen",
    VERSION_RUNNING           = "Frage laeuft ...",
    VERSION_CURRENT           = "aktuell",
    VERSION_OUTDATED          = "veraltet",
    VERSION_NEWER             = "neuer",
    VERSION_UNKNOWN           = "Fassung unlesbar",
    VERSION_SILENT            = "keine Antwort",
    VERSION_SILENT_HINT       = "Keine Antwort heisst nicht, dass jemand das Addon nicht hat: offline, ausser Reichweite oder Nachricht verloren sind genauso moeglich.",
    VERSION_SUMMARY           = "%d aktuell · %d veraltet · %d ohne Antwort",
    VERSION_SCOPE_GROUP       = "Gruppe",
    VERSION_SCOPE_GUILD       = "Gilde",

    -- Offene Uebergaben
    HANDOVER_TITLE            = "Offene Uebergaben",
    HANDOVER_REMIND           = "%d Gegenstaende in deinen Taschen gehoeren anderen: %s",
    HANDOVER_MORE             = " und %d weitere",
    HANDOVER_NONE             = "Nichts offen.",
    HANDOVER_CARRYING         = "In den Taschen",
    HANDOVER_MISSING          = "Nicht in den Taschen",
    HANDOVER_MISSING_HINT     = "Kann in der Bank liegen, angelegt sein oder vom Empfaenger selbst aufgenommen worden sein. Das Addon aendert deshalb nichts von allein.",
    HANDOVER_WAITING          = "wartet seit %s",

    SET_STORAGE      = "Speicher: %s",

    STORAGE_EMPTY    = "Der Client hat keine gespeicherten Daten geliefert — die Datenbank beginnt leer. Auf der Forever-Beta ist das ein bekannter Fehler: Geschrieben wird korrekt, gelesen nicht. Alles, was du heute eintraegst, ist nach dem naechsten Anmelden weg.",

    -- Wuerfeln
    ROLL_TITLE                = "Wuerfeln",
    ROLL_ANNOUNCE             = "Wuerfeln auf %s — /roll %d-%d, %d Sekunden.",
    ROLL_OPEN                 = "Wurf oeffnen",
    ROLL_CLOSE                = "Beenden",
    ROLL_RUNNING              = "Wurfrunde laeuft: %s (%d-%d)",
    ROLL_IDLE                 = "Keine Wurfrunde offen.",
    ROLL_COUNT                = "%d Wuerfe, %d fehlen noch",
    ROLL_WINNER               = "Hoechster Wurf: %s mit %d",
    ROLL_TIE                  = "Gleichstand bei %d — %s",
    ROLL_TIE_HINT             = "Das Addon waehlt hier niemanden aus. Wie es weitergeht, entscheidet der Raid.",
    ROLL_INVALID_RANGE        = "falsche Spanne",
    ROLL_INVALID_SECOND       = "Zweitwurf",
    ROLL_NOBODY               = "Niemand hat gewuerfelt.",
    ROLL_ERR_RUNNING          = "Es laeuft schon eine Wurfrunde.",
    ROLL_ERR_NOGROUP          = "Dafuer braucht es eine Gruppe.",
    ROLL_ERR_RANGE            = "Die Spanne ergibt keinen Sinn.",

    -- Reservierungen und Plus-Eins
    SOFTRES_TITLE             = "Reservierungen",
    SOFTRES_OPEN              = "Runde oeffnen",
    SOFTRES_CLOSE             = "Runde beenden",
    SOFTRES_NONE              = "Keine Reservierungsrunde offen.",
    SOFTRES_STATS             = "%d Reservierungen von %d Spielern, %d umkaempft",
    SOFTRES_DROPPED           = "Reserviert: %s — %s",
    SOFTRES_ORIGIN_LIST       = "eingetragen",
    SOFTRES_ORIGIN_CLAIM      = "selbst angemeldet",
    SOFTRES_CONTESTED         = "Mehrfach reserviert",
    SOFTRES_OVERLIMIT         = "Ueber der Grenze",
    SOFTRES_IMPORTED          = "%d Reservierungen eingelesen, %d uebersprungen",
    SOFTRES_HINT              = "Eine Reservierung gilt fuer diesen Abend, nicht dauerhaft — und das Addon teilt nichts automatisch zu.",
    SOFTRES_ERR_NOROUND       = "Keine Reservierungsrunde offen.",
    SOFTRES_ERR_NOTALLOWED    = "Nur der Lootmeister kann eine Runde oeffnen.",
    PLUSONE_TITLE             = "Plus Eins",
    PLUSONE_ROW               = "%s: %d (%d gerechnet, %d Ausgleich)",
    PLUSONE_MANUAL_HINT       = "%d davon nur von Hand bestaetigt",
    PLUSONE_HINT              = "Gerechnet aus den bestaetigten Vergaben — nicht gefuehrt. Die Zahl kann der Historie nicht widersprechen.",

    COUNCIL_RESERVED = "reserviert (%s)",

    SOFTRES_ACK_ok            = "Reservierung eingetragen.",
    SOFTRES_ACK_noround       = "Es laeuft keine Reservierungsrunde.",
    SOFTRES_ACK_duplicate     = "Hast du schon reserviert.",
    SOFTRES_ACK_overlimit     = "Du liegst ueber der Grenze — eingetragen, aber der Lootmeister sieht es.",
    SOFTRES_ACK_removed       = "Reservierung zurueckgenommen.",
    SOFTRES_ACK_notfound      = "Da war nichts zurueckzunehmen.",
    SOFTRES_CLAIM             = "Fuer heute reservieren",
    SOFTRES_MINE              = "Meine Reservierungen",
    SOFTRES_VS_WISHLIST       = "Wunschliste heisst 'kann ich gebrauchen' und gilt dauerhaft. Eine Reservierung heisst 'das ist heute meins' und gilt nur diesen Abend.",
    SOFTRES_ERR_NOGROUP2      = "Dafuer braucht es eine Gruppe.",

    SET_PUBLISH_ON   = "Ausruestungsdaten werden in der Gilde geteilt.",

    ATLAS_START      = "AtlasLoot wird eingelesen: %d Gegenstaende ...",
    ATLAS_DONE       = "AtlasLoot eingelesen: %d Gegenstaende, %d Namen aufgeloest.",
    ATLAS_STATS      = "AtlasLoot: %d Fundstellen bekannt, %d Namen aufgeloest.",
    ATLAS_MISSING    = "AtlasLootClassic ist nicht installiert — die Suche nutzt nur, was dieser Client selbst gesehen hat.",
    ATLAS_SOURCE     = "Fundort: %s",
    ATLAS_OFFER      = "AtlasLoot gefunden. /ga atlas liest die Fundorte ein und erweitert die Suche.",

    ATLAS_LOAD           = "AtlasLoot laden",
    ATLAS_LOADED         = "AtlasLoot: %d Fundorte",
    ATLAS_RUNNING        = "AtlasLoot wird eingelesen — das dauert ein paar Sekunden.",
    ATLAS_RUNNING_SHORT  = "laedt ...",
    ATLAS_ERR_RUNNING    = "Laeuft schon.",
    ATLAS_ERR_NOTINSTALLED = "AtlasLootClassic ist nicht installiert.",
    ATLAS_ERR_NOITEMDB   = "AtlasLoot ist da, hat aber keine lesbare Datenbank.",
    ATLAS_ERR_NOSTORAGE  = "AtlasLoot ist da, hat aber keine lesbare Datenbank.",
    ATLAS_ERR_EMPTY      = "AtlasLoot hat noch nichts geladen — Datenmodule fehlen oder sind aus.",

    TEST_USAGE       = "/ga test <Gegenstand> legt eine Probevergabe an. /ga test clear raeumt sie weg.",
    TEST_CREATED     = "Probevergabe angelegt: %s (%s). Jetzt /ga council oeffnen und eine Session starten.",
    TEST_CLEARED     = "%d Probevergaben entfernt.",
    TEST_SOURCE      = "Probelauf",
    TEST_MARK        = "PROBE",

    -- Erfolge
    ACH_TITLE          = "Erfolge",
    ACH_UNLOCKED       = "Erfolg: %s (%d Punkte)",
    ACH_FIRST_REPORTED = "Gilden-First gemeldet: %s — gilt als bestaetigt, sobald die Gilde zugestimmt hat.",
    ACH_FIRST_CONTESTED= "Gilden-First strittig: %s — gleicher Zeitstempel, das entscheidet kein Addon.",
    ACH_POINTS         = "%d Punkte aus %d von %d Erfolgen",
    ACH_GRANTED_HINT   = "%d Punkte davon von Hand eingetragen",
    ACH_STATE_reported = "gemeldet",
    ACH_STATE_verified = "bestaetigt",
    ACH_STATE_superseded = "ueberholt",
    ACH_STATE_contested= "strittig",
    ACH_EV_measured    = "gemessen",
    ACH_EV_observed    = "beobachtet",
    ACH_EV_granted     = "eingetragen",
    ACH_SINCE          = "Gezaehlt wird seit %s.",
    ACH_HALL           = "Hall of Fame",

    NAV_ACHIEVEMENTS   = "Erfolge",
    ACH_MODE_OWN       = "Meine Erfolge",
    ACH_MODE_HALL      = "Hall of Fame",
    ACH_MODE_BOARD     = "Rangliste",
    ACH_SEARCH         = "Erfolg oder Name",
    ACH_NOT_MEASURABLE = "noch nicht messbar",
    ACH_HALL_DETAIL    = "%s · %s",
    ACH_BOARD_DETAIL   = "%d Erfolge, davon %d Gilden-Firsts",
    ACH_CLAIMS         = " (%d Anspruechte)",
    ACH_COVERAGE       = "%d von %d Erfolgen werden derzeit gemessen.",

    ACH_UNREACHABLE    = "nicht erreichbar (hoechstens %d)",
    ACH_EMPTY          = "Dazu gibt es hier nichts.",

    -- Einen Erfolg von Hand eintragen. Der einzig moegliche Weg fuer die rund
    -- fuenfundvierzig Erfolge, die ein Addon nie messen kann.
    BTN_CANCEL         = "Abbrechen",
    BTN_APPLY          = "Uebernehmen",
    GRANT_TITLE        = "Erfolg eintragen",
    GRANT_BUTTON       = "Eintragen",
    GRANT_REVOKE       = "Zuruecknehmen",
    GRANT_PLAYER       = "Spieler",
    GRANT_SEARCH       = "Spielername",
    GRANT_REASON       = "Begruendung",
    GRANT_REASON_HINT  = "Pflicht. Was ist passiert, und wer hat es gesehen? Genau das unterscheidet einen Eintrag von einer Messung — und das Datum gehoert auch hierhin, denn der Zeitstempel haelt fest, wann eingetragen wurde, nicht wann es geschah.",
    GRANT_ACCEPT       = "Eintragen",
    GRANT_NEED_PLAYER  = "Links einen Spieler waehlen.",
    GRANT_NEED_REASON  = "Ohne Begruendung geht es nicht.",
    GRANT_NEED_ROW     = "Erst einen Erfolg waehlen.",
    GRANT_ALREADY      = "Schon da (%s) — eintragen wuerde nichts aendern.",
    GRANT_DONE         = "Eingetragen: %s",
    GRANT_REVOKED      = "Zurueckgenommen: %s",
    GRANT_ERR_UNKNOWN  = "Diesen Erfolg gibt es nicht.",
    GRANT_ERR_NOPLAYER = "Diesen Spieler gibt es nicht.",
    GRANT_ERR_NOTALLOWED = "Das darf nur ein Administrator.",
    GRANT_ERR_NOREASON = "Ohne Begruendung geht es nicht.",
    GRANT_ERR_ALREADY  = "Schon freigeschaltet.",
    GRANT_ERR_NOTGRANTED = "Zuruecknehmen geht nur bei Eintraegen von Hand. Ein gemessener Erfolg stuende bei der naechsten Pruefung wieder da.",
    GRANT_ERR_HASCLAIMS = "Jemand anderes hat diesen Gilden-First aus einer Messung gemeldet. Zuruecknehmen wuerde seine Meldung wegwerfen.",
    GRANT_ERR_CONTESTED = "Strittig — gleicher Zeitstempel wie eine andere Meldung.",
    GRANT_ERR_SUPERSEDED = "Jemand war frueher.",
    ACH_CAT_PROGRESS   = "%d von %d Erfolgen",
    ACH_CAT_UNTOUCHED  = "noch keiner von %d",
    ACH_EXPAND_ALL     = "Alle aufklappen",
    ACH_COLLAPSE_ALL   = "Alle zuklappen",
    PROBE_TITLE        = "Was dieser Client hergibt",
    PROBE_RESULT       = "Sonde: %d brauchbar, %d leer, %d fehlt",
    ICONS_RESULT       = "Symbole geprueft: %d, davon unbekannt: %d",
    ICONS_TITLE        = "Symbole, die dieser Client nicht kennt",

    -- Sprache. Die Befehlswoerter von /ga bleiben englisch: Sie sind Eingabe,
    -- keine Ausgabe, und muessen aus jeder Anleitung tippbar sein.
    SET_LANGUAGE       = "Sprache",
    SET_LANGUAGE_AUTO  = "Automatisch (Clientsprache)",
    SET_LANGUAGE_HINT  = "Grundeinstellung ist Englisch. \"Automatisch\" folgt dem Spielclient, und der wechselt auf Forever nachweislich von selbst.",
    SET_LANGUAGE_ENUS  = "English",
    SET_LANGUAGE_DEDE  = "Deutsch",
    SET_LANGUAGE_RELOAD = "Vollstaendig erst nach einem /reload — was schon im Fenster steht, wurde in der alten Sprache geschrieben.",

    BTN_RELOAD         = "Jetzt neu laden",

    -- /ga
    DASH_TRADABLES     = "Tauschbare Gegenstaende",
    DASH_TRADABLES_NONE = "Noch hat niemand einen seltenen Gegenstand gemeldet, der beim Anlegen bindet.",
    DASH_TRADABLES_ROW = "%s  ·  %s",
    TRADE_OWN          = "Du bietest %d von %d moeglichen an.%s",
    TRADE_NOW_OFFERED  = "Wird jetzt angeboten: %s",
    TRADE_NO_LONGER    = "Wird nicht mehr angeboten: %s",
    TRADE_NOT_CANDIDATE = "Das liegt nicht in deinem Beutel, oder es bindet beim Aufheben.",
    TRADE_TEST         = "Testmodus: %s — jeder Beutelgegenstand gilt als tauschbar.",
    TRADE_TEST_ON      = "Testmodus ist AN. Grauer Trödel wird der Gilde angeboten.",
    TRADE_HOOK_ON      = "Alt-Klick im Beutel ist aktiv (über %s).",
    TRADE_HOOK_OFF     = "Alt-Klick im Beutel geht auf diesem Client NICHT. Stattdessen /ga trade add <Gegenstand>.",
    TRADE_POSTED       = "Deine tauschbaren Gegenstände stehen im Gildenchat.",
    TRADE_POST_FAILED  = "Konnte nicht in den Gildenchat schreiben. Bist du in einer Gilde?",
    DASH_TRADABLES_POST = "In den Gildenchat",
    TIP_TRADE_ON       = "Wird der Gilde angeboten",
    TIP_TRADE_OFF      = "Wird nicht angeboten",
    TIP_TRADE_HINT_ON  = "Alt-Klick bietet es an",
    TIP_TRADE_HINT_OFF = "Alt-Klick nimmt es zurueck",
    SET_OFFER_NEW      = "Neue Funde automatisch anbieten",
    SET_OFFER_NEW_HINT = "Nur selten und besser. Grüne Stücke kannst du von Hand anbieten, automatisch laufen sie nie mit — ein Beutel voll Questbelohnungen würde sonst das eine blaue Teil in der Liste begraben. Standard aus: Was du für einen Twink aufhebst, soll nicht ungefragt beworben werden.",
    TRADE_NONE_OWN     = "Nichts Tauschbares im Beutel.",
    TRADE_UNSURE       = "dieser Client kann nicht sagen, ob sie schon gebunden sind",
    TRADE_ANNOUNCE     = "Zu vergeben: %s",
    SLASH_COMBATLOG    = "Combat Log automatisch: %s   ·   zeichnet gerade auf: %s",
    SLASH_HELP         = "Befehle: /ga · armory · scale · debug · language · status · capture · minimap · sync · export · import · rotate · roll · sr · plusone · atlas · icons · probe · combatlog · trade · test · version · handover · reset",
    SLASH_RESET_WARN   = "Zuruecksetzen von \"%s\" — loescht %d Charaktere und %d Vergaben.",
    SLASH_RESET_CONFIRM = "Zum Bestaetigen noch einmal: /ga reset %s",
    SLASH_RESET_EXPIRED = "Abgelaufen, nichts geaendert.",
    SLASH_RESET_DONE   = "Zurueckgesetzt: %s",
    SLASH_RESET_UNKNOWN = "Unbekannter Bereich: %s (all, ui, characters)",
    SLASH_SCALE_SET    = "Skalierung: %.2f",
    SLASH_SCALE_CURRENT = "Aktuelle Skalierung: %.2f",
    SLASH_STATUS_VERSION = "Version %s, Schema %s, Sprache %s (%s)",
    SLASH_STATUS_STORAGE = "Speicherquelle: %s%s",
    SLASH_STATUS_MIRROR = "(die kontoweite Datei kam nicht an — Spiegel in der Charakterdatei)",
    SLASH_STATUS_COUNTS = "%d Charaktere, %d Vergaben, %d Sessions, %d Journaleintraege",
    SLASH_STATUS_TEMPLATES = "Fenstervorlagen: %s",
    SLASH_CAPTURED     = "Ausruestung erfasst.",
    SLASH_SOURCE_COMMAND = "Befehl",
    SLASH_MINIMAP      = "Minimap-Knopf: %s",
    SLASH_ON           = "an",
    SLASH_OFF          = "aus",
    SLASH_SYNC         = "Abgleich: %d Clients bekannt, %d Widersprueche%s",
    SLASH_SYNC_NOTSENT = " — nichts gesendet (%s)",
    SLASH_SYNC_SHARING_OFF = "Freigabe aus",
    SLASH_SYNC_REJECTED = "Verworfen: %d von ausserhalb der Gilde, %d bei unbekanntem Roster",
    SLASH_SYNC_PEER    = "  %s  Addon %s, Protokoll %s",
    SLASH_ROTATE_CLEARED = "%d Sitze beendet.",
    SLASH_ROTATE_STATUS = "Sitze auf Zeit: %d · Zyklus %d von %d",
    SLASH_ROTATE_SEAT  = "  %s  noch %d min",
    SLASH_BY_HAND      = "von Hand",
    SLASH_ROLL_CLOSED  = "Wurfrunde beendet.",
    SLASH_SR_CLOSED    = "Runde beendet.",
    SLASH_SR_IMPORT_EXAMPLE = "Anna: Thunderfury, 18348\nBert = 19019",
    SLASH_NO_ITEM      = "Gegenstand nicht erkannt: %s",
    SLASH_NO_PROFILES  = "Keine Spielerprofile.",
    SLASH_ATLAS_ERROR  = "AtlasLoot: %s",
    SLASH_ITEM_FALLBACK = "Gegenstand %d",
    SLASH_HANDOVER_CARRYING = "  %s  %s  → %s (Tasche %d, Platz %d)",
    SLASH_LANGUAGE_NOW = "Sprache: %s (%s)",
    SLASH_LANGUAGE_SET = "Sprache auf %s gestellt.",
    SLASH_LANGUAGE_UNKNOWN = "Unbekannte Sprache: %s (en, de, auto)",

    -- Was dieser Client kann, in Worten statt in Wahrheitswerten.
    CAP_masterLootApi       = "Pluendermeister-API",
    CAP_masterLootApi_GOOD  = "GiveMasterLoot vorhanden — ob 'master' waehlbar ist, zeigt die Gruppe.",
    CAP_masterLootApi_BAD   = "Keine Zuweisung durch das Addon moeglich; Uebergabe per Handel.",
    CAP_tradeApi            = "Handels-API",
    CAP_tradeApi_GOOD       = "Uebergaben per Handel koennen bestaetigt werden.",
    CAP_tradeApi_BAD        = "Handelsbestaetigung nicht verfuegbar — nur manuell.",
    CAP_guildRoster         = "Gildenroster",
    CAP_guildRoster_GOOD    = "Gildenmitglieder werden erfasst.",
    CAP_guildRoster_BAD     = "Kein Zugriff auf das Gildenroster.",
    CAP_inspect             = "Inspect",
    CAP_inspect_GOOD        = "Fremde Ausruestung in Reichweite lesbar.",
    CAP_inspect_BAD         = "Nur die eigene Ausruestung.",
    CAP_itemLevelApi        = "Itemlevel je Item",
    CAP_itemLevelApi_GOOD   = "C_Item.GetDetailedItemLevelInfo — Itemlevel wird selbst berechnet.",
    CAP_itemLevelApi_BAD    = "Rueckfall auf GetItemInfo.",
    CAP_tooltipProcessor    = "Tooltip-Erweiterung",
    CAP_tooltipProcessor_GOOD = "TooltipDataProcessor — Guild-Armory-Zeilen im Item-Tooltip moeglich.",
    CAP_tooltipProcessor_BAD  = "Rueckfall auf HookScript.",
    CAP_chatInfo            = "Addon-Nachrichten",
    CAP_chatInfo_GOOD       = "C_ChatInfo verfuegbar.",
    CAP_chatInfo_BAD        = "Keine Synchronisation moeglich.",
    CAP_multipleSpecs       = "Mehrere Specs je Klasse",
    CAP_multipleSpecs_GOOD  = "Rolle aus der Spec ableitbar.",
    CAP_multipleSpecs_BAD   = "Eine Spec je Klasse (gemessen) — Rolle nicht aus der Spec ableiten.",

    -- Kopfzahlen
    ACH_STAT_POINTS    = "Punkte",
    ACH_STAT_DONE      = "Erfolge",
    ACH_STAT_FIRSTS    = "Gilden-Firsts",
    ACH_STAT_BYHAND    = "%d von Hand",

    -- Tooltip
    ACH_TT_CATEGORY    = "Kategorie: %s",
    ACH_TT_POINTS      = "%d Punkte",
    ACH_TT_UNLOCKED    = "Freigeschaltet %s",
    ACH_TT_CHARACTER   = "Auf %s",
    ACH_TT_PROGRESS    = "Fortschritt: %d von %d",
    ACH_TT_HOLDER      = "Gehalten von %s",

    -- Kategorien
    ACH_CAT_FIRSTS     = "Gilden-Firsts",
    ACH_CAT_LEVEL      = "Stufen",
    ACH_CAT_LOOT       = "Beute",
    ACH_CAT_RAID       = "Schlachtzug",
    ACH_CAT_WIPES      = "Wipes",
    ACH_CAT_ATTENDANCE = "Teilnahme",
    ACH_CAT_MASTER     = "Meisterschaft",
    ACH_CAT_PROFESSION = "Berufe",
    ACH_CAT_ECONOMY    = "Wirtschaft",
    ACH_CAT_PVP        = "PvP",
    ACH_CAT_SOCIAL     = "Gemeinschaft",
    ACH_CAT_COLLECTION = "Sammlung",
    ACH_CAT_SECRET     = "Geheim",
})

-- Sprache JETZT anwenden, nicht erst bei PLAYER_LOGIN: Alle folgenden Dateien
-- (Views, MainFrame) lesen `L.XYZ` bereits beim Laden fuer Titel und Spalten.
-- GetLocale() ist zu diesem Zeitpunkt verfuegbar. Der zweite Aufruf bei
-- PLAYER_LOGIN in Core\Events.lua ist dann nur noch eine Sicherung.
GA.Core.Locale:Apply()
