--[[----------------------------------------------------------------------------
    enUS — Grundlage. Wird IMMER geladen; jede andere Sprache ueberschreibt nur.
    Ein Schluessel, der hier fehlt, erscheint im UI als roher Schluessel.
------------------------------------------------------------------------------]]

local _, GA = ...

GA.Core.Locale:Register("enUS", {
    -- Navigation
    NAV_DASHBOARD    = "Dashboard",
    NAV_ARMORY       = "Armory",
    NAV_CHARACTERS   = "Characters",
    NAV_LOOTCOUNCIL  = "Loot Session",
    NAV_LOOTHISTORY  = "History",
    NAV_WISHLIST     = "Wishlist",
    NAV_GEAR         = "Gear Tracking",
    NAV_ARMORY_LONG  = "Guild Armory",
    DASH_CHANGES     = "Recent Changes",
    DASH_ONLINE      = "Guild Online",
    DASH_NO_CHANGES  = "No changes recorded yet.",
    DASH_SNAPSHOT_ROW = "Equipment captured, item level %s",
    DASH_NOBODY_ONLINE = "Nobody online",
    ARMORY_CHARACTERS = "Characters",
    ARMORY_SEARCH    = "Search name",
    SET_NATIVE       = "Frame templates",
    NAV_ANALYTICS    = "Analytics",
    NAV_SETTINGS     = "Settings",

    -- Allgemein
    BTN_CLOSE        = "Close",
    BTN_REFRESH      = "Refresh",
    BTN_EXPORT       = "Export",
    BTN_IMPORT       = "Import",
    BTN_COPY_HINT    = "Ctrl+A, then Ctrl+C",
    UNKNOWN          = "unknown",
    NEVER            = "never",
    JUST_NOW         = "just now",
    AGO_MINUTES      = "%d min ago",
    AGO_HOURS        = "%d h ago",
    AGO_DAYS         = "%d days ago",
    PHASE_LABEL      = "Phase %d",

    -- Dashboard
    DASH_MY_CHARACTER = "My character",
    DASH_GUILD        = "Guild",
    DASH_LOOT_STATE   = "Loot",
    DASH_ITEMLEVEL    = "Item level",
    DASH_EQUIPPED     = "%d of %d slots equipped",
    DASH_MEMBERS      = "%d members, %d online",
    DASH_NOT_IN_GUILD = "Not in a guild",
    DASH_LOOT_METHOD  = "Loot method",
    DASH_LOOT_MASTER  = "You are the master looter",
    DASH_LOOT_NOTMASTER = "Master loot is not active",
    DASH_COMPUTED     = "computed from equipped items",

    -- Armory
    ARMORY_SLOT       = "Slot",
    ARMORY_ITEM       = "Item",
    ARMORY_ILVL       = "ilvl",
    ARMORY_EMPTY      = "empty",
    ARMORY_SNAPSHOT   = "Snapshot: %s",
    ARMORY_NO_DATA    = "No equipment data for this character yet.",
    ARMORY_OWN_HINT   = "Your own equipment is recorded automatically on every change.",
    ARMORY_STALE      = "Last update %s — this is NOT live data.",

    -- Rollen
    ROLE_ADMIN        = "Administrator",
    ROLE_LOOTMASTER   = "Loot Master",
    ROLE_COUNCIL      = "Council",
    ROLE_MEMBER       = "Member",

    -- Einstellungen
    SET_WINDOW        = "Window",
    SET_SCALE         = "Scale: %.2f",
    SET_DEBUG         = "Toggle debug",
    SET_CLIENT        = "This client",
    SET_DATA          = "Data",
    SET_PUBLISH       = "Share my characters with the guild",
    SET_PUBLISH_HINT  = "What leaves: gear, item level, class and level — plus confirmed awards. What does not: notes, nicknames and your change journal. The addon cannot enforce it: whoever does not share shows up in the version overview as no reply.",

    -- Platzhalter fuer spaetere Phasen
    -- Ergaenzt 19.09.2026: Dashboard/Armory-Texte, Inspect, Quellen
    LEVEL_FMT               = "Level %s",
    LOOT_NO_GROUP           = "Not in a group",
    LOOT_NO_GROUP_HINT      = "The loot method only applies in a party or raid.",
    LOOT_FREEFORALL         = "Free for all",
    LOOT_ROUNDROBIN         = "Round robin",
    LOOT_MASTER             = "Master looter",
    LOOT_GROUP              = "Group loot",
    LOOT_NBG                = "Need before greed",
    LOOT_PERSONAL           = "Personal loot",
    CHANGE_EQUIPPED         = "%s: %s equipped",
    CHANGE_UNEQUIPPED       = "%s: %s unequipped",
    ITEM_FALLBACK           = "Item %s",
    ARMORY_LOADOUT_CAPTURED = "Talent loadout captured",
    ARMORY_SNAPSHOT_COUNT   = "%d equipment snapshots since %s",
    ARMORY_OWN              = "Your character",
    ARMORY_GUILD_MEMBER     = "Guild member",
    COL_NAME                = "Name",
    COL_CLASS               = "Class",
    COL_ILVL                = "Ilvl",
    ARMORY_INSPECT_TARGET   = "Inspect target",
    ARMORY_INSPECT_HINT     = "Target a player (within ~28 yd), then inspect.",
    ARMORY_INSPECT_SENT     = "Inspect requested: %s",
    ARMORY_INSPECT_DONE     = "Inspect captured: %s",
    ARMORY_INSPECT_FAILED   = "No reply to the inspect of %s.",
    INSPECT_REASON_notarget = "No target",
    INSPECT_REASON_notplayer= "Target is not a player",
    INSPECT_REASON_self     = "That is you",
    INSPECT_REASON_combat   = "Not while in combat",
    INSPECT_REASON_range    = "Target out of range",
    INSPECT_REASON_api      = "Inspect not available",
    INSPECT_REASON_busy     = "An inspect is still pending",
    SOURCE_self             = "own character",
    SOURCE_inspect          = "inspect",
    SOURCE_sync             = "guild sync",
    SET_ON                  = "on",
    SET_OFF                 = "off",
    SET_STATS               = "%d characters · %d awards · %d journal entries · schema %s",

    -- Charaktere/Spieler und Gear-Verlauf (Phase 3)
    CHAR_PLAYERS            = "Players",
    CHAR_PLAYER_DETAIL      = "%d characters  ·  %s",
    CHAR_MEMBERS            = "Characters",
    CHAR_MEMBERS_OF         = "Characters of %s",
    CHAR_UNASSIGNED         = "Unassigned",
    CHAR_MAIN_TAG           = "|cffe5cc80(Main)|r",
    CHAR_SET_MAIN           = "Set main",
    CHAR_UNLINK             = "Unlink",
    CHAR_ASSIGN             = "Assign",
    CHAR_NEW_PLAYER         = "New player",
    CHAR_ORIGIN_account     = "proven",
    CHAR_ORIGIN_manual      = "set",
    CHAR_ORIGIN_claim       = "claimed",
    CHAR_PROVEN_HINT        = "Same WoW account — a fact, not an entry.",
    CHAR_ALREADY_MAIN       = "Already the main.",
    CHAR_PICK_PLAYER        = "Pick a player on the left first.",
    CHAR_ROLE_HINT          = "The role belongs to the main; alts inherit it.",
    CHAR_ROLE_CURRENT       = "Current role.",
    CHAR_NEED_ADMIN         = "Only an administrator can change roles.",
    CHAR_CONTEXT            = "%d players  ·  %d unassigned",
    GEAR_HISTORY            = "Item level history",
    GEAR_NO_HISTORY         = "No history yet — it starts as soon as equipment changes.",
    GEAR_SNAPSHOTS          = "%d snapshots",
    GEAR_DISCRETE           = "One bar per captured snapshot, nothing in between.",

    -- Loot-Historie und Erfassung (Phase 5)
    COL_WHEN                    = "When",
    COL_ITEM                    = "Item",
    COL_WHO                     = "Recipient",
    COL_STATUS                  = "Status",
    COL_PROOF                   = "Confirmed by",
    LOOT_SEARCH                 = "Item or player",
    LOOT_ONLY_OPEN              = "Open only",
    LOOT_DETAIL                 = "Details",
    LOOT_PICK_ROW               = "Select a row.",
    LOOT_SUMMARY                = "%d recorded  ·  %d open  ·  %d confirmed by hand",
    LOOT_CONTEXT                = "%d entries",
    LOOT_STATUS_DETECTED        = "detected",
    LOOT_STATUS_SESSION_OPEN    = "bidding open",
    LOOT_STATUS_AWARDED         = "awarded",
    LOOT_STATUS_TRANSFER_PENDING= "transfer pending",
    LOOT_STATUS_RECEIVED        = "received",
    LOOT_STATUS_EQUIPPED        = "equipped",
    LOOT_STATUS_CANCELLED       = "cancelled",
    LOOT_STATUS_CORRECTED       = "corrected",
    LOOT_PROOF_MASTER_LOOT      = "Master loot",
    LOOT_PROOF_TRADE            = "Trade",
    LOOT_PROOF_LOOT_CHAT        = "Chat message",
    LOOT_PROOF_MANUAL           = "by hand",
    LOOT_PROOF_NONE             = "—",
    LOOT_PROOF_STRONG           = "Reported by the game",
    LOOT_PROOF_WEAK             = "Weak evidence",
    LOOT_FROM_ENCOUNTER         = "Encounter: %s",
    LOOT_FROM_CREATURE          = "From %s",
    LOOT_FROM_NPCID             = "NPC %s",
    LOOT_FROM_UNKNOWN           = "Source unknown",
    SET_LOOT                    = "Loot tracking",
    SET_LOOT_THRESHOLD          = "From quality: %s",
    SET_LOOT_SOLO               = "Track outside a group too",
    SET_LOOT_SOLO_HINT          = "For testing alone. Off in normal use, or every quest item lands in the history.",
    SET_MEASURED                = "Observed loot methods: %s",
    SET_MEASURED_NONE           = "none yet",
    QUALITY_2                   = "Uncommon",
    QUALITY_3                   = "Rare",
    QUALITY_4                   = "Epic",
    LOOT_CORRECTION_OF          = "Correction of %s",
    LOOT_CORRECTED_BY           = "Corrected by %s",

    -- Minimap-Knopf
    MINIMAP_LEFT                = "Left click: open the window",
    MINIMAP_RIGHT               = "Right click: settings",
    MINIMAP_DRAG                = "Drag: move the button",
    MINIMAP_STATS               = "%d characters  ·  %d awards",
    SET_MINIMAP                 = "Show minimap button",

    -- LootCouncil (Phase 4)
    BID_TITLE                   = "Loot bid",
    BID_HINT                    = "Pick one answer per item.",
    BID_FROM                    = "Loot master: %s",
    BID_ANSWERED                = "Answered: %s",
    BID_FAILED                  = "Could not send the bid (%s).",
    COUNCIL_OPEN                = "Open session",
    COUNCIL_CLOSE               = "Close",
    COUNCIL_ITEMS               = "Items",
    COUNCIL_DETECTED_TITLE      = "Detected loot",
    COUNCIL_CANDIDATES          = "Candidates",
    COUNCIL_CANDIDATES_FOR      = "Candidates: %s",
    COUNCIL_VOTE                = "Vote",
    COUNCIL_AWARD               = "Award",
    COUNCIL_BIDS                = "%d bids",
    COUNCIL_RUNNING             = "Session running: %d items  ·  loot master %s",
    COUNCIL_DETECTED            = "%d items detected — session not opened yet",
    COUNCIL_IDLE                = "No open session, nothing detected.",
    COUNCIL_FOOTER              = "%d bids  ·  %d votes cast",
    COUNCIL_PICK_ITEM           = "Pick an item on the left.",
    COUNCIL_HINT                = "Loot is detected when the loot window opens. Then open the session here.",
    COUNCIL_CONTEXT_OPEN        = "session running",
    COUNCIL_NEED_LOOTMASTER     = "Only the loot master can do that.",
    COUNCIL_NEED_COUNCIL        = "Only the council can vote.",
    COUNCIL_ALREADY_OPEN        = "A session is already running.",
    COUNCIL_NO_SESSION          = "No open session.",
    COUNCIL_NOTHING_DETECTED    = "No detected loot.",
    COUNCIL_NO_CANDIDATE        = "%s is not in the master loot list — transfer stays open.",
    COUNCIL_ERR_notallowed      = "You lack the permission for that.",
    COUNCIL_ERR_alreadyopen     = "A session is already running.",
    COUNCIL_ERR_noitems         = "No items selected.",
    COUNCIL_ERR_nomaster        = "No master looter: the server hands this loot out itself, so a session would be voting on nothing. Recording for the history carries on.",
    COUNCIL_ERR_noeligible      = "Nothing detected to open.",
    COUNCIL_ERR_nobid           = "That player did not bid.",
    COUNCIL_ERR_closed          = "The session is closed.",
    COUNCIL_ERR_forbidden       = "This item has already been awarded. A later change goes through a correction, not a second award — the old record stays.",
    COUNCIL_ERR_badstate        = "This item is in a state that cannot be awarded.",
    COUNCIL_ERR_unknown         = "That item is not in the database.",
    COUNCIL_ERR_unknownsession  = "That session no longer exists.",
    COUNCIL_ERR_unknownitem     = "That item is not part of this session.",
    COUNCIL_REOPEN_BID          = "Bid window",
    COUNCIL_REOPEN_NONE         = "No open session to bid on.",
    HANDOVER_FILLED             = "Put %d item(s) for %s into the trade window. Nothing is traded until you both confirm.",
    LR_AUTOTRADE                = "Fill the trade window automatically",
    LR_AUTOTRADE_HINT           = "When somebody opens a trade with you, items awarded to that person are placed into the window. It only fills it — you still confirm the trade yourself, and nothing is marked as handed over until the trade goes through.",

    -- Wunschliste und Statistik (Phase 6)
    WISH_MINE                 = "My wishlist",
    WISH_MINE_COUNT           = "My wishlist — %d open, %d fulfilled",
    WISH_OTHERS               = "Who else wants it?",
    WISH_OTHERS_FOR           = "Who else wants: %s",
    WISH_INPUT                = "Wowhead link, item link, ID or name",
    WISH_DROP_HINT            = "Paste a Wowhead link or item link, or type an item ID or name.",
    WISH_NO_ITEM              = "No item recognised — paste a link or type a name.",
    WISH_SEARCH_TITLE         = "Search results (%d)",
    WISH_SEARCH_EMPTY         = "Nothing found. The index knows %d items.",
    WISH_SEARCH_HINT          = "It only holds what this client has already seen — an addon cannot query Wowhead. Pasting a Wowhead link always works.",
    WISH_SEARCH_STATUS        = "Searching this client's index (%d items). Click a result.",
    SET_ITEMINDEX             = "Item index: %d items",
    SET_SYNC                  = "Sync: %d other clients seen, %d conflicts",
    EXPORT_TITLE              = "Export for the web app",
    EXPORT_DONE               = "Export built: %d characters, %d awards, %d KB.",
    EXPORT_HINT               = "It reaches the file on logout or /reload — an addon cannot reach the network itself.",
    SET_EXPORT                = "Export: %d KB, as of %s",
    SET_EXPORT_NONE           = "Export: none built yet",
    ANNOUNCE_AWARD            = "%s to %s",
    ANNOUNCE_REASON           = " (%s)",
    ANNOUNCE_SOURCE           = " — %s",
    ANNOUNCE_LIMIT            = "Announcements stopped: %d this session is the limit.",
    SET_ANNOUNCE              = "Announce confirmed awards in guild chat",
    SET_ANNOUNCE_HINT         = "Confirmed transfers only, loot master only, at most one every 3 seconds. If the guild bridges guild chat to Discord, it lands there too.",
    SET_COMBATLOG      = "Turn on combat logging in raids",
    SET_COMBATLOG_HINT = "Writes WoWCombatLog.txt while you are in a raid instance — several megabytes per evening, containing the names of everyone present, including people outside the guild. The addon cannot read the file; it is there for the companion program and the website. Off by default.",
    COMBATLOG_UNAVAILABLE = "This client does not let an addon start combat logging. Type /combatlog yourself before the raid.",
    COMBATLOG_FAILED   = "Combat logging could not be started — the call went through but nothing changed.",
    SET_COLLECTOR             = "Collector mode: reload hourly",
    SET_COLLECTOR_HINT        = "The client writes the web app file ONLY on logout and /reload. This reloads every %d minutes — never in combat, never during a loot session. Meant for one client parked for the job.",
    EXPORT_RELOAD_SOON        = "Guild Armory reloads in %d seconds (collector mode).",

    IMPORT_TITLE              = "Read a backup",
    IMPORT_HINT               = "Paste the export block here. Import adds and overwrites nothing: your own measured gear stays, conflicting awards go to the journal.",
    IMPORT_FROM               = "From %s, exported by %s (%s)",
    IMPORT_CHARS              = "Characters: %d new, %d updated, %d unchanged",
    IMPORT_AWARDS             = "Awards: %d new, %d already known",
    IMPORT_CONFLICTS          = "%d conflicts — they go to the journal, nothing is overwritten",
    IMPORT_REST               = "Wishlists: %d  ·  player profiles: %d  ·  items: %d",
    IMPORT_CONFIRM            = "To apply, run again: /ga import",
    IMPORT_DONE               = "Import done: %d characters, %d awards, %d conflicts.",
    IMPORT_ERR_empty          = "Nothing pasted.",
    IMPORT_ERR_badjson        = "That is not a valid export block.",
    IMPORT_ERR_badformat      = "Foreign format — this did not come from Guild Armory.",
    IMPORT_ERR_newer          = "The backup is from a newer version. Update the addon.",
    IMPORT_ERR_noexport       = "No export block in this database. Run /ga export first.",

    HIST_JOINED               = "joined",
    HIST_LEFT                 = "no longer on the roster",
    HIST_PROMOTED             = "promoted",
    HIST_DEMOTED              = "demoted",
    HIST_KNOWN_SINCE          = "known since %s",
    HIST_JOINED_SINCE         = "joined %s",
    HIST_FROM_RANK            = "from %s",

    TIP_WISHED                = "On the wishlist:",
    TIP_AND_MORE              = "and %d more",
    TIP_LAST_AWARD            = "Last awarded to %s (%s)",
    TIP_ILVL                  = "Item level %s  ·  %s, %s",
    TIP_LAST_LOOT             = "Last received: %s (%s)",
    SET_TOOLTIPS              = "Extend tooltips",
    SET_TOOLTIPS_HINT         = "Wishlist hits on items, item level and last award on players. Foreign data always shows its source and age.",
    NOTE_NICKNAME             = "Nickname",
    NOTE_NOTE                 = "Note",
    NOTE_HINT                 = "Stays on this client. Notes about other players do not travel through the guild unasked.",
    WISH_REMOVE               = "Remove",
    WISH_FULFILLED            = "received %s",
    WISH_ALREADY_GOT          = "already has it",
    WISH_NOBODY_ELSE          = "Nobody else.",
    WISH_PICK                 = "Select an entry on the left.",
    WISH_CONTEXT              = "%d open wishes",
    WISH_ERR_noitem           = "No item recognised.",
    WISH_ERR_nocharacter      = "No character.",
    WISH_ERR_unknownpriority  = "Unknown priority.",
    ANA_BY_PLAYER             = "By player",
    ANA_BY_CHARACTER          = "By character",
    ANA_BY_SOURCE             = "By source",
    ANA_BY_RESPONSE           = "By response",
    ANA_BY_QUALITY            = "By quality",
    ANA_RANGE_ALL             = "All time",
    ANA_RANGE_7               = "7 days",
    ANA_RANGE_30              = "30 days",
    ANA_RANGE_90              = "90 days",
    ANA_TABLE                 = "Breakdown",
    ANA_TIMELINE              = "Over time",
    ANA_ACTIVE                = "Already selected.",
    ANA_DELIVERED             = "confirmed received",
    ANA_UNKNOWN               = "source unknown",
    ANA_NO_DATA               = "No confirmed awards yet.",
    ANA_PENDING               = "%d open",
    ANA_MANUAL                = "%d by hand",
    ANA_CLAIMED               = "link claimed",
    ANA_UNLINKED              = "no profile",
    ANA_SUM_PENDING           = "%d awards without confirmed transfer",
    ANA_SUM_STRONG            = "%d reported by the game",
    ANA_SUM_CHAT              = "%d from chat messages only",
    ANA_SUM_MANUAL            = "%d confirmed by hand only",
    ANA_SUM_UNKNOWN           = "%d without a proven source",
    ANA_SUM_SINCE             = "oldest %s",
    ANA_TIMELINE_HINT         = "One bar per day with a confirmed transfer. Days without awards are absent — this shows events, not a measurement series.",
    ANA_CONTEXT               = "%d received  ·  %d open",

    COUNCIL_ON_WISHLIST       = "Wishlist: %s",
    COUNCIL_WISH_DONE         = "(already received)",

    SET_TRUSTED               = "This is my own backup",
    SET_TRUSTED_HINT          = "Only then do proven main/alt links stay proven. From a foreign file they were the exporter's proof, not yours — they become \"claimed\".",

    TODO_TITLE        = "Not built yet",
    TODO_LOOTCOUNCIL  = "Loot sessions, applications, council votes and the loot master view.",
    TODO_LOOTHISTORY  = "Every confirmed award with status, recipient and council decision.",
    TODO_WISHLIST     = "Per-character and per-player wishlists, matched against awards.",
    TODO_GEAR         = "Equipment snapshots over time, item level curve, per-character comparison.",
    TODO_ANALYTICS    = "Loot per player, character, raid, boss, quality and period.",

    -- Council rotation
    ROTATION_TITLE            = "Council rotation",
    ROTATION_ANNOUNCE         = "Council rotation: %s join the council tonight (%d h).",
    ROTATION_WHISPER          = "You have a loot council seat for the next %d hours. You can vote on awards — /ga council opens the view.",
    ROTATION_ROTATE           = "Rotate",
    ROTATION_CLEAR            = "End seats",
    ROTATION_SEATS            = "Seats per rotation",
    ROTATION_HOURS            = "Duration in hours",
    ROTATION_ENABLED          = "Use council rotation",
    ROTATION_ANNOUNCE_OPT     = "Announce rotation and whisper the chosen",
    ROTATION_ACTIVE           = "Active seats",
    ROTATION_NONE             = "No temporary seat assigned.",
    ROTATION_CYCLE            = "Cycle: %d of %d",
    ROTATION_CYCLED           = "New cycle started",
    ROTATION_EXPIRES          = "expires %s",
    ROTATION_TEMPORARY        = "temporary",
    ROTATION_ERR_NOTALLOWED   = "Only the loot master can rotate.",
    ROTATION_ERR_NOGROUP      = "That needs a group.",
    ROTATION_ERR_NOPOOL       = "Nobody in the raid is eligible.",
    ROTATION_ERR_NOSEATS      = "At least one seat.",
    ROTATION_DONE             = "Rotated: %s",

    -- Version overview
    VERSION_TITLE             = "Versions",
    VERSION_CHECK             = "Check",
    VERSION_RUNNING           = "Asking ...",
    VERSION_CURRENT           = "current",
    VERSION_OUTDATED          = "outdated",
    VERSION_NEWER             = "newer",
    VERSION_UNKNOWN           = "version unreadable",
    VERSION_SILENT            = "no reply",
    VERSION_SILENT_HINT       = "No reply does not mean somebody lacks the addon: offline, out of range or a lost message are just as likely.",
    VERSION_SUMMARY           = "%d current · %d outdated · %d without reply",
    VERSION_SCOPE_GROUP       = "Group",
    VERSION_SCOPE_GUILD       = "Guild",

    -- Pending handovers
    HANDOVER_TITLE            = "Pending handovers",
    HANDOVER_REMIND           = "%d items in your bags belong to others: %s",
    HANDOVER_MORE             = " and %d more",
    HANDOVER_NONE             = "Nothing pending.",
    HANDOVER_CARRYING         = "In your bags",
    HANDOVER_MISSING          = "Not in your bags",
    HANDOVER_MISSING_HINT     = "May be in the bank, equipped, or picked up by the recipient. The addon changes nothing on its own.",
    HANDOVER_WAITING          = "waiting for %s",

    SET_STORAGE      = "Storage: %s",

    STORAGE_EMPTY    = "The client delivered no saved data — the database starts empty. On the Forever beta this is a known defect: writing works, reading does not. Anything you enter today is gone after the next login.",

    -- Rolling
    ROLL_TITLE                = "Rolls",
    ROLL_ANNOUNCE             = "Roll for %s — /roll %d-%d, %d seconds.",
    ROLL_OPEN                 = "Open roll",
    ROLL_CLOSE                = "Close",
    ROLL_RUNNING              = "Roll open: %s (%d-%d)",
    ROLL_IDLE                 = "No roll open.",
    ROLL_COUNT                = "%d rolls, %d still missing",
    ROLL_WINNER               = "Highest roll: %s with %d",
    ROLL_TIE                  = "Tie at %d — %s",
    ROLL_TIE_HINT             = "The addon picks nobody here. How to proceed is the raid's call.",
    ROLL_INVALID_RANGE        = "wrong range",
    ROLL_INVALID_SECOND       = "second roll",
    ROLL_NOBODY               = "Nobody rolled.",
    ROLL_ERR_RUNNING          = "A roll is already open.",
    ROLL_ERR_NOGROUP          = "That needs a group.",
    ROLL_ERR_RANGE            = "That range makes no sense.",

    -- Reserves and plus one
    SOFTRES_TITLE             = "Reserves",
    SOFTRES_OPEN              = "Open round",
    SOFTRES_CLOSE             = "Close round",
    SOFTRES_NONE              = "No reserve round open.",
    SOFTRES_STATS             = "%d reserves from %d players, %d contested",
    SOFTRES_DROPPED           = "Reserved: %s — %s",
    SOFTRES_ORIGIN_LIST       = "entered",
    SOFTRES_ORIGIN_CLAIM      = "self-declared",
    SOFTRES_CONTESTED         = "Reserved more than once",
    SOFTRES_OVERLIMIT         = "Over the limit",
    SOFTRES_IMPORTED          = "%d reserves read, %d skipped",
    SOFTRES_HINT              = "A reserve is for tonight, not forever — and the addon assigns nothing on its own.",
    SOFTRES_ERR_NOROUND       = "No reserve round open.",
    SOFTRES_ERR_NOTALLOWED    = "Only the loot master can open a round.",
    PLUSONE_TITLE             = "Plus one",
    PLUSONE_ROW               = "%s: %d (%d counted, %d adjustment)",
    PLUSONE_MANUAL_HINT       = "%d of those confirmed by hand only",
    PLUSONE_HINT              = "Computed from confirmed awards — not kept. The number cannot contradict the history.",

    COUNCIL_RESERVED = "reserved (%s)",

    SOFTRES_ACK_ok            = "Reserve recorded.",
    SOFTRES_ACK_noround       = "No reserve round is running.",
    SOFTRES_ACK_duplicate     = "You already reserved that.",
    SOFTRES_ACK_overlimit     = "You are over the limit — recorded, but the loot master sees it.",
    SOFTRES_ACK_removed       = "Reserve withdrawn.",
    SOFTRES_ACK_notfound      = "There was nothing to withdraw.",
    SOFTRES_CLAIM             = "Reserve for tonight",
    SOFTRES_MINE              = "My reserves",
    SOFTRES_VS_WISHLIST       = "A wishlist says 'I can use this' and lasts. A reserve says 'this is mine tonight' and lasts one evening.",
    SOFTRES_ERR_NOGROUP2      = "That needs a group.",

    SET_PUBLISH_ON   = "Gear data is shared with the guild.",

    ATLAS_START      = "Reading AtlasLoot: %d items ...",
    ATLAS_DONE       = "AtlasLoot read: %d items, %d names resolved.",
    ATLAS_STATS      = "AtlasLoot: %d sources known, %d names resolved.",
    ATLAS_MISSING    = "AtlasLootClassic is not installed — search uses only what this client has seen itself.",
    ATLAS_SOURCE     = "Drops from: %s",
    ATLAS_OFFER      = "AtlasLoot found. /ga atlas reads the sources and widens the search.",

    ATLAS_LOAD           = "Load AtlasLoot",
    ATLAS_LOADED         = "AtlasLoot: %d sources",
    ATLAS_RUNNING        = "Reading AtlasLoot — this takes a few seconds.",
    ATLAS_RUNNING_SHORT  = "loading ...",
    ATLAS_ERR_RUNNING    = "Already running.",
    ATLAS_ERR_NOTINSTALLED = "AtlasLootClassic is not installed.",
    ATLAS_ERR_NOITEMDB   = "AtlasLoot is present but has no readable database.",
    ATLAS_ERR_NOSTORAGE  = "AtlasLoot is present but has no readable database.",
    ATLAS_ERR_EMPTY      = "AtlasLoot has not loaded anything yet — data modules missing or off.",

    TEST_USAGE       = "/ga test <item> creates a rehearsal award. /ga test clear removes them.",
    TEST_CREATED     = "Rehearsal award created: %s (%s). Open /ga council and start a session.",
    TEST_CLEARED     = "%d rehearsal awards removed.",
    TEST_SOURCE      = "Rehearsal",
    TEST_MARK        = "TEST",

    -- Achievements
    ACH_TITLE          = "Achievements",
    ACH_UNLOCKED       = "Achievement: %s (%d points)",
    ACH_FIRST_REPORTED = "Guild first reported: %s — counts as verified once the guild agrees.",
    ACH_FIRST_CONTESTED= "Guild first contested: %s — same timestamp, no addon decides that.",
    ACH_POINTS         = "%d points from %d of %d achievements",
    ACH_GRANTED_HINT   = "%d of those points entered by hand",
    ACH_STATE_reported = "reported",
    ACH_STATE_verified = "verified",
    ACH_STATE_superseded = "superseded",
    ACH_STATE_contested= "contested",
    ACH_EV_measured    = "measured",
    ACH_EV_observed    = "observed",
    ACH_EV_granted     = "entered",
    ACH_SINCE          = "Counting since %s.",
    ACH_HALL           = "Hall of Fame",

    NAV_ACHIEVEMENTS   = "Achievements",
    ACH_MODE_OWN       = "My achievements",
    ACH_MODE_HALL      = "Hall of Fame",
    ACH_MODE_BOARD     = "Leaderboard",
    ACH_SEARCH         = "Achievement or name",
    ACH_NOT_MEASURABLE = "not measurable yet",
    ACH_HALL_DETAIL    = "%s · %s",
    ACH_BOARD_DETAIL   = "%d achievements, %d guild firsts",
    ACH_CLAIMS         = " (%d claims)",
    ACH_COVERAGE       = "%d of %d achievements are currently measured.",

    ACH_UNREACHABLE    = "not reachable (at most %d)",
    ACH_EMPTY          = "Nothing here for that.",

    -- Entering an achievement by hand. The only possible path for the roughly
    -- forty-five achievements an addon can never measure.
    BTN_CANCEL         = "Cancel",
    BTN_APPLY          = "Apply",
    GRANT_TITLE        = "Enter achievement",
    GRANT_BUTTON       = "Enter by hand",
    GRANT_REVOKE       = "Take back",
    GRANT_PLAYER       = "Player",
    GRANT_SEARCH       = "Player name",
    GRANT_REASON       = "Reason",
    GRANT_REASON_HINT  = "Required. What happened, and who saw it? This is what separates an entry from a measurement — and the date belongs here too, because the timestamp records when it was entered, not when it happened.",
    GRANT_ACCEPT       = "Enter",
    GRANT_NEED_PLAYER  = "Pick a player on the left.",
    GRANT_NEED_REASON  = "A reason is required.",
    GRANT_NEED_ROW     = "Pick an achievement first.",
    GRANT_ALREADY      = "Already there (%s) — entering would change nothing.",
    GRANT_DONE         = "Entered: %s",
    GRANT_REVOKED      = "Taken back: %s",
    GRANT_ERR_UNKNOWN  = "No such achievement.",
    GRANT_ERR_NOPLAYER = "No such player.",
    GRANT_ERR_NOTALLOWED = "Only an administrator can do that.",
    GRANT_ERR_NOREASON = "A reason is required.",
    GRANT_ERR_ALREADY  = "Already unlocked.",
    GRANT_ERR_NOTGRANTED = "Only entries made by hand can be taken back. A measured achievement would be back at the next check.",
    GRANT_ERR_HASCLAIMS = "Someone else reported this guild first from a measurement. Taking it back would discard their claim.",
    GRANT_ERR_CONTESTED = "Contested — same timestamp as another claim.",
    GRANT_ERR_SUPERSEDED = "Someone was earlier.",
    ACH_CAT_PROGRESS   = "%d of %d achievements",
    ACH_CAT_UNTOUCHED  = "none of %d yet",
    ACH_EXPAND_ALL     = "Expand all",
    ACH_COLLAPSE_ALL   = "Collapse all",
    PROBE_TITLE        = "What this client provides",
    PROBE_RESULT       = "Probe: %d usable, %d empty, %d missing",
    ICONS_RESULT       = "Icons checked: %d, unknown: %d",
    ICONS_TITLE        = "Icons this client does not have",

    -- Language. The command words of /ga stay English: they are input, not
    -- output, and have to be typeable from any guide.
    SET_LANGUAGE       = "Language",
    SET_LANGUAGE_AUTO  = "Automatic (client language)",
    SET_LANGUAGE_ENUS  = "English",
    SET_LANGUAGE_DEDE  = "Deutsch",
    SET_LANGUAGE_RELOAD = "Takes full effect after a /reload — text already on screen was written in the old language.",
    SET_LANGUAGE_HINT  = "Default is English. \"Automatic\" follows the game client, which on Forever has been seen to change on its own.",
    BTN_RELOAD         = "Reload now",

    -- /ga
    DASH_TRADABLES     = "Tradable Items",
    DASH_TRADABLES_NONE = "Nobody has offered a rare bind-on-equip item yet.",
    DASH_TRADABLES_ROW = "%s  ·  %s",
    TRADE_OWN          = "Offering %d of %d possible item(s).%s",
    TRADE_NOW_OFFERED  = "Now offered to the guild: %s",
    TRADE_NO_LONGER    = "No longer offered: %s",
    TRADE_NOT_CANDIDATE = "That is not in your bags, or it binds on pickup.",
    TRADE_TEST         = "Test mode: %s — every bag item counts as tradable.",
    TRADE_TEST_ON      = "Test mode is ON. Grey junk is being offered to the guild.",
    TRADE_HOOK_ON      = "Alt-click in your bags is active (via %s).",
    TRADE_HOOK_OFF     = "Alt-click in your bags is NOT available on this client. Use /ga trade add <item> instead.",
    TRADE_POSTED       = "Posted your tradable items to guild chat.",
    TRADE_ASK          = "Could I have %s?",
    TRADE_ASK_BUTTON   = "Ask",
    TRADE_ASKED        = "Asked %s about %s.",
    TRADE_ASK_ERR_self = "That is your own offer.",
    TRADE_ASK_ERR_recent = "You already asked about that a moment ago.",
    TRADE_ASK_ERR_noowner = "No owner recorded for that item.",
    TRADE_ASK_ERR_chat = "Could not whisper — is that character still online?",
    SIM_ON             = "Test mode ON. Nothing leaves this client — no chat line, no addon message — until you turn it off.",
    SIM_OFF            = "Test mode off. While it ran it held back %d chat line(s) and %d addon message(s). Made-up records are still here; /ga sim clear removes them.",
    SIM_CLEARED        = "Removed: %d award(s), %d character(s), %d profile(s), %d session(s), %d reservation(s).",
    SIM_ROSTER         = "%d made-up raid member(s) added.",
    SIM_DROPPED        = "%d item(s) dropped.",
    SIM_RESERVED       = "%d soft reserve(s) declared.",
    SIM_SEED           = "Random seed set to %d. The same seed replays the same run.",
    SIM_RAN            = "Ready: %d player(s), %d item(s), %d bid(s), %d vote(s). Nothing is awarded — that part is yours.",
    SIM_AWARDED        = "Awarded %d, %d had nobody bidding.",
    SIM_LOOK           = "Open /ga council and /ga history to see it.",
    SIM_FAILED         = "Could not open a session: %s",
    SIM_STATE          = "Test mode: %s — %d award(s), %d character(s), %d session(s) are made up.",
    SIM_USAGE          = "/ga sim [run] | raid | drop | sr | bid | award | seed <n> | on | off | clear",
    NAV_LOOTRULES      = "Loot rules",
    LR_COUNCIL         = "Council",
    LR_MODE_DKP        = "DKP",
    LR_MODE_DKP_HINT   = "People bid points, the highest bid wins, and only the winner pays. A balance is never a stored number here: it is the sum of every posting, so it cannot contradict the ledger. Points are granted by hand or from attendance — the addon posts nothing on its own, because it cannot tell a missed boss from one that never happened.",
    LR_SUM_DKP_MODE    = "Points decide; only the winner pays.",
    BID_DKP_SEND       = "Bid",
    BID_DKP_SENT       = "%d points bid",
    BID_DKP_INFO       = "you have %d, minimum %d",
    BID_DKP_ERR_toolow = "Below the minimum bid.",
    BID_DKP_ERR_insufficient = "You do not have that many points.",
    BID_DKP_ERR_notanumber = "Whole numbers only.",
    BID_DKP_ERR_notraised = "You can raise a bid, not lower it.",
    BID_DKP_ERR_nocomm = "No connection to the loot master.",
    BID_DKP_ERR_nodkp  = "DKP is not available on this client.",
    DKP_TITLE          = "Points",
    LR_TIMER_WHICH     = "Bidding stays open for %d seconds",
    LR_TIMER_WHICH_OFF = "Bidding stays open until you close it",
    LR_TIMER_OFF       = "No clock",
    LR_TIMER_SECONDS   = "%ds",
    LR_TIMER_HINT      = "When the time is up, no bid can be placed, changed or withdrawn any more — otherwise somebody revises theirs while the awarding is already under way. The loot master's clock decides; the countdown in everyone's bid window only says where they stand. Without a clock you close bidding yourself.",
    BID_TIME_LEFT      = "%ds left",
    BID_TIME_UP        = "bidding closed",
    BID_DKP_ERR_timeup = "The bidding time is up.",
    COUNCIL_ERR_timeup = "The bidding time is up.",
    BID_DKP_STATE      = "you bid %d · %d still free · minimum %d",
    DKP_OUTBID         = "You have been outbid on %s.",
    DKP_OUTBID_SELF    = "Your own earlier bid has been replaced.",
    COUNCIL_DKP        = "%d points",
    COUNCIL_SEALED     = "sealed",
    BID_DKP_CANCEL     = "Withdraw",
    BID_DKP_WITHDRAWN  = "withdrawn",
    BID_DKP_AVAILABLE  = "you can still bid %d, minimum %d",
    LR_OUTBID          = "Whisper somebody when they are outbid",
    LR_OUTBID_HINT     = "The loot master's client whispers the previous highest bidder — without the new amount. Bids stay sealed: whoever knows the top bid simply bids one more, and the auction turns into a race for the last second.",
    DKP_KNOWN_NAMES    = "  known as: %s",
    DKP_NO_CHARACTER_WHY = "  %d character(s) known · you are %s · own id readable: %s",
    DKP_OPEN           = "Points and ledger",
    DKP_LIST_TITLE     = "Standings",
    DKP_LEDGER         = "Ledger",
    DKP_LEDGER_OF      = "%s — %d points  (%d earned, %d spent)",
    DKP_POST_TITLE     = "Post points",
    DKP_POST_HINT      = "Amount and reason. A negative amount deducts. Nothing is posted without a reason — a posting you cannot explain later is worse than none.",
    DKP_POST_ONE       = "To the selected player",
    DKP_POST_RAID      = "To everyone in the raid",
    DKP_POSTED_COUNT   = "%+d posted for %d player(s).",
    DKP_NEED_POINTS    = "Enter an amount.",
    DKP_NEED_REASON    = "Enter a reason.",
    DKP_NO_SELECTION   = "Pick somebody on the left first.",
    DKP_NO_RAID        = "Nobody in the group is known to the addon yet.",
    DKP_LOCKED_role    = "Only the loot master and administrators post points. You can look.",
    DKP_LOCKED_noguid  = "This client will not hand out your own character id, so no role can be assigned to you.",
    DKP_NO_CHARACTER   = "No character called %s is known here. The full name with surname, and the addon has to have seen them — a guild scan or /ga sim raid does that.",
    DKP_NO_ENTRIES     = "No postings for %s yet.",
    DKP_EMPTY          = "The ledger is empty — nobody has points yet. /ga dkp add 20 Harry Ghosthook posts some.",
    DKP_LIST_HEAD      = "Points, %d player(s):",
    DKP_LOG_HEAD       = "%s — %d points:",
    DKP_WORD_EARNED    = "earned",
    DKP_WORD_SPENT     = "spent",
    DKP_USAGE          = "/ga dkp  |  /ga dkp add 20 Harry Ghosthook  |  /ga dkp log Harry Ghosthook   (full name, surname included)",
    DKP_BY_HAND        = "posted by hand",
    DKP_POSTED         = "%+d for %s — now at %d.",
    DKP_BALANCE        = "%d points",
    DKP_EARNED         = "%d earned, %d spent",
    LR_LOCKED_role     = "Only the loot master and administrators change these rules. What counts during a raid are the rules of whoever runs the session — they travel with the announcement.",
    LR_LOCKED_noguid   = "This client will not hand out your own character id, so no role can be assigned to you. See /ga status.",
    LR_SCOPE_WHICH     = "Who takes part: %s",
    LR_SCOPE_GUILD     = "Guild members in the raid",
    LR_SCOPE_RAID      = "Everyone in the raid",
    LR_SCOPE_GUILD_HINT = "A session is announced over the raid or party channel, never to the guild — people who are not in the raid never see it. On top of that, only guild members are accepted, checked on both sides: somebody from outside sees no bid window, and their bids would not arrive either.",
    LR_SCOPE_RAID_HINT = "People from outside the guild can bid too, as long as they really are in your raid. This applies to the SESSION ONLY: characters, wishlists and confirmed awards stay between guild members either way.",
    LR_MODE_WHICH      = "How loot is distributed: %s",
    LR_MODE_COUNCIL    = "Council",
    LR_MODE_SOFTRES    = "Soft reserve",
    LR_MODE_ROLL       = "Roll",
    BID_RESERVED_BY    = "Reserved by %s",
    BID_ROLLED         = "rolled",
    COUNCIL_ROLLED     = "%d / %s  %s",
    BID_ROLLED_VALUE   = "rolled %d of %d",
    LR_QUIETROLLS      = "Keep roll lines out of my chat",
    LR_ROLLSRC_WHICH   = "Who rolls: %s",
    LR_ROLLSRC_MASTER  = "The loot master",
    LR_ROLLSRC_CHAT    = "Everyone with /roll",
    LR_ROLLSRC_MASTER_HINT = "No chat lines at all. A bidder cannot influence their own number — their client does not draw it. The trade: the raid cannot check the number either. With 20 people and 10 items, /roll means 200 lines for everybody, including people without the addon.",
    LR_ROLLSRC_CHAT_HINT = "Everyone rolls with /roll, so the server draws the number and the whole raid reads it — nobody can fake it, not even the loot master. The trade: a full chat. The addon hides the lines it can attribute, but only in the chat of people who have it.",
    LR_QUIETROLLS_HINT = "While a session is open, roll lines that belong to it are hidden from YOUR chat window — the roll still happens on the server and everyone else still sees it. Rolls that have nothing to do with the session stay visible.",
    BID_ROLL_ERR_noroll = "This client cannot roll. Type /roll yourself.",
    BID_ROLL_ERR_pending = "Your previous roll has not arrived yet. One at a time, otherwise the two chat lines cannot be told apart.",
    BID_ROLL_ERR_nocomm = "No connection to the loot master.",
    BID_ROLL_ERR_noname = "Your own name is not available on this client.",
    BID_ROLL_ERR_unknowntier = "Unknown roll range.",
    LR_MODE_COUNCIL_HINT = "People bid, the council votes, the loot master awards.",
    LR_MODE_SOFTRES_HINT = "A reservation decides. Anything nobody reserved is rolled for: 100 main-spec, 50 off-spec, 25 transmog. The loot master awards.",
    LR_MODE_ROLL_HINT  = "Everything is rolled for: 100 main-spec, 50 off-spec, 25 transmog. A low roll in the larger range beats a high one in the smaller — that is the point of the ranges. The loot master awards.",
    LR_SUM_SOFTRES_MODE = "Reservations decide; the rest is rolled for (100/50/25).",
    LR_SUM_ROLL_MODE   = "Everything is rolled for (100/50/25).",
    LR_COUNCIL_ON      = "Use a loot council",
    LR_COUNCIL_HINT    = "On: people bid, the council votes, the loot master awards. Off: people still bid, but nobody votes and the loot master decides alone.",
    LR_VOTE_WHO        = "Who may vote: %s",
    LR_VOTE_COUNCIL    = "Council",
    LR_VOTE_LOOTMASTER = "Loot master only",
    LR_VOTE_ALL        = "Everyone",
    LR_VOTE_HINT       = "Loot master and admin rank above council, so they always vote too. Roles are set per player under Characters.",
    LR_RESPONSES       = "What bidders can answer",
    LR_RESPONSES_HINT  = "Only the ticked answers appear in the bid window. Pass is always there: somebody who does not want the item must be able to say so, or silence looks like no answer yet.",
    LR_RULES           = "Procedure",
    LR_SOFTRES         = "Use soft reserves",
    LR_SOFTRES_HINT    = "A list for one raid night, separate from wishlists. The council sees who reserved what before it votes.",
    LR_PLUSONE         = "Count plus one",
    LR_PLUSONE_HINT    = "How often somebody already received something, computed from the loot history on every read rather than kept as a counter that can drift.",
    LR_ROTATION        = "Rotate council seats",
    LR_ROTATION_HINT   = "Temporary seats for raid members, fairly cycled. A seat expires on the clock and is never written into permanent roles.",
    LR_SUMMARY         = "What applies tonight",
    LR_SUM_COUNCIL     = "%s votes, the loot master awards.",
    LR_SUM_NOCOUNCIL   = "No vote — the loot master decides alone.",
    LR_SUM_SOFTRES     = "Soft reserves count.",
    LR_SUM_PLUSONE     = "Plus one is counted.",
    LR_SUM_ROTATION    = "%d seat(s) rotate among raid members.",
    LR_WARN_ROTATION_NOCOUNCIL = "Seats are rotating, but nobody may vote. The chosen are whispered a seat that does not exist.",
    LR_WARN_ALL_VOTE   = "Everyone in the raid may vote. With 40 people that is a poll, not a council.",
    LR_WARN_NO_RESPONSES = "Only Pass is left. Nobody can bid for anything.",
    SLASH_STATUS_ROLE  = "Your role: %s   (loot master: %s, council: %s)",
    ROLE_NO_GUID       = "This client will not hand out your own GUID, so no role can be assigned to you. Loot master and council checks will refuse. /ga sim works around it for testing.",
    TRADE_POST_FAILED  = "Could not write to guild chat. Are you in a guild?",
    DASH_TRADABLES_POST = "Post to guild",
    TIP_TRADE_ON       = "Offered to the guild",
    TIP_TRADE_OFF      = "Not offered",
    TIP_TRADE_HINT_ON  = "Alt-click to offer it",
    TIP_TRADE_HINT_OFF = "Alt-click to take it back",
    SET_OFFER_NEW      = "Offer new finds automatically",
    SET_OFFER_NEW_HINT = "Rare and better only. Greens can be offered by hand but never run along on their own, or a bag of quest rewards would bury the one blue item in the list. Off by default: something you are keeping for an alt should not be advertised without you saying so.",
    TRADE_NONE_OWN     = "Nothing tradable in your bags.",
    TRADE_UNSURE       = "this client cannot tell whether they are already soulbound",
    TRADE_ANNOUNCE     = "Up for trade: %s",
    SLASH_COMBATLOG    = "Auto combat logging: %s   ·   recording right now: %s",
    SLASH_HELP         = "Commands: /ga · armory · scale · debug · language · status · mem · capture · minimap · sync · export · import · rotate · roll · sr · plusone · atlas · icons · probe · combatlog · trade · camp · craft · craft link · map · test · version · handover · reset",
    SLASH_RESET_WARN   = "Resetting \"%s\" deletes %d characters and %d awards.",
    SLASH_RESET_CONFIRM = "To confirm, repeat: /ga reset %s",
    SLASH_RESET_EXPIRED = "Expired, nothing changed.",
    SLASH_RESET_DONE   = "Reset: %s",
    SLASH_RESET_UNKNOWN = "Unknown scope: %s (all, ui, characters)",
    SLASH_SCALE_SET    = "Scale: %.2f",
    SLASH_SCALE_CURRENT = "Current scale: %.2f",
    SLASH_STATUS_VERSION = "Version %s, schema %s, language %s (%s)",
    SLASH_STATUS_STORAGE = "Storage source: %s%s",
    SLASH_STATUS_MIRROR = "(the account-wide file never arrived — mirror in the character file)",
    SLASH_STATUS_COUNTS = "%d characters, %d awards, %d sessions, %d journal entries",
    SLASH_STATUS_TEMPLATES = "Frame templates: %s",
    SLASH_STATUS_TITLE = "Status — to copy",
    SLASH_MEM_TITLE    = "Memory — what is held and what was only garbage",
    SLASH_MEM_BEFORE   = "Before: addon %s, Lua total %s",
    SLASH_MEM_AFTER    = "After:  addon %s, Lua total %s",
    SLASH_MEM_GARBAGE  = "%s of that was garbage (%.0f %%). What stays held is %s — a rising figure is throughput, not a leak.",
    SLASH_MEM_HELD     = "Hardly anything could be collected. This is REALLY held — the numbers below say by what.",
    SLASH_MEM_NOAPI    = "This client does not hand out the addon memory figure.",
    SLASH_MEM_TABLES   = "Entries in the big tables:",
    SLASH_MEM_ROW      = "  %-20s %6d",
    SLASH_CAPTURED     = "Equipment captured.",
    SLASH_SOURCE_COMMAND = "command",
    SLASH_MINIMAP      = "Minimap button: %s",
    SLASH_ON           = "on",
    SLASH_OFF          = "off",
    SLASH_SYNC         = "Sync: %d clients known, %d conflicts%s",
    SLASH_SYNC_NOTSENT = " — nothing sent (%s)",
    SLASH_SYNC_SHARING_OFF = "sharing off",
    SLASH_SYNC_REJECTED = "Rejected: %d from outside the guild, %d while the roster was unknown",
    SLASH_SYNC_PEER    = "  %s  addon %s, protocol %s",
    SLASH_ROTATE_CLEARED = "%d seats ended.",
    SLASH_ROTATE_STATUS = "Timed seats: %d · cycle %d of %d",
    SLASH_ROTATE_SEAT  = "  %s  %d min left",
    SLASH_BY_HAND      = "by hand",
    SLASH_ROLL_CLOSED  = "Roll round ended.",
    SLASH_SR_CLOSED    = "Round ended.",
    SLASH_SR_IMPORT_EXAMPLE = "Anna: Thunderfury, 18348\nBert = 19019",
    SLASH_NO_ITEM      = "Item not recognised: %s",
    SLASH_NO_PROFILES  = "No player profiles.",
    SLASH_ATLAS_ERROR  = "AtlasLoot: %s",
    SLASH_ITEM_FALLBACK = "Item %d",
    SLASH_HANDOVER_CARRYING = "  %s  %s  → %s (bag %d, slot %d)",
    SLASH_LANGUAGE_NOW = "Language: %s (%s)",
    SLASH_LANGUAGE_SET = "Language set to %s.",
    SLASH_LANGUAGE_UNKNOWN = "Unknown language: %s (en, de, auto)",

    -- What this client can do, in words instead of booleans.
    CAP_masterLootApi       = "Master loot API",
    CAP_masterLootApi_GOOD  = "GiveMasterLoot present — whether 'master' is selectable is up to the group.",
    CAP_masterLootApi_BAD   = "The addon cannot assign loot; hand over by trade.",
    CAP_tradeApi            = "Trade API",
    CAP_tradeApi_GOOD       = "Handovers by trade can be confirmed.",
    CAP_tradeApi_BAD        = "Trade confirmation unavailable — manual only.",
    CAP_guildRoster         = "Guild roster",
    CAP_guildRoster_GOOD    = "Guild members are recorded.",
    CAP_guildRoster_BAD     = "No access to the guild roster.",
    CAP_inspect             = "Inspect",
    CAP_inspect_GOOD        = "Other players' gear is readable in range.",
    CAP_inspect_BAD         = "Own equipment only.",
    CAP_itemLevelApi        = "Item level per item",
    CAP_itemLevelApi_GOOD   = "C_Item.GetDetailedItemLevelInfo — item level is computed here.",
    CAP_itemLevelApi_BAD    = "Falling back to GetItemInfo.",
    CAP_tooltipProcessor    = "Tooltip extension",
    CAP_tooltipProcessor_GOOD = "TooltipDataProcessor — Guild Armory lines in item tooltips are possible.",
    CAP_tooltipProcessor_BAD  = "Falling back to HookScript.",
    CAP_chatInfo            = "Addon messages",
    CAP_chatInfo_GOOD       = "C_ChatInfo available.",
    CAP_chatInfo_BAD        = "No synchronisation possible.",
    CAP_multipleSpecs       = "Several specs per class",
    CAP_multipleSpecs_GOOD  = "Role can be derived from the spec.",
    CAP_multipleSpecs_BAD   = "One spec per class (measured) — do not derive the role from it.",

    -- Header figures
    ACH_STAT_POINTS    = "Points",
    ACH_STAT_DONE      = "Achievements",
    ACH_STAT_FIRSTS    = "Guild firsts",
    ACH_STAT_BYHAND    = "%d by hand",

    -- Tooltip
    ACH_TT_CATEGORY    = "Category: %s",
    ACH_TT_POINTS      = "%d points",
    ACH_TT_UNLOCKED    = "Unlocked %s",
    ACH_TT_CHARACTER   = "On %s",
    ACH_TT_PROGRESS    = "Progress: %d of %d",
    ACH_TT_HOLDER      = "Held by %s",

    -- Categories
    ACH_CAT_FIRSTS     = "Guild firsts",
    ACH_CAT_LEVEL      = "Leveling",
    ACH_CAT_LOOT       = "Loot",
    ACH_CAT_RAID       = "Raiding",
    ACH_CAT_WIPES      = "Wipes",
    ACH_CAT_ATTENDANCE = "Attendance",
    ACH_CAT_MASTER     = "Mastery",
    ACH_CAT_PROFESSION = "Professions",
    ACH_CAT_ECONOMY    = "Economy",
    ACH_CAT_PVP        = "PvP",
    ACH_CAT_SOCIAL     = "Social",
    ACH_CAT_COLLECTION = "Collection",
    ACH_CAT_SECRET     = "Secret",

    -- Camp
    CAMP_TITLE         = "Camp",
    CAMP_ALONE         = "Nobody else from the guild in this zone.",
    CAMP_NOTICE        = "Camp list is on. This client now tells the guild which zone you are in, which professions you have and which camp upgrades are in your bags. Your position goes out only in the moment you place a campfire. Switch it off in the settings or with /ga camp off.",

    CAMP_TT_NOPROF     = "Profession not learned.",
    CAMP_TT_UNKNOWN    = "Nothing known — this player is not running the addon, or has not reported yet.",
    CAMP_TT_READY      = "carried",
    CAMP_TT_TOOLOW     = "skill too low",
    CAMP_TT_MISSING    = "not carried",

    CAMP_PROF_ALCHEMY        = "Alchemy",
    CAMP_PROF_BLACKSMITHING  = "Blacksmithing",
    CAMP_PROF_ENCHANTING     = "Enchanting",
    CAMP_PROF_ENGINEERING    = "Engineering",
    CAMP_PROF_HERBALISM      = "Herbalism",
    CAMP_PROF_LEATHERWORKING = "Leatherworking",
    CAMP_PROF_MINING         = "Mining",
    CAMP_PROF_SKINNING       = "Skinning",
    CAMP_PROF_TAILORING      = "Tailoring",
    CAMP_PROF_FIRSTAID       = "First Aid",
    CAMP_PROF_FISHING        = "Fishing",

    CAMP_PLACED_BY     = "%s set up a %s",
    CAMP_PLACED_AT     = "at %.1f, %.1f",
    CAMP_BTN_PIN       = "Map pin",
    CAMP_BTN_PINNED    = "Pin set",
    CAMP_BTN_SHARE     = "Share",
    CAMP_BTN_SHARED    = "Shared",
    CAMP_NO_WAYPOINT   = "This client does not set map pins.",
    CAMP_NO_GROUP      = "Not in a group.",
    CAMP_SHARE_LINE    = "%s — %s: %s",

    CAMP_WHY_ENABLED   = "Camp list: %s",
    CAMP_WHY_ZONE      = "Zone: %s",
    CAMP_WHY_POSITION  = "Position: %s",
    CAMP_WHY_WAYPOINT  = "Map pins: %s",
    CAMP_WHY_BUFF      = "Camp buff: %s",
    CAMP_WHY_NOBUFF    = "not running",
    CAMP_WHY_NOPROF    = "Professions: this client does not report them.",
    CAMP_WHY_NOCAMP    = "no camp upgrades",
    CAMP_WHY_ITEMS     = "Item names known: %d of %d",
    CAMP_WHY_COUNT     = "Bag count: %s, carrying %d upgrades",
    CAMP_WHY_SPELLS    = "Use spells resolved: %d of %d",
    CAMP_WHY_ROSTER    = "In this zone: %d, of those with data: %d",
    CAMP_WHY_REJECTED  = "Rejected: catalog %d, field %d, zone or map %d, stale %d",

    SET_CAMP           = "Camp list",
    SET_CAMP_HINT      = "A small bar showing who from the guild is standing in your zone, which professions they have and which camp upgrades they carry — plus a notice when somebody places a campfire. While it is on, this client reports the same about you to the guild; your position only at the moment you place a campfire. Off means this client neither sends nor receives.",
    SLASH_CAMP         = "Camp list: %s",

    -- Crafting
    NAV_CRAFTING       = "Crafting",
    CRAFT_PROFESSIONS  = "Professions",
    CRAFT_WHO          = "Who can make it",
    CRAFT_SEARCH       = "Item name, link or ID",
    CRAFT_CONTEXT      = "%d professions",
    CRAFT_FOUND        = "%d can make %s",
    CRAFT_NOBODY       = "Nobody known can make %s — which may only mean nobody has opened that profession window yet.",
    CRAFT_NO_ITEM      = "No item found for \"%s\".",
    CRAFT_KNOWN        = "%d characters, %d recipes known.",
    CRAFT_EMPTY        = "Nothing known yet. Open each profession window once, and ask the guild with /ga craft sync.",
    CRAFT_STATS        = "Crafting: %d characters, %d professions, %d recipes.",
    CRAFT_HOWTO        = "Recipes can only be read while a profession window is open. Open each of yours once; /ga craft scan reads the open one again.",
    CRAFT_SCAN_LINE    = "%s read: %d recipes, skill %d.",
    CRAFT_SCAN_SAME    = "%s unchanged: %d recipes.",
    CRAFT_SYNCED       = "Asked the guild and sent your own professions.",
    CRAFT_LINKS_TITLE  = "Profession links — what the open button depends on",
    CRAFT_OPEN_SENT    = "Profession link sent (%s) — the window comes from the server, and only while the other player is online.",
    CRAFT_OPEN_STALE   = "If no window appears: the link from %s was recorded %s. It only works while that player is online AND has had their profession window open this session.",
    CRAFT_LINKS_OWN    = "Own link: %s",
    CRAFT_ERR_nowindow = "No profession window open.",
    CRAFT_ERR_notready = "The profession window has not sent its recipes yet — try again in a moment.",
    CRAFT_ERR_noguid   = "Your own character ID is unreadable on this client.",

    CRAFT_ASK_BUTTON   = "Ask",
    CRAFT_ASK          = "Could you craft %s for me?",
    CRAFT_ASKED        = "Asked %s of %s.",
    CRAFT_ASK_ERR_noitem = "No item selected.",
    CRAFT_ASK_ERR_noname = "No recipient.",
    CRAFT_ASK_ERR_self = "That is you.",
    CRAFT_ASK_ERR_recent = "Already asked for that within the last minute.",
    CRAFT_ASK_ERR_chat = "The whisper could not be sent.",

    TIP_CRAFTED_BY     = "Can be made by",

    -- Bereiche der zweistufigen Navigation
    NAV_OVERVIEW       = "Overview",
    NAV_GUILD          = "Guild",
    NAV_LOOT           = "Loot",
    NAV_PROFESSIONS    = "Professions",
    NAV_EQUIPMENT      = "Equipment",
    NAV_SESSION        = "Session",
    NAV_RULES          = "Rules",

    -- Karte
    MAP_WHY_SHARE      = "Sharing position: %s",
    MAP_WHY_OWN        = "Your position: %s",
    MAP_WHY_CANVAS     = "World map surface found: %s",
    MAP_WHY_SHOWN      = "Map on screen: %s",
    MAP_WHY_KNOWN      = "Known positions: %d on %d maps",
    MAP_WHY_REJECTED   = "Rejected: map %d, field %d",
    MAP_NO_CANVAS      = "No world map surface found — guild pins are off on this client. /ga map why says what was tried.",
    MAP_STATS          = "Map: %d positions known, on %d maps.",
    MAP_SHARING        = "Sharing position: %s",
    MAP_NOTICE         = "The guild map is on: while you are online, this client tells the guild which map you are on and where. Switch it off in the settings or with /ga map off — off means it neither sends nor receives.",

    SET_MAP            = "Guild map",
    SET_MAP_HINT       = "Shows guild members as pins on the world map. While it is on, this client reports your map and your coordinates to the guild for as long as you are online — the furthest-reaching switch in this addon. Your zone was already in the guild roster; the coordinates are what is new. Off means this client neither sends nor receives, and the pins stay empty.",
    SET_MAP_LABELS      = "Name and level beside the pin",
    SET_MAP_LABELS_HINT = "Shows who is standing there next to each dot, without hovering. Off leaves only the dots; the tooltip still says everything.",


    SET_ONSCREEN       = "On screen",


    CRAFT_BACK         = "Back",
    CRAFT_RECIPES_OF   = "%s — %s %d, %d recipes, read %s",
    CRAFT_ENCHANT      = "no item",
    CRAFT_SPELL_FALLBACK = "Recipe %s",

    CRAFT_OPEN         = "Open profession",
    CRAFT_OPEN_NOLINK  = "No profession link yet — that person has not opened their profession window since the addon has been running.",
    CRAFT_OPEN_OFFLINE = "Offline. The profession link asks the server for that character's data, and there is nobody to ask.",
    CRAFT_OPEN_FAILED  = "The profession window could not be opened. The link may have expired; it is only valid for that login session.",

})
