--[[----------------------------------------------------------------------------
    enUS — Grundlage. Wird IMMER geladen; jede andere Sprache ueberschreibt nur.
    Ein Schluessel, der hier fehlt, erscheint im UI als roher Schluessel.
------------------------------------------------------------------------------]]

local _, GA = ...

GA.Core.Locale:Register("enUS", {
    -- Navigation
    NAV_DASHBOARD    = "Dashboard",
    NAV_ARMORY       = "Armory",
    NAV_CHARACTERS   = "Characters",
    NAV_LOOTCOUNCIL  = "Loot Council",
    NAV_LOOTHISTORY  = "History",
    NAV_WISHLIST     = "Wishlist",
    NAV_GEAR         = "Gear Tracking",
    NAV_ARMORY_LONG  = "Guild Armory",
    DASH_CHANGES     = "Recent Changes",
    DASH_ONLINE      = "Guild Online",
    DASH_NO_CHANGES  = "No changes recorded yet.",
    DASH_SNAPSHOT_ROW = "Equipment captured, item level %s",
    DASH_NOBODY_ONLINE = "Nobody online",
    ARMORY_CHARACTERS = "Characters",
    ARMORY_SEARCH    = "Search name",
    SET_NATIVE       = "Frame templates",
    NAV_ANALYTICS    = "Analytics",
    NAV_SETTINGS     = "Settings",

    -- Allgemein
    BTN_CLOSE        = "Close",
    BTN_REFRESH      = "Refresh",
    BTN_EXPORT       = "Export",
    BTN_IMPORT       = "Import",
    BTN_COPY_HINT    = "Ctrl+A, then Ctrl+C",
    UNKNOWN          = "unknown",
    NEVER            = "never",
    JUST_NOW         = "just now",
    AGO_MINUTES      = "%d min ago",
    AGO_HOURS        = "%d h ago",
    AGO_DAYS         = "%d days ago",
    PHASE_LABEL      = "Phase %d",

    -- Dashboard
    DASH_MY_CHARACTER = "My character",
    DASH_GUILD        = "Guild",
    DASH_LOOT_STATE   = "Loot",
    DASH_ITEMLEVEL    = "Item level",
    DASH_EQUIPPED     = "%d of %d slots equipped",
    DASH_MEMBERS      = "%d members, %d online",
    DASH_NOT_IN_GUILD = "Not in a guild",
    DASH_LOOT_METHOD  = "Loot method",
    DASH_LOOT_MASTER  = "You are the master looter",
    DASH_LOOT_NOTMASTER = "Master loot is not active",
    DASH_COMPUTED     = "computed from equipped items",

    -- Armory
    ARMORY_SLOT       = "Slot",
    ARMORY_ITEM       = "Item",
    ARMORY_ILVL       = "ilvl",
    ARMORY_EMPTY      = "empty",
    ARMORY_SNAPSHOT   = "Snapshot: %s",
    ARMORY_NO_DATA    = "No equipment data for this character yet.",
    ARMORY_OWN_HINT   = "Your own equipment is recorded automatically on every change.",
    ARMORY_STALE      = "Last update %s — this is NOT live data.",

    -- Rollen
    ROLE_ADMIN        = "Administrator",
    ROLE_LOOTMASTER   = "Loot Master",
    ROLE_COUNCIL      = "Council",
    ROLE_MEMBER       = "Member",

    -- Einstellungen
    SET_WINDOW        = "Window",
    SET_SCALE         = "Scale: %.2f",
    SET_DEBUG         = "Toggle debug",
    SET_CLIENT        = "This client",
    SET_DATA          = "Data",
    SET_PUBLISH       = "Share my characters with the guild",
    SET_PUBLISH_HINT  = "What leaves: gear, item level, class and level — plus confirmed awards. What does not: notes, nicknames and your change journal. The addon cannot enforce it: whoever does not share shows up in the version overview as no reply.",

    -- Platzhalter fuer spaetere Phasen
    -- Ergaenzt 19.09.2026: Dashboard/Armory-Texte, Inspect, Quellen
    LEVEL_FMT               = "Level %s",
    LOOT_NO_GROUP           = "Not in a group",
    LOOT_NO_GROUP_HINT      = "The loot method only applies in a party or raid.",
    LOOT_FREEFORALL         = "Free for all",
    LOOT_ROUNDROBIN         = "Round robin",
    LOOT_MASTER             = "Master looter",
    LOOT_GROUP              = "Group loot",
    LOOT_NBG                = "Need before greed",
    LOOT_PERSONAL           = "Personal loot",
    CHANGE_EQUIPPED         = "%s: %s equipped",
    CHANGE_UNEQUIPPED       = "%s: %s unequipped",
    ITEM_FALLBACK           = "Item %s",
    ARMORY_LOADOUT_CAPTURED = "Talent loadout captured",
    ARMORY_SNAPSHOT_COUNT   = "%d equipment snapshots since %s",
    ARMORY_OWN              = "Your character",
    ARMORY_GUILD_MEMBER     = "Guild member",
    COL_NAME                = "Name",
    COL_CLASS               = "Class",
    COL_ILVL                = "Ilvl",
    ARMORY_INSPECT_TARGET   = "Inspect target",
    ARMORY_INSPECT_HINT     = "Target a player (within ~28 yd), then inspect.",
    ARMORY_INSPECT_SENT     = "Inspect requested: %s",
    ARMORY_INSPECT_DONE     = "Inspect captured: %s",
    ARMORY_INSPECT_FAILED   = "No reply to the inspect of %s.",
    INSPECT_REASON_notarget = "No target",
    INSPECT_REASON_notplayer= "Target is not a player",
    INSPECT_REASON_self     = "That is you",
    INSPECT_REASON_combat   = "Not while in combat",
    INSPECT_REASON_range    = "Target out of range",
    INSPECT_REASON_api      = "Inspect not available",
    INSPECT_REASON_busy     = "An inspect is still pending",
    SOURCE_self             = "own character",
    SOURCE_inspect          = "inspect",
    SOURCE_sync             = "guild sync",
    SET_ON                  = "on",
    SET_OFF                 = "off",
    SET_STATS               = "%d characters · %d awards · %d journal entries · schema %s",

    -- Charaktere/Spieler und Gear-Verlauf (Phase 3)
    CHAR_PLAYERS            = "Players",
    CHAR_PLAYER_DETAIL      = "%d characters  ·  %s",
    CHAR_MEMBERS            = "Characters",
    CHAR_MEMBERS_OF         = "Characters of %s",
    CHAR_UNASSIGNED         = "Unassigned",
    CHAR_MAIN_TAG           = "|cffe5cc80(Main)|r",
    CHAR_SET_MAIN           = "Set main",
    CHAR_UNLINK             = "Unlink",
    CHAR_ASSIGN             = "Assign",
    CHAR_NEW_PLAYER         = "New player",
    CHAR_ORIGIN_account     = "proven",
    CHAR_ORIGIN_manual      = "set",
    CHAR_ORIGIN_claim       = "claimed",
    CHAR_PROVEN_HINT        = "Same WoW account — a fact, not an entry.",
    CHAR_ALREADY_MAIN       = "Already the main.",
    CHAR_PICK_PLAYER        = "Pick a player on the left first.",
    CHAR_ROLE_HINT          = "The role belongs to the main; alts inherit it.",
    CHAR_ROLE_CURRENT       = "Current role.",
    CHAR_NEED_ADMIN         = "Only an administrator can change roles.",
    CHAR_CONTEXT            = "%d players  ·  %d unassigned",
    GEAR_HISTORY            = "Item level history",
    GEAR_NO_HISTORY         = "No history yet — it starts as soon as equipment changes.",
    GEAR_SNAPSHOTS          = "%d snapshots",
    GEAR_DISCRETE           = "One bar per captured snapshot, nothing in between.",

    -- Loot-Historie und Erfassung (Phase 5)
    COL_WHEN                    = "When",
    COL_ITEM                    = "Item",
    COL_WHO                     = "Recipient",
    COL_STATUS                  = "Status",
    COL_PROOF                   = "Confirmed by",
    LOOT_SEARCH                 = "Item or player",
    LOOT_ONLY_OPEN              = "Open only",
    LOOT_DETAIL                 = "Details",
    LOOT_PICK_ROW               = "Select a row.",
    LOOT_SUMMARY                = "%d recorded  ·  %d open  ·  %d confirmed by hand",
    LOOT_CONTEXT                = "%d entries",
    LOOT_STATUS_DETECTED        = "detected",
    LOOT_STATUS_SESSION_OPEN    = "bidding open",
    LOOT_STATUS_AWARDED         = "awarded",
    LOOT_STATUS_TRANSFER_PENDING= "transfer pending",
    LOOT_STATUS_RECEIVED        = "received",
    LOOT_STATUS_EQUIPPED        = "equipped",
    LOOT_STATUS_CANCELLED       = "cancelled",
    LOOT_STATUS_CORRECTED       = "corrected",
    LOOT_PROOF_MASTER_LOOT      = "Master loot",
    LOOT_PROOF_TRADE            = "Trade",
    LOOT_PROOF_LOOT_CHAT        = "Chat message",
    LOOT_PROOF_MANUAL           = "by hand",
    LOOT_PROOF_NONE             = "—",
    LOOT_PROOF_STRONG           = "Reported by the game",
    LOOT_PROOF_WEAK             = "Weak evidence",
    LOOT_FROM_ENCOUNTER         = "Encounter: %s",
    LOOT_FROM_CREATURE          = "From %s",
    LOOT_FROM_NPCID             = "NPC %s",
    LOOT_FROM_UNKNOWN           = "Source unknown",
    SET_LOOT                    = "Loot tracking",
    SET_LOOT_THRESHOLD          = "From quality: %s",
    SET_LOOT_SOLO               = "Track outside a group too",
    SET_LOOT_SOLO_HINT          = "For testing alone. Off in normal use, or every quest item lands in the history.",
    SET_MEASURED                = "Observed loot methods: %s",
    SET_MEASURED_NONE           = "none yet",
    QUALITY_2                   = "Uncommon",
    QUALITY_3                   = "Rare",
    QUALITY_4                   = "Epic",
    LOOT_CORRECTION_OF          = "Correction of %s",
    LOOT_CORRECTED_BY           = "Corrected by %s",

    -- Minimap-Knopf
    MINIMAP_LEFT                = "Left click: open the window",
    MINIMAP_RIGHT               = "Right click: settings",
    MINIMAP_DRAG                = "Drag: move the button",
    MINIMAP_STATS               = "%d characters  ·  %d awards",
    SET_MINIMAP                 = "Show minimap button",

    -- LootCouncil (Phase 4)
    BID_TITLE                   = "Loot bid",
    BID_HINT                    = "Pick one answer per item.",
    BID_FROM                    = "Loot master: %s",
    BID_ANSWERED                = "Answered: %s",
    BID_FAILED                  = "Could not send the bid (%s).",
    COUNCIL_OPEN                = "Open session",
    COUNCIL_CLOSE               = "Close",
    COUNCIL_ITEMS               = "Items",
    COUNCIL_DETECTED_TITLE      = "Detected loot",
    COUNCIL_CANDIDATES          = "Candidates",
    COUNCIL_CANDIDATES_FOR      = "Candidates: %s",
    COUNCIL_VOTE                = "Vote",
    COUNCIL_AWARD               = "Award",
    COUNCIL_BIDS                = "%d bids",
    COUNCIL_RUNNING             = "Session running: %d items  ·  loot master %s",
    COUNCIL_DETECTED            = "%d items detected — session not opened yet",
    COUNCIL_IDLE                = "No open session, nothing detected.",
    COUNCIL_FOOTER              = "%d bids  ·  %d votes cast",
    COUNCIL_PICK_ITEM           = "Pick an item on the left.",
    COUNCIL_HINT                = "Loot is detected when the loot window opens. Then open the session here.",
    COUNCIL_CONTEXT_OPEN        = "session running",
    COUNCIL_NEED_LOOTMASTER     = "Only the loot master can do that.",
    COUNCIL_NEED_COUNCIL        = "Only the council can vote.",
    COUNCIL_ALREADY_OPEN        = "A session is already running.",
    COUNCIL_NO_SESSION          = "No open session.",
    COUNCIL_NOTHING_DETECTED    = "No detected loot.",
    COUNCIL_NO_CANDIDATE        = "%s is not in the master loot list — transfer stays open.",
    COUNCIL_ERR_notallowed      = "You lack the permission for that.",
    COUNCIL_ERR_alreadyopen     = "A session is already running.",
    COUNCIL_ERR_noitems         = "No items selected.",
    COUNCIL_ERR_noeligible      = "Nothing detected to open.",
    COUNCIL_ERR_nobid           = "That player did not bid.",
    COUNCIL_ERR_closed          = "The session is closed.",

    -- Wunschliste und Statistik (Phase 6)
    WISH_MINE                 = "My wishlist",
    WISH_MINE_COUNT           = "My wishlist — %d open, %d fulfilled",
    WISH_OTHERS               = "Who else wants it?",
    WISH_OTHERS_FOR           = "Who else wants: %s",
    WISH_INPUT                = "Wowhead link, item link, ID or name",
    WISH_DROP_HINT            = "Paste a Wowhead link or item link, or type an item ID or name.",
    WISH_NO_ITEM              = "No item recognised — paste a link or type a name.",
    WISH_SEARCH_TITLE         = "Search results (%d)",
    WISH_SEARCH_EMPTY         = "Nothing found. The index knows %d items.",
    WISH_SEARCH_HINT          = "It only holds what this client has already seen — an addon cannot query Wowhead. Pasting a Wowhead link always works.",
    WISH_SEARCH_STATUS        = "Searching this client's index (%d items). Click a result.",
    SET_ITEMINDEX             = "Item index: %d items",
    SET_SYNC                  = "Sync: %d other clients seen, %d conflicts",
    EXPORT_TITLE              = "Export for the web app",
    EXPORT_DONE               = "Export built: %d characters, %d awards, %d KB.",
    EXPORT_HINT               = "It reaches the file on logout or /reload — an addon cannot reach the network itself.",
    SET_EXPORT                = "Export: %d KB, as of %s",
    SET_EXPORT_NONE           = "Export: none built yet",
    ANNOUNCE_AWARD            = "%s to %s",
    ANNOUNCE_REASON           = " (%s)",
    ANNOUNCE_SOURCE           = " — %s",
    ANNOUNCE_LIMIT            = "Announcements stopped: %d this session is the limit.",
    SET_ANNOUNCE              = "Announce confirmed awards in guild chat",
    SET_ANNOUNCE_HINT         = "Confirmed transfers only, loot master only, at most one every 3 seconds. If the guild bridges guild chat to Discord, it lands there too.",
    SET_COMBATLOG      = "Turn on combat logging in raids",
    SET_COMBATLOG_HINT = "Writes WoWCombatLog.txt while you are in a raid instance — several megabytes per evening, containing the names of everyone present, including people outside the guild. The addon cannot read the file; it is there for the companion program and the website. Off by default.",
    COMBATLOG_UNAVAILABLE = "This client does not let an addon start combat logging. Type /combatlog yourself before the raid.",
    COMBATLOG_FAILED   = "Combat logging could not be started — the call went through but nothing changed.",
    SET_COLLECTOR             = "Collector mode: reload hourly",
    SET_COLLECTOR_HINT        = "The client writes the web app file ONLY on logout and /reload. This reloads every %d minutes — never in combat, never during a loot session. Meant for one client parked for the job.",
    EXPORT_RELOAD_SOON        = "Guild Armory reloads in %d seconds (collector mode).",

    IMPORT_TITLE              = "Read a backup",
    IMPORT_HINT               = "Paste the export block here. Import adds and overwrites nothing: your own measured gear stays, conflicting awards go to the journal.",
    IMPORT_FROM               = "From %s, exported by %s (%s)",
    IMPORT_CHARS              = "Characters: %d new, %d updated, %d unchanged",
    IMPORT_AWARDS             = "Awards: %d new, %d already known",
    IMPORT_CONFLICTS          = "%d conflicts — they go to the journal, nothing is overwritten",
    IMPORT_REST               = "Wishlists: %d  ·  player profiles: %d  ·  items: %d",
    IMPORT_CONFIRM            = "To apply, run again: /ga import",
    IMPORT_DONE               = "Import done: %d characters, %d awards, %d conflicts.",
    IMPORT_ERR_empty          = "Nothing pasted.",
    IMPORT_ERR_badjson        = "That is not a valid export block.",
    IMPORT_ERR_badformat      = "Foreign format — this did not come from Guild Armory.",
    IMPORT_ERR_newer          = "The backup is from a newer version. Update the addon.",
    IMPORT_ERR_noexport       = "No export block in this database. Run /ga export first.",

    HIST_JOINED               = "joined",
    HIST_LEFT                 = "no longer on the roster",
    HIST_PROMOTED             = "promoted",
    HIST_DEMOTED              = "demoted",
    HIST_KNOWN_SINCE          = "known since %s",
    HIST_JOINED_SINCE         = "joined %s",
    HIST_FROM_RANK            = "from %s",

    TIP_WISHED                = "On the wishlist:",
    TIP_AND_MORE              = "and %d more",
    TIP_LAST_AWARD            = "Last awarded to %s (%s)",
    TIP_ILVL                  = "Item level %s  ·  %s, %s",
    TIP_LAST_LOOT             = "Last received: %s (%s)",
    SET_TOOLTIPS              = "Extend tooltips",
    SET_TOOLTIPS_HINT         = "Wishlist hits on items, item level and last award on players. Foreign data always shows its source and age.",
    NOTE_NICKNAME             = "Nickname",
    NOTE_NOTE                 = "Note",
    NOTE_HINT                 = "Stays on this client. Notes about other players do not travel through the guild unasked.",
    WISH_REMOVE               = "Remove",
    WISH_FULFILLED            = "received %s",
    WISH_ALREADY_GOT          = "already has it",
    WISH_NOBODY_ELSE          = "Nobody else.",
    WISH_PICK                 = "Select an entry on the left.",
    WISH_CONTEXT              = "%d open wishes",
    WISH_ERR_noitem           = "No item recognised.",
    WISH_ERR_nocharacter      = "No character.",
    WISH_ERR_unknownpriority  = "Unknown priority.",
    ANA_BY_PLAYER             = "By player",
    ANA_BY_CHARACTER          = "By character",
    ANA_BY_SOURCE             = "By source",
    ANA_BY_RESPONSE           = "By response",
    ANA_BY_QUALITY            = "By quality",
    ANA_RANGE_ALL             = "All time",
    ANA_RANGE_7               = "7 days",
    ANA_RANGE_30              = "30 days",
    ANA_RANGE_90              = "90 days",
    ANA_TABLE                 = "Breakdown",
    ANA_TIMELINE              = "Over time",
    ANA_ACTIVE                = "Already selected.",
    ANA_DELIVERED             = "confirmed received",
    ANA_UNKNOWN               = "source unknown",
    ANA_NO_DATA               = "No confirmed awards yet.",
    ANA_PENDING               = "%d open",
    ANA_MANUAL                = "%d by hand",
    ANA_CLAIMED               = "link claimed",
    ANA_UNLINKED              = "no profile",
    ANA_SUM_PENDING           = "%d awards without confirmed transfer",
    ANA_SUM_STRONG            = "%d reported by the game",
    ANA_SUM_CHAT              = "%d from chat messages only",
    ANA_SUM_MANUAL            = "%d confirmed by hand only",
    ANA_SUM_UNKNOWN           = "%d without a proven source",
    ANA_SUM_SINCE             = "oldest %s",
    ANA_TIMELINE_HINT         = "One bar per day with a confirmed transfer. Days without awards are absent — this shows events, not a measurement series.",
    ANA_CONTEXT               = "%d received  ·  %d open",

    COUNCIL_ON_WISHLIST       = "Wishlist: %s",
    COUNCIL_WISH_DONE         = "(already received)",

    SET_TRUSTED               = "This is my own backup",
    SET_TRUSTED_HINT          = "Only then do proven main/alt links stay proven. From a foreign file they were the exporter's proof, not yours — they become \"claimed\".",

    TODO_TITLE        = "Not built yet",
    TODO_LOOTCOUNCIL  = "Loot sessions, applications, council votes and the loot master view.",
    TODO_LOOTHISTORY  = "Every confirmed award with status, recipient and council decision.",
    TODO_WISHLIST     = "Per-character and per-player wishlists, matched against awards.",
    TODO_GEAR         = "Equipment snapshots over time, item level curve, per-character comparison.",
    TODO_ANALYTICS    = "Loot per player, character, raid, boss, quality and period.",

    -- Council rotation
    ROTATION_TITLE            = "Council rotation",
    ROTATION_ANNOUNCE         = "Council rotation: %s join the council tonight (%d h).",
    ROTATION_WHISPER          = "You have a loot council seat for the next %d hours. You can vote on awards — /ga council opens the view.",
    ROTATION_ROTATE           = "Rotate",
    ROTATION_CLEAR            = "End seats",
    ROTATION_SEATS            = "Seats per rotation",
    ROTATION_HOURS            = "Duration in hours",
    ROTATION_ENABLED          = "Use council rotation",
    ROTATION_ANNOUNCE_OPT     = "Announce rotation and whisper the chosen",
    ROTATION_ACTIVE           = "Active seats",
    ROTATION_NONE             = "No temporary seat assigned.",
    ROTATION_CYCLE            = "Cycle: %d of %d",
    ROTATION_CYCLED           = "New cycle started",
    ROTATION_EXPIRES          = "expires %s",
    ROTATION_TEMPORARY        = "temporary",
    ROTATION_ERR_NOTALLOWED   = "Only the loot master can rotate.",
    ROTATION_ERR_NOGROUP      = "That needs a group.",
    ROTATION_ERR_NOPOOL       = "Nobody in the raid is eligible.",
    ROTATION_ERR_NOSEATS      = "At least one seat.",
    ROTATION_DONE             = "Rotated: %s",

    -- Version overview
    VERSION_TITLE             = "Versions",
    VERSION_CHECK             = "Check",
    VERSION_RUNNING           = "Asking ...",
    VERSION_CURRENT           = "current",
    VERSION_OUTDATED          = "outdated",
    VERSION_NEWER             = "newer",
    VERSION_UNKNOWN           = "version unreadable",
    VERSION_SILENT            = "no reply",
    VERSION_SILENT_HINT       = "No reply does not mean somebody lacks the addon: offline, out of range or a lost message are just as likely.",
    VERSION_SUMMARY           = "%d current · %d outdated · %d without reply",
    VERSION_SCOPE_GROUP       = "Group",
    VERSION_SCOPE_GUILD       = "Guild",

    -- Pending handovers
    HANDOVER_TITLE            = "Pending handovers",
    HANDOVER_REMIND           = "%d items in your bags belong to others: %s",
    HANDOVER_MORE             = " and %d more",
    HANDOVER_NONE             = "Nothing pending.",
    HANDOVER_CARRYING         = "In your bags",
    HANDOVER_MISSING          = "Not in your bags",
    HANDOVER_MISSING_HINT     = "May be in the bank, equipped, or picked up by the recipient. The addon changes nothing on its own.",
    HANDOVER_WAITING          = "waiting for %s",

    SET_STORAGE      = "Storage: %s",

    STORAGE_EMPTY    = "The client delivered no saved data — the database starts empty. On the Forever beta this is a known defect: writing works, reading does not. Anything you enter today is gone after the next login.",

    -- Rolling
    ROLL_TITLE                = "Rolls",
    ROLL_ANNOUNCE             = "Roll for %s — /roll %d-%d, %d seconds.",
    ROLL_OPEN                 = "Open roll",
    ROLL_CLOSE                = "Close",
    ROLL_RUNNING              = "Roll open: %s (%d-%d)",
    ROLL_IDLE                 = "No roll open.",
    ROLL_COUNT                = "%d rolls, %d still missing",
    ROLL_WINNER               = "Highest roll: %s with %d",
    ROLL_TIE                  = "Tie at %d — %s",
    ROLL_TIE_HINT             = "The addon picks nobody here. How to proceed is the raid's call.",
    ROLL_INVALID_RANGE        = "wrong range",
    ROLL_INVALID_SECOND       = "second roll",
    ROLL_NOBODY               = "Nobody rolled.",
    ROLL_ERR_RUNNING          = "A roll is already open.",
    ROLL_ERR_NOGROUP          = "That needs a group.",
    ROLL_ERR_RANGE            = "That range makes no sense.",

    -- Reserves and plus one
    SOFTRES_TITLE             = "Reserves",
    SOFTRES_OPEN              = "Open round",
    SOFTRES_CLOSE             = "Close round",
    SOFTRES_NONE              = "No reserve round open.",
    SOFTRES_STATS             = "%d reserves from %d players, %d contested",
    SOFTRES_DROPPED           = "Reserved: %s — %s",
    SOFTRES_ORIGIN_LIST       = "entered",
    SOFTRES_ORIGIN_CLAIM      = "self-declared",
    SOFTRES_CONTESTED         = "Reserved more than once",
    SOFTRES_OVERLIMIT         = "Over the limit",
    SOFTRES_IMPORTED          = "%d reserves read, %d skipped",
    SOFTRES_HINT              = "A reserve is for tonight, not forever — and the addon assigns nothing on its own.",
    SOFTRES_ERR_NOROUND       = "No reserve round open.",
    SOFTRES_ERR_NOTALLOWED    = "Only the loot master can open a round.",
    PLUSONE_TITLE             = "Plus one",
    PLUSONE_ROW               = "%s: %d (%d counted, %d adjustment)",
    PLUSONE_MANUAL_HINT       = "%d of those confirmed by hand only",
    PLUSONE_HINT              = "Computed from confirmed awards — not kept. The number cannot contradict the history.",

    COUNCIL_RESERVED = "reserved (%s)",

    SOFTRES_ACK_ok            = "Reserve recorded.",
    SOFTRES_ACK_noround       = "No reserve round is running.",
    SOFTRES_ACK_duplicate     = "You already reserved that.",
    SOFTRES_ACK_overlimit     = "You are over the limit — recorded, but the loot master sees it.",
    SOFTRES_ACK_removed       = "Reserve withdrawn.",
    SOFTRES_ACK_notfound      = "There was nothing to withdraw.",
    SOFTRES_CLAIM             = "Reserve for tonight",
    SOFTRES_MINE              = "My reserves",
    SOFTRES_VS_WISHLIST       = "A wishlist says 'I can use this' and lasts. A reserve says 'this is mine tonight' and lasts one evening.",
    SOFTRES_ERR_NOGROUP2      = "That needs a group.",

    SET_PUBLISH_ON   = "Gear data is shared with the guild.",

    ATLAS_START      = "Reading AtlasLoot: %d items ...",
    ATLAS_DONE       = "AtlasLoot read: %d items, %d names resolved.",
    ATLAS_STATS      = "AtlasLoot: %d sources known, %d names resolved.",
    ATLAS_MISSING    = "AtlasLootClassic is not installed — search uses only what this client has seen itself.",
    ATLAS_SOURCE     = "Drops from: %s",
    ATLAS_OFFER      = "AtlasLoot found. /ga atlas reads the sources and widens the search.",

    ATLAS_LOAD           = "Load AtlasLoot",
    ATLAS_LOADED         = "AtlasLoot: %d sources",
    ATLAS_RUNNING        = "Reading AtlasLoot — this takes a few seconds.",
    ATLAS_RUNNING_SHORT  = "loading ...",
    ATLAS_ERR_RUNNING    = "Already running.",
    ATLAS_ERR_NOTINSTALLED = "AtlasLootClassic is not installed.",
    ATLAS_ERR_NOITEMDB   = "AtlasLoot is present but has no readable database.",
    ATLAS_ERR_NOSTORAGE  = "AtlasLoot is present but has no readable database.",
    ATLAS_ERR_EMPTY      = "AtlasLoot has not loaded anything yet — data modules missing or off.",

    TEST_USAGE       = "/ga test <item> creates a rehearsal award. /ga test clear removes them.",
    TEST_CREATED     = "Rehearsal award created: %s (%s). Open /ga council and start a session.",
    TEST_CLEARED     = "%d rehearsal awards removed.",
    TEST_SOURCE      = "Rehearsal",
    TEST_MARK        = "TEST",

    -- Achievements
    ACH_TITLE          = "Achievements",
    ACH_UNLOCKED       = "Achievement: %s (%d points)",
    ACH_FIRST_REPORTED = "Guild first reported: %s — counts as verified once the guild agrees.",
    ACH_FIRST_CONTESTED= "Guild first contested: %s — same timestamp, no addon decides that.",
    ACH_POINTS         = "%d points from %d of %d achievements",
    ACH_GRANTED_HINT   = "%d of those points entered by hand",
    ACH_STATE_reported = "reported",
    ACH_STATE_verified = "verified",
    ACH_STATE_superseded = "superseded",
    ACH_STATE_contested= "contested",
    ACH_EV_measured    = "measured",
    ACH_EV_observed    = "observed",
    ACH_EV_granted     = "entered",
    ACH_SINCE          = "Counting since %s.",
    ACH_HALL           = "Hall of Fame",

    NAV_ACHIEVEMENTS   = "Achievements",
    ACH_MODE_OWN       = "My achievements",
    ACH_MODE_HALL      = "Hall of Fame",
    ACH_MODE_BOARD     = "Leaderboard",
    ACH_SEARCH         = "Achievement or name",
    ACH_NOT_MEASURABLE = "not measurable yet",
    ACH_HALL_DETAIL    = "%s · %s",
    ACH_BOARD_DETAIL   = "%d achievements, %d guild firsts",
    ACH_CLAIMS         = " (%d claims)",
    ACH_COVERAGE       = "%d of %d achievements are currently measured.",

    ACH_UNREACHABLE    = "not reachable (at most %d)",
    ACH_EMPTY          = "Nothing here for that.",

    -- Entering an achievement by hand. The only possible path for the roughly
    -- forty-five achievements an addon can never measure.
    BTN_CANCEL         = "Cancel",
    BTN_APPLY          = "Apply",
    GRANT_TITLE        = "Enter achievement",
    GRANT_BUTTON       = "Enter by hand",
    GRANT_REVOKE       = "Take back",
    GRANT_PLAYER       = "Player",
    GRANT_SEARCH       = "Player name",
    GRANT_REASON       = "Reason",
    GRANT_REASON_HINT  = "Required. What happened, and who saw it? This is what separates an entry from a measurement — and the date belongs here too, because the timestamp records when it was entered, not when it happened.",
    GRANT_ACCEPT       = "Enter",
    GRANT_NEED_PLAYER  = "Pick a player on the left.",
    GRANT_NEED_REASON  = "A reason is required.",
    GRANT_NEED_ROW     = "Pick an achievement first.",
    GRANT_ALREADY      = "Already there (%s) — entering would change nothing.",
    GRANT_DONE         = "Entered: %s",
    GRANT_REVOKED      = "Taken back: %s",
    GRANT_ERR_UNKNOWN  = "No such achievement.",
    GRANT_ERR_NOPLAYER = "No such player.",
    GRANT_ERR_NOTALLOWED = "Only an administrator can do that.",
    GRANT_ERR_NOREASON = "A reason is required.",
    GRANT_ERR_ALREADY  = "Already unlocked.",
    GRANT_ERR_NOTGRANTED = "Only entries made by hand can be taken back. A measured achievement would be back at the next check.",
    GRANT_ERR_HASCLAIMS = "Someone else reported this guild first from a measurement. Taking it back would discard their claim.",
    GRANT_ERR_CONTESTED = "Contested — same timestamp as another claim.",
    GRANT_ERR_SUPERSEDED = "Someone was earlier.",
    ACH_CAT_PROGRESS   = "%d of %d achievements",
    ACH_CAT_UNTOUCHED  = "none of %d yet",
    ACH_EXPAND_ALL     = "Expand all",
    ACH_COLLAPSE_ALL   = "Collapse all",
    PROBE_TITLE        = "What this client provides",
    PROBE_RESULT       = "Probe: %d usable, %d empty, %d missing",
    ICONS_RESULT       = "Icons checked: %d, unknown: %d",
    ICONS_TITLE        = "Icons this client does not have",

    -- Language. The command words of /ga stay English: they are input, not
    -- output, and have to be typeable from any guide.
    SET_LANGUAGE       = "Language",
    SET_LANGUAGE_AUTO  = "Automatic (client language)",
    SET_LANGUAGE_ENUS  = "English",
    SET_LANGUAGE_DEDE  = "Deutsch",
    SET_LANGUAGE_RELOAD = "Takes full effect after a /reload — text already on screen was written in the old language.",
    SET_LANGUAGE_HINT  = "Default is English. \"Automatic\" follows the game client, which on Forever has been seen to change on its own.",
    BTN_RELOAD         = "Reload now",

    -- /ga
    DASH_TRADABLES     = "Tradable Items",
    DASH_TRADABLES_NONE = "Nobody has offered a rare bind-on-equip item yet.",
    DASH_TRADABLES_ROW = "%s  ·  %s",
    TRADE_OWN          = "Offering %d of %d possible item(s).%s",
    TRADE_NOW_OFFERED  = "Now offered to the guild: %s",
    TRADE_NO_LONGER    = "No longer offered: %s",
    TRADE_NOT_CANDIDATE = "That is not in your bags, or it binds on pickup.",
    TRADE_TEST         = "Test mode: %s — every bag item counts as tradable.",
    TRADE_TEST_ON      = "Test mode is ON. Grey junk is being offered to the guild.",
    TRADE_HOOK_ON      = "Alt-click in your bags is active (via %s).",
    TRADE_HOOK_OFF     = "Alt-click in your bags is NOT available on this client. Use /ga trade add <item> instead.",
    TIP_TRADE_ON       = "Offered to the guild",
    TIP_TRADE_OFF      = "Not offered",
    TIP_TRADE_HINT_ON  = "Alt-click to offer it",
    TIP_TRADE_HINT_OFF = "Alt-click to take it back",
    SET_OFFER_NEW      = "Offer new finds automatically",
    SET_OFFER_NEW_HINT = "Off by default: a rare item you are keeping for an alt should not be advertised without you saying so.",
    TRADE_NONE_OWN     = "Nothing tradable in your bags.",
    TRADE_UNSURE       = "this client cannot tell whether they are already soulbound",
    TRADE_ANNOUNCE     = "Up for trade: %s",
    SLASH_COMBATLOG    = "Auto combat logging: %s   ·   recording right now: %s",
    SLASH_HELP         = "Commands: /ga · armory · scale · debug · language · status · capture · minimap · sync · export · import · rotate · roll · sr · plusone · atlas · icons · probe · combatlog · trade · test · version · handover · reset",
    SLASH_RESET_WARN   = "Resetting \"%s\" deletes %d characters and %d awards.",
    SLASH_RESET_CONFIRM = "To confirm, repeat: /ga reset %s",
    SLASH_RESET_EXPIRED = "Expired, nothing changed.",
    SLASH_RESET_DONE   = "Reset: %s",
    SLASH_RESET_UNKNOWN = "Unknown scope: %s (all, ui, characters)",
    SLASH_SCALE_SET    = "Scale: %.2f",
    SLASH_SCALE_CURRENT = "Current scale: %.2f",
    SLASH_STATUS_VERSION = "Version %s, schema %s, language %s (%s)",
    SLASH_STATUS_STORAGE = "Storage source: %s%s",
    SLASH_STATUS_MIRROR = "(the account-wide file never arrived — mirror in the character file)",
    SLASH_STATUS_COUNTS = "%d characters, %d awards, %d sessions, %d journal entries",
    SLASH_STATUS_TEMPLATES = "Frame templates: %s",
    SLASH_CAPTURED     = "Equipment captured.",
    SLASH_SOURCE_COMMAND = "command",
    SLASH_MINIMAP      = "Minimap button: %s",
    SLASH_ON           = "on",
    SLASH_OFF          = "off",
    SLASH_SYNC         = "Sync: %d clients known, %d conflicts%s",
    SLASH_SYNC_NOTSENT = " — nothing sent (%s)",
    SLASH_SYNC_SHARING_OFF = "sharing off",
    SLASH_SYNC_REJECTED = "Rejected: %d from outside the guild, %d while the roster was unknown",
    SLASH_SYNC_PEER    = "  %s  addon %s, protocol %s",
    SLASH_ROTATE_CLEARED = "%d seats ended.",
    SLASH_ROTATE_STATUS = "Timed seats: %d · cycle %d of %d",
    SLASH_ROTATE_SEAT  = "  %s  %d min left",
    SLASH_BY_HAND      = "by hand",
    SLASH_ROLL_CLOSED  = "Roll round ended.",
    SLASH_SR_CLOSED    = "Round ended.",
    SLASH_SR_IMPORT_EXAMPLE = "Anna: Thunderfury, 18348\nBert = 19019",
    SLASH_NO_ITEM      = "Item not recognised: %s",
    SLASH_NO_PROFILES  = "No player profiles.",
    SLASH_ATLAS_ERROR  = "AtlasLoot: %s",
    SLASH_ITEM_FALLBACK = "Item %d",
    SLASH_HANDOVER_CARRYING = "  %s  %s  → %s (bag %d, slot %d)",
    SLASH_LANGUAGE_NOW = "Language: %s (%s)",
    SLASH_LANGUAGE_SET = "Language set to %s.",
    SLASH_LANGUAGE_UNKNOWN = "Unknown language: %s (en, de, auto)",

    -- What this client can do, in words instead of booleans.
    CAP_masterLootApi       = "Master loot API",
    CAP_masterLootApi_GOOD  = "GiveMasterLoot present — whether 'master' is selectable is up to the group.",
    CAP_masterLootApi_BAD   = "The addon cannot assign loot; hand over by trade.",
    CAP_tradeApi            = "Trade API",
    CAP_tradeApi_GOOD       = "Handovers by trade can be confirmed.",
    CAP_tradeApi_BAD        = "Trade confirmation unavailable — manual only.",
    CAP_guildRoster         = "Guild roster",
    CAP_guildRoster_GOOD    = "Guild members are recorded.",
    CAP_guildRoster_BAD     = "No access to the guild roster.",
    CAP_inspect             = "Inspect",
    CAP_inspect_GOOD        = "Other players' gear is readable in range.",
    CAP_inspect_BAD         = "Own equipment only.",
    CAP_itemLevelApi        = "Item level per item",
    CAP_itemLevelApi_GOOD   = "C_Item.GetDetailedItemLevelInfo — item level is computed here.",
    CAP_itemLevelApi_BAD    = "Falling back to GetItemInfo.",
    CAP_tooltipProcessor    = "Tooltip extension",
    CAP_tooltipProcessor_GOOD = "TooltipDataProcessor — Guild Armory lines in item tooltips are possible.",
    CAP_tooltipProcessor_BAD  = "Falling back to HookScript.",
    CAP_chatInfo            = "Addon messages",
    CAP_chatInfo_GOOD       = "C_ChatInfo available.",
    CAP_chatInfo_BAD        = "No synchronisation possible.",
    CAP_multipleSpecs       = "Several specs per class",
    CAP_multipleSpecs_GOOD  = "Role can be derived from the spec.",
    CAP_multipleSpecs_BAD   = "One spec per class (measured) — do not derive the role from it.",

    -- Header figures
    ACH_STAT_POINTS    = "Points",
    ACH_STAT_DONE      = "Achievements",
    ACH_STAT_FIRSTS    = "Guild firsts",
    ACH_STAT_BYHAND    = "%d by hand",

    -- Tooltip
    ACH_TT_CATEGORY    = "Category: %s",
    ACH_TT_POINTS      = "%d points",
    ACH_TT_UNLOCKED    = "Unlocked %s",
    ACH_TT_CHARACTER   = "On %s",
    ACH_TT_PROGRESS    = "Progress: %d of %d",
    ACH_TT_HOLDER      = "Held by %s",

    -- Categories
    ACH_CAT_FIRSTS     = "Guild firsts",
    ACH_CAT_LEVEL      = "Leveling",
    ACH_CAT_LOOT       = "Loot",
    ACH_CAT_RAID       = "Raiding",
    ACH_CAT_WIPES      = "Wipes",
    ACH_CAT_ATTENDANCE = "Attendance",
    ACH_CAT_MASTER     = "Mastery",
    ACH_CAT_PROFESSION = "Professions",
    ACH_CAT_ECONOMY    = "Economy",
    ACH_CAT_PVP        = "PvP",
    ACH_CAT_SOCIAL     = "Social",
    ACH_CAT_COLLECTION = "Collection",
    ACH_CAT_SECRET     = "Secret",
})
