--[[----------------------------------------------------------------------------
    Achievements/CatalogEN — die englischen Namen und Beschreibungen.

    WARUM EINE EIGENE DATEI (10.10.2026, Wunsch: "die Achievements muessen
    auch auf Englisch sein"): Achievements/Catalog.lua wird aus dem Word-
    Katalog ERZEUGT und traegt die deutschen Texte. Wer dort Englisch
    eintraegt, verliert es beim naechsten Erzeugen. Hier stehen nur die
    Uebersetzungen, je Kennung { Name, Beschreibung }.

    Catalog.ApplyLanguage tauscht Name und Beschreibung jedes Eintrags in die
    aktive Sprache; Locale:Apply ruft es bei jedem Sprachwechsel auf. Die
    deutschen Texte bleiben als nameDE/descriptionDE am Eintrag. Fehlt eine
    Kennung hier, bleibt der deutsche Text stehen — und
    tools/test/achievements.test.js meldet sie.
------------------------------------------------------------------------------]]

local _, GA = ...

local Catalog = GA.Data.Catalog

Catalog.EN = {
    ["GA-001"] = { "The Pioneer", "First guild character to reach level 60" },
    ["GA-002"] = { "Vanguard of the Horde", "First Horde character of the guild to reach level 60" },
    ["GA-003"] = { "Vanguard of the Alliance", "First Alliance character of the guild to reach level 60" },
    ["GA-004"] = { "Top of the Class", "First warrior to reach level 60" },
    ["GA-005"] = { "Master of Magic", "First mage to reach level 60" },
    ["GA-006"] = { "Shadow Master", "First rogue to reach level 60" },
    ["GA-007"] = { "Call of the Wild", "First hunter to reach level 60" },
    ["GA-008"] = { "Dark Path", "First warlock to reach level 60" },
    ["GA-009"] = { "Divine Calling", "First priest to reach level 60" },
    ["GA-010"] = { "Holy Warrior", "First paladin to reach level 60" },
    ["GA-011"] = { "Voice of the Elements", "First shaman to reach level 60" },
    ["GA-012"] = { "Keeper of Nature", "First druid to reach level 60" },
    ["GA-013"] = { "Purple Is the New Green", "First epic item of a guild member" },
    ["GA-014"] = { "A Legend Begins", "First legendary item of the guild" },
    ["GA-015"] = { "Blue Hour", "First rare item of the guild" },
    ["GA-016"] = { "Put the Helmet On", "First set item received" },
    ["GA-017"] = { "Two of Eight", "First two-piece set bonus of the guild" },
    ["GA-018"] = { "Four Wins", "First four-piece set bonus of the guild" },
    ["GA-019"] = { "Eightfold Immortal", "First complete eight-piece set" },
    ["GA-020"] = { "Saddled Up", "First epic mount of the guild" },
    ["GA-021"] = { "Golden Goose", "First character with 1,000 gold" },
    ["GA-022"] = { "Master of the Craft", "First primary profession at its maximum" },
    ["GA-023"] = { "Double Master", "First player with two primary professions at their maximum" },
    ["GA-024"] = { "Master of All Recipes", "First player with every recipe of a profession" },
    ["GA-025"] = { "Vanguard", "First guild character inside a raid instance" },
    ["GA-026"] = { "First Blood", "First raid boss kill of the guild" },
    ["GA-027"] = { "Meltdown", "First guild boss in Molten Core" },
    ["GA-028"] = { "The Firelord Has Fallen", "First Ragnaros kill" },
    ["GA-029"] = { "Dragonslayer", "First Onyxia kill" },
    ["GA-030"] = { "Black Throne", "First Nefarian kill" },
    ["GA-031"] = { "A God Defeated", "First C’Thun kill" },
    ["GA-032"] = { "Ice-Cold Premiere", "First Kel’Thuzad kill" },
    ["GA-033"] = { "Flawless Premiere", "First boss first kill without a single raid death" },
    ["GA-034"] = { "Speedrun Premiere", "First full raid clear in under two hours" },
    ["GA-035"] = { "The First Ten", "First full 10-player guild group" },
    ["GA-036"] = { "The First Forty", "First full 40-player guild group" },
    ["GA-037"] = { "First Among Equals", "First guild rank at officer level" },
    ["GA-038"] = { "Into the Coffers", "First recorded guild bank donation" },
    ["GA-039"] = { "For the Guild", "First epic item crafted for a member" },
    ["GA-040"] = { "The Cartographer", "First player with every flight point" },
    ["GA-041"] = { "Globetrotter", "First player to discover every region" },
    ["GA-042"] = { "Honourable Premiere", "First honourable kill of the guild" },
    ["GA-043"] = { "Rank and Name", "First player at the highest PvP rank" },
    ["GA-044"] = { "Priceless", "First epic upgrade passed in a raid" },
    ["GA-045"] = { "The First Patron", "First player to pass on loot ten times in favour of others" },
    ["GA-046"] = { "The Journey Begins", "Reach level 10 with a character" },
    ["GA-047"] = { "Halfway There", "Reach level 30 with a character" },
    ["GA-048"] = { "Ready for Adventure", "Reach level 40 with a character" },
    ["GA-049"] = { "Almost There", "Reach level 50 with a character" },
    ["GA-050"] = { "All Grown Up", "Reach level 60 with a character" },
    ["GA-051"] = { "Double Life", "Bring 2 of your characters to level 60" },
    ["GA-052"] = { "Trinity", "Bring 3 of your characters to level 60" },
    ["GA-053"] = { "Altaholic", "Bring 5 of your characters to level 60" },
    ["GA-054"] = { "Ten Lives", "Bring 10 of your characters to level 60" },
    ["GA-055"] = { "Warrior Through and Through", "Bring a warrior to level 60" },
    ["GA-056"] = { "Mage Through and Through", "Bring a mage to level 60" },
    ["GA-057"] = { "Rogue Through and Through", "Bring a rogue to level 60" },
    ["GA-058"] = { "Hunter Through and Through", "Bring a hunter to level 60" },
    ["GA-059"] = { "Warlock Through and Through", "Bring a warlock to level 60" },
    ["GA-060"] = { "Priest Through and Through", "Bring a priest to level 60" },
    ["GA-061"] = { "Paladin Through and Through", "Bring a paladin to level 60" },
    ["GA-062"] = { "Shaman Through and Through", "Bring a shaman to level 60" },
    ["GA-063"] = { "Druid Through and Through", "Bring a druid to level 60" },
    ["GA-064"] = { "Class Master", "Bring five different classes to level 60" },
    ["GA-065"] = { "Jack of All Trades", "Bring every class available in Forever to level 60" },
    ["GA-066"] = { "Epic Moment", "Own 1 epic item" },
    ["GA-067"] = { "Purple Rush", "Own 10 epic items" },
    ["GA-068"] = { "Epic Collector", "Own 25 epic items" },
    ["GA-069"] = { "Loot Goblin", "Own 50 epic items" },
    ["GA-070"] = { "Purple Legend", "Own 100 epic items" },
    ["GA-071"] = { "Purple Feet", "5 equipment slots epic or better at the same time" },
    ["GA-072"] = { "Half Gilded", "10 equipment slots epic or better at the same time" },
    ["GA-073"] = { "Almost Complete", "15 equipment slots epic or better at the same time" },
    ["GA-074"] = { "Head to Toe", "18 equipment slots epic or better at the same time" },
    ["GA-075"] = { "A Piece of History", "Own or wear 1 tier set piece" },
    ["GA-076"] = { "Bonus Hunter", "Own or wear 2 matching tier set pieces" },
    ["GA-077"] = { "Four Wins", "Own or wear 4 matching tier set pieces" },
    ["GA-078"] = { "Set for Life", "Own or wear 8 matching tier set pieces" },
    ["GA-079"] = { "Not Today", "Pass voluntarily in the loot council once" },
    ["GA-080"] = { "Modesty", "Pass voluntarily in the loot council 10 times" },
    ["GA-081"] = { "The Benefactor", "Pass voluntarily in the loot council 25 times" },
    ["GA-082"] = { "Loot Saint", "Pass voluntarily in the loot council 50 times" },
    ["GA-083"] = { "Finally Dropped", "Receive a wishlist item after at least 20 recorded kills" },
    ["GA-084"] = { "Perfect Match", "Receive an item with the highest wishlist priority" },
    ["GA-085"] = { "Offspec in Style", "Receive ten offspec items" },
    ["GA-086"] = { "A Taste of Blood", "Reach 1 boss kill" },
    ["GA-087"] = { "Boss Hunter", "Reach 10 boss kills" },
    ["GA-088"] = { "Battle Veteran", "Reach 50 boss kills" },
    ["GA-089"] = { "Raid Machine", "Reach 100 boss kills" },
    ["GA-090"] = { "Unstoppable", "Reach 250 boss kills" },
    ["GA-091"] = { "Boss Encyclopedia", "Reach 500 boss kills" },
    ["GA-092"] = { "Dawn of an Era", "Reach 1 guild first kill" },
    ["GA-093"] = { "Progress Hero", "Reach 5 guild first kills" },
    ["GA-094"] = { "Enforcer", "Reach 10 guild first kills" },
    ["GA-095"] = { "Worldbreaker", "Reach 25 guild first kills" },
    ["GA-096"] = { "Evening Shift", "Reach 10 hours of raiding" },
    ["GA-097"] = { "Regular", "Reach 50 hours of raiding" },
    ["GA-098"] = { "Season Ticket", "Reach 100 hours of raiding" },
    ["GA-099"] = { "Timeless", "Reach 250 hours of raiding" },
    ["GA-100"] = { "Forever", "Reach 500 hours of raiding" },
    ["GA-101"] = { "Flawless Victory", "Defeat a boss without a single raid death" },
    ["GA-102"] = { "The Immortal", "Finish a whole raid without dying yourself" },
    ["GA-103"] = { "With the Last of My Strength", "Boss kill with less than 5 percent of your own health" },
    ["GA-104"] = { "Last One Standing", "Live through a boss kill as the last player alive" },
    ["GA-105"] = { "Right on Time", "Defeat a boss in the very last second of an enrage timer" },
    ["GA-106"] = { "Part of the Game", "Reach 1 wipe" },
    ["GA-107"] = { "Learning Curve", "Reach 25 wipes" },
    ["GA-108"] = { "Stamina Is Everything", "Reach 100 wipes" },
    ["GA-109"] = { "Pain Is Temporary", "Reach 250 wipes" },
    ["GA-110"] = { "Wipe Legend", "Reach 500 wipes" },
    ["GA-111"] = { "Unbreakable", "Reach 1,000 wipes" },
    ["GA-112"] = { "First Contact with the Floor", "Reach 1 raid death" },
    ["GA-113"] = { "Floor Inspector", "Reach 25 raid deaths" },
    ["GA-114"] = { "The Floor Is My Home", "Reach 100 raid deaths" },
    ["GA-115"] = { "Spirit Healer Regular", "Reach 250 raid deaths" },
    ["GA-116"] = { "Tombstone Collector", "Reach 500 raid deaths" },
    ["GA-117"] = { "Lava Is Not a Healing Potion", "Die to lava or environmental damage ten times" },
    ["GA-118"] = { "Frontal Is Also a Position", "Die to a known frontal ability 25 times" },
    ["GA-119"] = { "Don't Stand in the Fire", "Collect 50 avoidable damage events in one evening" },
    ["GA-120"] = { "Chain Reaction", "Die to a mechanic another player set off" },
    ["GA-121"] = { "The Last Survivor", "Be the last player to die in a wipe" },
    ["GA-122"] = { "Repair King", "Cause more than 25 gold in repair costs in one evening" },
    ["GA-123"] = { "Being There Is Everything", "Reach 1 raid attendance" },
    ["GA-124"] = { "Always There", "Reach 10 raid attendances" },
    ["GA-125"] = { "Core Raider", "Reach 50 raid attendances" },
    ["GA-126"] = { "Part of the Furniture", "Reach 100 raid attendances" },
    ["GA-127"] = { "Irreplaceable", "Reach 250 raid attendances" },
    ["GA-128"] = { "A Month Among Friends", "30 days of recorded guild membership" },
    ["GA-129"] = { "Quarter Veteran", "90 days of recorded guild membership" },
    ["GA-130"] = { "Old Guard", "180 days of recorded guild membership" },
    ["GA-131"] = { "A Year Together", "365 days of recorded guild membership" },
    ["GA-132"] = { "Two Years of Loyalty", "730 days of recorded guild membership" },
    ["GA-133"] = { "Part of History", "1,825 days of recorded guild membership" },
    ["GA-134"] = { "Reliable", "Attend 5 scheduled raids in a row" },
    ["GA-135"] = { "Regular Spot", "Attend 10 scheduled raids in a row" },
    ["GA-136"] = { "Iron Streak", "Attend 25 scheduled raids in a row" },
    ["GA-137"] = { "No Evening Without Me", "Attend 50 scheduled raids in a row" },
    ["GA-138"] = { "Fire Brigade", "Step in as a confirmed substitute 5 times" },
    ["GA-139"] = { "The Substitute", "Step in as a confirmed substitute 10 times" },
    ["GA-140"] = { "Rescuer in Need", "Step in as a confirmed substitute 25 times" },
    ["GA-141"] = { "Always on Call", "Step in as a confirmed substitute 50 times" },
    ["GA-142"] = { "First Responsibility", "Reach 1 item handed out" },
    ["GA-143"] = { "The Benefactor", "Reach 25 items handed out" },
    ["GA-144"] = { "Safe Hands", "Reach 100 items handed out" },
    ["GA-145"] = { "Master of Distribution", "Reach 250 items handed out" },
    ["GA-146"] = { "Keeper of the Treasure", "Reach 500 items handed out" },
    ["GA-147"] = { "Calling the Shots", "Reach 1 raid led" },
    ["GA-148"] = { "Raid Leader", "Reach 25 raids led" },
    ["GA-149"] = { "Warlord", "Reach 100 raids led" },
    ["GA-150"] = { "Legendary Commander", "Reach 250 raids led" },
    ["GA-151"] = { "Zero Complaints", "Hand out 50 items without an objection or correction" },
    ["GA-152"] = { "Quick Decision", "Make 25 loot decisions in under 30 seconds" },
    ["GA-153"] = { "Full Transparency", "Record a reason for 100 awards" },
    ["GA-154"] = { "Planner", "Publish ten raids with a confirmed roster" },
    ["GA-155"] = { "Fully Booked", "Fill a raid completely before sign-ups close" },
    ["GA-156"] = { "No Gaps", "Fill ten dropouts in time" },
    ["GA-157"] = { "Chronicler", "Keep 100 historical events with evidence" },
    ["GA-158"] = { "Data Guardian", "Sync 1,000 records successfully between guild clients" },
    ["GA-159"] = { "Handmade", "Reach 1 crafted item" },
    ["GA-160"] = { "Workbench", "Reach 50 crafted items" },
    ["GA-161"] = { "Manufactory", "Reach 250 crafted items" },
    ["GA-162"] = { "Master Workshop", "Reach 1,000 crafted items" },
    ["GA-163"] = { "Apprentice Years", "Learn a primary profession" },
    ["GA-164"] = { "Master Craftsman", "Bring a primary profession to its maximum" },
    ["GA-165"] = { "Double Master", "Bring two primary professions to their maximum" },
    ["GA-166"] = { "Recipe Hunter", "Know 100 different recipes" },
    ["GA-167"] = { "Complete Recipe Book", "Know every available recipe of a profession" },
    ["GA-168"] = { "Guild Supplier", "Craft 100 items directly for guild members" },
    ["GA-169"] = { "Specialist", "Complete a profession specialisation" },
    ["GA-170"] = { "Self-Sufficient", "Get through a whole raid evening on consumables you crafted yourself" },
    ["GA-171"] = { "Rare Plans", "Learn a rare recipe" },
    ["GA-172"] = { "As Good as a Handshake", "Complete 50 confirmed orders without a cancellation" },
    ["GA-173"] = { "Small Contribution", "Reach 10 gold donated" },
    ["GA-174"] = { "Supporter", "Reach 100 gold donated" },
    ["GA-175"] = { "Benefactor", "Reach 500 gold donated" },
    ["GA-176"] = { "Patron", "Reach 1,000 gold donated" },
    ["GA-177"] = { "Golden Pillar", "Reach 5,000 gold donated" },
    ["GA-178"] = { "Giving Back", "Reach 1 item donated" },
    ["GA-179"] = { "Parcel Carrier", "Reach 25 items donated" },
    ["GA-180"] = { "Generosity", "Reach 100 items donated" },
    ["GA-181"] = { "Quartermaster", "Reach 500 items donated" },
    ["GA-182"] = { "Debt-Free", "Own 100 gold for the first time" },
    ["GA-183"] = { "Four Digits", "Own 1,000 gold at the same time" },
    ["GA-184"] = { "Golden Dragon", "Own 5,000 gold at the same time" },
    ["GA-185"] = { "Market Expert", "Record 100 successful auctions" },
    ["GA-186"] = { "Bargain Hunter", "Buy a wishlist item at least 30 percent below the reference price" },
    ["GA-187"] = { "Flask Fund", "Donate consumables for ten complete raids" },
    ["GA-188"] = { "Repair Patron", "Pay for ten guild repairs in full" },
    ["GA-189"] = { "Clean Books", "Record 100 bank transactions without an unexplained entry" },
    ["GA-190"] = { "Liquidity", "Keep at least 1,000 gold in stock for 30 days" },
    ["GA-191"] = { "First Blood in PvP", "Reach 1 honourable kill" },
    ["GA-192"] = { "Skirmisher", "Reach 100 honourable kills" },
    ["GA-193"] = { "Battleground Veteran", "Reach 500 honourable kills" },
    ["GA-194"] = { "Honour Machine", "Reach 1,000 honourable kills" },
    ["GA-195"] = { "Countless", "Reach 5,000 honourable kills" },
    ["GA-196"] = { "Flag Bearer", "Record ten flag pickups" },
    ["GA-197"] = { "Bringing It Home", "Capture ten flags" },
    ["GA-198"] = { "Untouchable", "Win a battleground without dying yourself" },
    ["GA-199"] = { "Outnumbered", "Survive and win a fight against at least three enemies" },
    ["GA-200"] = { "Duellist", "Win 25 confirmed duels" },
    ["GA-201"] = { "Flawless Duellist", "Win ten duels in a row" },
    ["GA-202"] = { "Rank of Honour", "Rise one PvP rank" },
    ["GA-203"] = { "Pinnacle of Honour", "Reach the highest PvP rank" },
    ["GA-204"] = { "Guild Group", "Win a battleground with a full guild group" },
    ["GA-205"] = { "No Prisoners", "Win a battleground with the maximum score difference" },
    ["GA-206"] = { "Healer Hunter", "Defeat 100 players with a healing specialisation" },
    ["GA-207"] = { "Protector", "Control or defeat 100 attackers of a friendly healer" },
    ["GA-208"] = { "Revenge Served", "Defeat the same enemy within two minutes of your own death" },
    ["GA-209"] = { "World PvP", "100 honourable kills outside instanced areas" },
    ["GA-210"] = { "Banner Bearer", "25 victories under a guild banner or a defined guild buff" },
    ["GA-211"] = { "A Helping Hand", "Reach 1 confirmed help" },
    ["GA-212"] = { "Good Soul", "Reach 10 confirmed helps" },
    ["GA-213"] = { "Mentor", "Reach 25 confirmed helps" },
    ["GA-214"] = { "Backbone of the Guild", "Reach 100 confirmed helps" },
    ["GA-215"] = { "Welcome Home", "Join the guild" },
    ["GA-216"] = { "Founding Member", "Be marked as a founding member" },
    ["GA-217"] = { "Welcome Committee", "Welcome ten new members and get their confirmation" },
    ["GA-218"] = { "Teacher", "Guide five new raiders through a mentoring cycle" },
    ["GA-219"] = { "On the Road Together", "Spend 100 hours in guild groups" },
    ["GA-220"] = { "Dungeon Buddy", "Finish 50 dungeons with at least three guild members" },
    ["GA-221"] = { "Full House", "Finish a dungeon with five guild members" },
    ["GA-222"] = { "Meeting in Real Life", "Take part in a confirmed guild meetup" },
    ["GA-223"] = { "Voice of the Guild", "Spend 100 hours in the linked voice channel" },
    ["GA-224"] = { "The Mediator", "Mark five conflicts as confirmed resolved" },
    ["GA-225"] = { "Birthday Child", "Be online on a guild anniversary" },
    ["GA-226"] = { "Night Owl", "Finish a guild run after 2 a.m." },
    ["GA-227"] = { "Early Shift", "Finish a guild run before 8 a.m." },
    ["GA-228"] = { "Travel Group", "Quest with ten different guild members" },
    ["GA-229"] = { "Everybody Knows You", "Group with 50 different guild members" },
    ["GA-230"] = { "Heart of the Community", "Receive a token of thanks from 25 different members" },
    ["GA-231"] = { "First Steps", "Reach 5 zones discovered" },
    ["GA-232"] = { "Wanderer", "Reach 20 zones discovered" },
    ["GA-233"] = { "Cartographer", "Reach 40 zones discovered" },
    ["GA-234"] = { "Globetrotter", "Reach 60 zones discovered" },
    ["GA-235"] = { "Flight Network", "Unlock every flight point of a continent" },
    ["GA-236"] = { "Mount Collector", "Own ten different mounts" },
    ["GA-237"] = { "Stable Master", "Own 25 different mounts" },
    ["GA-238"] = { "Pet Lover", "Own 25 companions" },
    ["GA-239"] = { "Cabinet of Curiosities", "Collect 50 unique rare items" },
    ["GA-240"] = { "Key Ring", "Own every relevant raid attunement key" },
    ["GA-241"] = { "Onyxia's Key", "Complete the whole Onyxia attunement quest" },
    ["GA-242"] = { "Fire Resistant", "Put on a complete fire resistance set" },
    ["GA-243"] = { "Force of Nature", "Put on a complete nature resistance set" },
    ["GA-244"] = { "Frostbitten", "Put on a complete frost resistance set" },
    ["GA-245"] = { "The Bank Is Full", "Unlock every bank slot" },
    ["GA-246"] = { "Bag Pro", "Carry at least a 16-slot bag in every bag slot" },
    ["GA-247"] = { "Fashion over Function", "Have a complete themed outfit confirmed by an officer" },
    ["GA-248"] = { "Souvenir Hunter", "Own at least one item from five different raids" },
    ["GA-249"] = { "Archivist", "Keep 100 different item records in your Armory profile" },
    ["GA-250"] = { "Legacy Complete", "Complete every collection goal defined for a phase" },
    ["GA-251"] = { "Wrong Button", "Successfully start casting your Hearthstone during a boss fight" },
    ["GA-252"] = { "I Deserve This", "Receive three items in one raid evening" },
    ["GA-253"] = { "Big Bag, Little Luck", "Receive no item for ten boss kills in a row" },
    ["GA-254"] = { "On a Roll", "Receive an item from each of three bosses in a row" },
    ["GA-255"] = { "Late to the Party", "Join within 60 seconds of the raid start" },
    ["GA-256"] = { "On the Dot", "Join in exactly the minute the group starts" },
    ["GA-257"] = { "AFK Champion", "Be marked AFK three times in one session" },
    ["GA-258"] = { "Wrong Instance", "Show up in another instance during a scheduled raid" },
    ["GA-259"] = { "Who Needs Buffs Anyway", "Survive a boss without the defined required buffs" },
    ["GA-260"] = { "Naked and Fearless", "Enter an instance with at least one empty equipment slot" },
    ["GA-261"] = { "Forgot to Repair", "Start a raid with at least one red equipment piece" },
    ["GA-262"] = { "That Potion Was Expensive", "Use a consumable potion less than five seconds before the wipe" },
    ["GA-263"] = { "Portal to Where?", "Open a mage portal that does not lead to the announced destination" },
    ["GA-264"] = { "Summon Me", "Be summoned into the same raid instance ten times" },
    ["GA-265"] = { "In the Nick of Time", "Arrive less than ten seconds before the pull" },
    ["GA-266"] = { "Buff Food Gourmet", "Use ten different buff foods in one week" },
    ["GA-267"] = { "Pet Pull", "Cause a confirmed boss pull through a pet" },
    ["GA-268"] = { "At Least It Was Fun", "Die on a pull before the boss takes any damage" },
    ["GA-269"] = { "Don't Click Me", "Use an object marked as forbidden during the fight" },
    ["GA-270"] = { "One More Try", "Be there for the kill after ten wipes in a row" },
    ["GA-271"] = { "Resetting Is a Tactic Too", "Survive five controlled fight resets" },
    ["GA-272"] = { "Guild Armory Beta", "Submit a valid bug report during the beta phase" },
}

--- Name und Beschreibung jedes Eintrags in die Sprache `code`.
--- Deutsch aus dem Katalog, sonst Englisch aus Catalog.EN; was hier fehlt,
--- bleibt deutsch statt leer.
function Catalog.ApplyLanguage(code)
    for id, entry in pairs(Catalog.ENTRIES) do
        if entry.nameDE == nil then
            entry.nameDE = entry.name
            entry.descriptionDE = entry.description
        end
        local en = Catalog.EN[id]
        if code == "deDE" or not en then
            entry.name, entry.description = entry.nameDE, entry.descriptionDE
        else
            entry.name, entry.description = en[1], en[2]
        end
    end
    Catalog.language = code
end

-- Beim Laden gilt die Sprache, die Locale bis hierher gewaehlt hat; bei
-- PLAYER_LOGIN ruft Locale:Apply diese Funktion mit der Einstellung erneut.
Catalog.ApplyLanguage(GA.Core.Locale and GA.Core.Locale.active or "enUS")
